### ISSUE TITLE
improve setup.py

### ISSUE THREAD

**Issue by mattmilten** [SCIP-Interfaces/PySCIPOpt#1]

**Comment by mattmilten** [comment]
SCIP's `src` directory is now linked in `lib` (ef357b8)

**Comment by leethargo** [comment]
In what way exactly should the `setup.py` be improved?

In order to create a `pip` or `conda` installable package, the `setup.py` must probably be non-interactive.

**Comment by mattmilten** [comment]
I suppose we can close this issue since it's part of issue #5.
