### ISSUE TITLE
Increase readability for complex objective functions

### ISSUE THREAD

**Issue by MichaelHoss** [SCIP-Interfaces/PySCIPOpt#104]
Hi everyone,

in my application the decision variables undergo numerous operations inside the objective function.
If I implement the objective function in a single line of code, it would probably be 1000 characters long and be totally unreadable.
How can I make this code more readable without adding additional overhead to the model?

Currently, I have introduced intermediate decision variables (model.addVar()) for readability.
To eliminate these intermediate variables to the solver, I have added additional equality constraints (model.addCons()).
These additional constraints make the intermediate decision variables completely dependent on the actual decision variables.
However, this process makes the model more complicated and potentially slower.

Is there any existing solution to this or is someone thinking about implementing it?

**Comment by mattmilten** [comment]
You need to be more precise. I have no idea what you're trying to achieve. Could you maybe post a smal example code?

**Comment by MichaelHoss** [comment]
Thanks for the quick answer. I hope this reduced example makes it clear:

Say my model for the objective function f(x,y,z) is like this:
```
# declaring decision variables
for i in Xitems:
  x[i] = model.addVar(vtype="CONTINUOUS")
for i in Yitems:
  y[i] = model.addVar(vtype="CONTINUOUS")
for i in Zitems:
  z[i] = model.addVar(vtype="CONTINUOUS")

# setting objective function (not too readable)
# (a,b,c,d are fixed parameters)
model.setObjective(
  quicksum(a*x[i])/b[i] for i in range(0,len(Xitems)))
  + quicksum(i*c[i]*d*y[i]) for i in range(0,len(Yitems)))
  + quicksum(i*i*z[i])/b[i] for i in range(0,len(Zitems))) , "minimize")
```

As you can see, the line for the objective function is becoming pretty long. I would rather have something like this:
```
# defining x contribution
xContrib = model.addVar(vtype="CONTINUOUS")
model.addCons(xContrib == quicksum(a*x[i])/b[i] for i in range(0,len(Xitems))))

# defining y contribution
yContrib = model.addVar(vtype="CONTINUOUS")
model.addCons(yContrib == quicksum(i*c[i]*d*y[i]) for i in range(0,len(Yitems))))

# defining z contribution
zContrib = model.addVar(vtype="CONTINUOUS")
model.addCons(zContrib ==  quicksum(i*i*z[i])/b[i] for i in range(0,len(Zitems))))

# setting up the objective function in a more readable way by using these intermediate variables
model.setObjective(xContrib + yContrib + zContrib , "minimize")
```

However, now I have introduced 3 more variables and 3 more constraints that consume additional memory and that make the optimization slower. 
How can I achieve a more readable code without adding this overhead?

**Comment by mattmilten** [comment]
You can only use linear objective function coefficients and if these coefficients are known from the beginning, you can add them right when adding the variables:

    model.addVar(vtype="C", obj=a/b[i])

**Comment by MichaelHoss** [comment]
This means that those three versions actually do the same?
(for a fixed i) 

```
# completely using the obj argument
x[i] = model.addVar(vtype="C", obj=a/b[i])
model.setObjective(x[i], "minimize")

# completely writing it in the objective setter
x[i] = model.addVar(vtype="C")
model.setObjective((a/b[i])*x[i], "minimize")

# hybrid
x[i] = model.addVar(vtype="C", obj = a)
model.setObjective(x[i]/b[i], "minimize")
```

**Comment by mattmilten** [comment]
Of course not :-)

The first one results in the obj function being `a/b[i] * x[i]`, since you set the obj coef for `x[i]` to `a/b[i]`.

**Comment by mattmilten** [comment]
Of course not :-)

`x[i] = model.addVar(vtype="C", obj=a/b[i])` results in this obj function: `a/b[i] * x[i]`

Adding more variables will modify the obj function accordingly. Calling `setObjective()` on the other hand will overwrite the entire obj function with the one you specified - except if you set the parameter `clear=False`.

**Comment by mattmilten** [comment]
```python
def setObjective(self, coeffs, sense = 'minimize', clear = 'true'):
        """Establish the objective function as a linear expression.
        Keyword arguments:
        coeffs -- the coefficients
        sense -- the objective sense (default 'minimize')
        clear -- set all other variables objective coefficient to zero (default 'true')
        """
```

**Comment by MichaelHoss** [comment]
Thanks a lot! The `clear=false` flag seems very helpful for what I am trying to achieve.

But nevertheless, I never even need to explicitly call `setObjective()` when I just accumulate the whole function by means of the objective coefficients in the `addVar()` calls?

**Comment by mattmilten** [comment]
No, this is not required. The obj coef is an integral part of the variable and hence setup when the variable is created.

**Comment by mattmilten** [comment]
You may close this issue if this solves your problem.

**Comment by MichaelHoss** [comment]
I think it does solve the problem, closing now and thanks again.
