### ISSUE TITLE
Reasons why a constraint is not satisfied in optimal solution

### ISSUE THREAD

**Issue by MichaelHoss** [SCIP-Interfaces/PySCIPOpt#105]
Dear all,

please look at this part of an example code:

```
a = model.addVar(vtype="C")
b = model.addVar(vtype="C")
c = aFunctionThatReturnsADoubleGreaterThanZero(234.4)
myCons = model.addCons(a == c*b)
```

After optimization, I get the strange result that a=100 , but b=0 , which should actually be forbidden by myCons. Trying to investigate on myCons, I used

```
model.getLhs(myCons)
model.getRhs(myCons)
```

which both return 0.0 although the actual left hand side is a=100. 

Also,
`model.getActivity(myCons)`
returns 0.0 although an equality constraint should always be active?!

Any ideas what might have happened? Am I doing the investigation on this constraint right?

**Comment by mattmilten** [comment]
You're doing something wrong. I cannot reproduce the behavior you described.

Try calling `model.writeProblem("myproblem.lp")` to inspect the actual model built inside the solver. Spoiler: Your constraint is going to look like this: `a - c*b == 0`

**Comment by MichaelHoss** [comment]
Thanks for the quick reply... I guess this means that the left hand side is actually `a - c*b` and the right hand side is actually 0, like in the mathematical formulation.

The `myproblem.lp` file tells me
`a - 0.7*b == 0`
But still the optimization result is a=100, while b=0, which makes this constraint infeasible. However, I don't get such an error while solving?!

Of course there could be something going wrong in the rest of my code but I am pretty sure that the problem is related to me missing some important fact about how to use the API. Are there more examples about inspecting a specific constraint through `getLhs(), getRhs(), getActivity()` etc.?

**Comment by mattmilten** [comment]
I'd recommend to use an interactive Python shell like IPython or Jupyter Notebook and then makeheavy use of the auto-complete feature (pressing TAB to see available methods for specific objects).

**Comment by MichaelHoss** [comment]
So I could boil it down to a very specific question related to slack variables. The example is this very simple problem that maximizes x with x<=3.

```
model = Model("Slack Test")
x = model.addVar(vtype="C", name="x")
c = model.addCons(x<=3,name="cons")
model.setObjective(x, "maximize")

model.optimize()

print(model.printBestSol())

print("cons rhs = ", model.getRhs(c))
print("cons lhs = ", model.getLhs(c))

mySol = model.getBestSol()
print("cons slack rhs = ", model.getSlack(c, sol = mySol, side = "rhs"))
print("cons slack lhs = ", model.getSlack(c, sol = mySol, side = "lhs"))
```

I get the following output:

```
objective value:                            3
x                                                   3 	(obj:1)
None
cons rhs =  3.0
cons lhs =  -1e+20
cons slack rhs =  0.0
cons slack lhs =  1e+20
```

What exactly is going on with the slack variable on the left hand side of the constraint? In my imagination, the lhs slack variable should be zero since the constraint is tight.

**Comment by mattmilten** [comment]
I don't see an issue. You constraint has a left hand side of -infinity, hence the corresponding slack is also infinity. What you might be looking for is calling `getSlack()` without specifying a `side`. That way you will get the "correct" or expected result of 0.
