### ISSUE TITLE
Undefined symbol: rl_library_version.

### ISSUE THREAD

**Issue by Viech** [SCIP-Interfaces/PySCIPOpt#107]
I just installed `scipoptsuite 4.0.1` and `python-pyscipopt 1.2.0` on Arch Linux via [this package for scipoptsuite](https://aur.archlinux.org/packages/scipoptsuite) and a local package for `python-pyscipopt` that I am planning to publish, which boils down to `python`/`python2 setup.py install --root=${pkgdir} --optimize=1`. I experience the following issue with both `python 3.6.3` and `python2 2.7.14`:

```
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyscipopt/__init__.py", line 3, in <module>
    from pyscipopt.scip      import Model
ImportError: /usr/lib/libscip.so: undefined symbol: rl_library_version
```

**Comment by mattmilten** [comment]
This is not the official way og obtaining the SCIP Opt Suite and also not the standard way of installing it. Installation has got a lot easier with the additional cmake build system, You might want to try this.

Apart from that, the issue here is with conflicting and incompatible readline libraries. SCIP was built with another version than what's available on your system. You could try to disable readline when installing SCIP - you don't need it anyway if you're not using the interactive shell. Using CMake you can configure your build with `-DREADLINE=off` to disable readline support.

**Comment by Viech** [comment]
Thank you for the quick response! The weird part is that the `scip` command line utility works, and I did not update `readline` since I compiled `scipoptsuite` (which was just an hour ago). I will notify the maintainer of the `scipoptsuite` package so that they can look into using CMake.

**Comment by mattmilten** [comment]
Maybe you have a readline library in your python environment? Conda usually installs a libreadline and this is then used for compiling PySCIPOpt - I also had this issue before. My "solution" was to remove the readline lib that comes with (ana)conda.

**Comment by mattmilten** [comment]
You want to read more here: https://github.com/ContinuumIO/anaconda-recipes/issues/56

**Comment by Viech** [comment]
Could `/usr/lib/python3.6/lib-dynload/readline.cpython-36m-x86_64-linux-gnu.so` (from `cython 0.27.3`) be causing the problem? I do not have Anaconda installed and there is no other readline-related shared library below `/usr/lib/python3.6`. My system readline at the time of compiling the SCIPOpt Suite as well as now is `readline 7.0.003`. Note that I installed `cython` as a requirement for building PySCIPOpt. (I do not yet know if it is also a runtime dependency.) Also, `/usr/lib/python3.6/test/test_readline.py` passes without errors, for what it's worth.

**Comment by mattmilten** [comment]
Could you please check which libraries are used for PySCIPOpt? You need to run `ldd` or `readelf -d` on the generated library (`build/lib.linux-x86_64-3.5/pyscipopt/scip.cpython-35m-x86_64-linux-gnu.so` or something similiar within the `PySCIPOpt` directory).

**Comment by Viech** [comment]
```
% ldd PySCIPOpt-1.2.0/build/lib.linux-x86_64-3.6/pyscipopt/scip.cpython-36m-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffc965f8000)
	libscip.so => /usr/lib/libscip.so (0x00007f5969531000)
	libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x00007f5968fd4000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5968db6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f59689fe000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f59687e7000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f5968554000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f59681cd000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f5967e81000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5967c6a000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5967a66000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f5967863000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f596a0f4000)
```

**Comment by mattmilten** [comment]
OK, there is not even a dependency to readline. I bet there is a missing readline dependency when you run `ldd /usr/lib/libscip.so`. 

Another thing you might try is to delete `libscip.so` and rename `libscipopt.so` to `libscip.so`. We recently changed the library setup and `libscip` was replaced with `libscipopt`. If you use CMake to compile the SCIP Opt Suite you should not have encountered this problem.

**Comment by Viech** [comment]
With the following command I am running `ldd` on all shared libraries included in the package, and look for the string `readline`:
```
% pacman -Ql scipoptsuite|grep -o '/.*\.so$'|xargs ldd|grep readline
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007fbd891ee000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f51ca2b5000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f2ee00bb000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f66ce3d2000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f557da9b000)
```
So this was not causing the issue.

You are right about `libscip.so` versus `libscipopt.so` though! **Your rename proposal fixed my problem.** I will inform the maintainer of the Arch Linux PySCIPOpt package about this and will propose to make use of cmake. Thank you!
