### ISSUE TITLE
Installation using pip on 64-bit Windows 10 with Python 3.6

### ISSUE THREAD

**Issue by LoukasK** [SCIP-Interfaces/PySCIPOpt#110]
I am trying to install PySCIPopt on 64-bit Windows 10 and Python 3.6. As i figured out until now the steps are:

1) Download the executables for Windows 64 -bit from scip.zib.de and run it
2) Open CMD and run: **set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 4.0.1"** in order to set the SCIPOPTDIR variable in environmental variables.
3) Add "C:\Program Files\SCIPOptSuite 4.0.1" in PATH variable (I guess as e.g: %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\SCIPOptSuite 4.0.1)
4) Run: "pip install pyscipopt"

Pip runs correctly but when i am trying to import anything i get the following error:

ImportError: DLL load failed: The specified module could not be found. 

I am sure i'm doing something wrong in the installation process, so excuse me in advance if the answer is quite simple.

**Comment by mattmilten** [comment]
Actually, it should be quite simple: You forgot to add `\bin` to the `SCIPOPTDIR` when extending the `PATH`. See https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.rst#installation-from-pypi

**Comment by LoukasK** [comment]
I've tried it but it still doesn't work, the same error appears. I installed PySCIPopt with both pip install and setup.py, installation works fine, maybe i have to check something else in System Variables in regard to Microsoft Visual Studio?

**Comment by mattmilten** [comment]
Could you please write the entire error message?

**Comment by LoukasK** [comment]
Yes, of course, the error message is:

File "C:\Users\Loukas\AppData\Local\Programs\Python\Python36\lib\site-packages\pyscipopt\__init__.py", line 3, in <module>
    from pyscipopt.scip      import Model
ImportError: DLL load failed: Δεν ήταν δυνατό να εντοπιστεί η καθορισμένη λειτ. μονάδα.

The last phrase is in Greek and it says that "No module found"

**Comment by mattmilten** [comment]
Hmm, I was hoping that it would say which dll couldn't be loaded.

**Comment by mattmilten** [comment]
I just tried on a fresh Anaconda environment: 

```
(C:\Users\m2\Anaconda3) C:\Users\m2>activate scip

(scip) C:\Users\m2>which python
'which' is not recognized as an internal or external command,
operable program or batch file.

(scip) C:\Users\m2>SCIPOPTDIR="C:\Program Files\SCIPOptSuite 4.0.1" pip install pyscipopt
'SCIPOPTDIR' is not recognized as an internal or external command,
operable program or batch file.

(scip) C:\Users\m2>set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 4.0.1"

(scip) C:\Users\m2>pip install pyscipopt
Collecting pyscipopt
  Downloading PySCIPOpt-1.2.0-cp36-cp36m-win_amd64.whl (348kB)
    100% |████████████████████████████████| 358kB 3.3MB/s
Installing collected packages: pyscipopt
Successfully installed pyscipopt-1.2.0

(scip) C:\Users\m2>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyscipopt
>>> m = pyscipopt.Model()
>>> m.optimize()
feasible solution found by trivial heuristic after 0.0 seconds, objective value 0.000000e+00
presolving:
presolving (1 rounds: 1 fast, 0 medium, 0 exhaustive):
 0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
transformed 1/1 original solutions to the transformed problem space
Presolving Time: 0.00

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 0
Primal Bound       : +0.00000000000000e+00 (1 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %
```

**Comment by mattmilten** [comment]
This is WIndows 10 with python 3.6. When I installed the SCIPOptSuite, I may have enabled it to be in my PATH. Apart from that, I don't know what else I have done to make it work.

Could you please try to run SCIP by itself? Just run `bin/scip.exe` in the SCIPOptSuite installation directory.

**Comment by LoukasK** [comment]
I run it and i take the following message: 
"user parameter file <scip.set> not found - using default parameters"

**Comment by mattmilten** [comment]
Yeah, that's perfectly OK. So it seems to run just fine.

**Comment by mattmilten** [comment]
I did another test and ran `pip install pyscipopt` even without specifying the `SCIPOPTDIR` and it worked like a charm. Maybe you should reinstall the SCIPOptSuite?

**Comment by mattmilten** [comment]
The only path in my `PATH` variable that is relevant for this issue is this:
```
PATH=....;C:\Program Files\SCIPOptSuite 4.0.1\bin;.....
```

Could you please confirm that you have such a path in your `PATH`? You can also just open a command line terminal and type `scip` to check whether the `PATH` is correctly set up.

**Comment by mattmilten** [comment]
And you should consider installing [Anaconda](https://www.anaconda.com/download/). This is a very sophisticated Python environment and package manager.

**Comment by LoukasK** [comment]
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\SCIPOptSuite 4.0.1\bin something like this in my PATH i guess. 
I have Anaconda installed but i thought it would be much more difficult to handle PySCIPopt installation.

**Comment by mattmilten** [comment]
Try creating a new environment, fire up the terminal for this environment and run `pip install pyscipopt`. Worked for me...

**Comment by LoukasK** [comment]
IT FINALLY WORKS!!!

**Comment by LoukasK** [comment]
Mr. Milten thank you very much for your help, your immediate response, your truly useful information and the time you spent, it seems it works just fine so, i am ready to start setting up my optimization routine learning PySCIPopt i guess.

**Comment by mattmilten** [comment]
I am glad that it did work out in the end. Could you please share what you did differenlty to make it work this time? Was it really enough to use anaconda and set up a clean environment?

**Comment by LoukasK** [comment]
Finally, the solution was that the only path in the PATH variable must be **"PATH=....;C:\Program Files\SCIPOptSuite 4.0.1\bin;....."** and of course Anaconda was an option to set up a clean environment as i tested it too.

**Comment by gogutier** [comment]
Had the same problem here.. Thanks!

**Comment by eeliubin** [comment]
Hi LoukasK, I met the same problem and somehow cannot fix it. Could you help?

I input the following info step by step, where the Sciopt is installed in D:\Sciopt and Python is installed in D:\Python3plus

set SCIPOPTDIR="D:\Scipopt"

set PATH=%PATH%;%SCIPOPTDIR%\bin

pip install pyscipopt

cd D:\Python3plus\PySCIPOpt

python setup.py install

python setup.py install --debug

**Comment by eeliubin** [comment]
> Finally, the solution was that the only path in the PATH variable must be **"PATH=....;C:\Program Files\SCIPOptSuite 4.0.1\bin;....."** and of course Anaconda was an option to set up a clean environment as i tested it too.

Hi LoukasK, I met the same problem and somehow cannot fix it. Could you help?

I input the following info step by step, where the Sciopt is installed in D:\Sciopt and Python is installed in D:\Python3plus

set SCIPOPTDIR="D:\Scipopt"

set PATH=%PATH%;%SCIPOPTDIR%\bin

pip install pyscipopt

cd D:\Python3plus\PySCIPOpt

python setup.py install

python setup.py install --debug

**Comment by eeliubin** [comment]
> Finally, the solution was that the only path in the PATH variable must be **"PATH=....;C:\Program Files\SCIPOptSuite 4.0.1\bin;....."** and of course Anaconda was an option to set up a clean environment as i tested it too.

Thanks in advance and my email is eeliubin@hotmail.com
Really look forward to your reply.

**Comment by eeliubin** [comment]
> I am glad that it did work out in the end. Could you please share what you did differenlty to make it work this time? Was it really enough to use anaconda and set up a clean environment?

Hi mattmallten, I met the same problem and somehow cannot fix it. Could you help?

I input the following info step by step, where the Sciopt is installed in D:\Sciopt and Python is installed in D:\Python3plus

set SCIPOPTDIR="D:\Scipopt"

set PATH=%PATH%;%SCIPOPTDIR%\bin

pip install pyscipopt

cd D:\Python3plus\PySCIPOpt

python setup.py install

python setup.py install --debug


Thanks!

**Comment by mattmilten** [comment]
Wow.

Do you think it is beneficial to your cause if you describe the problem three times? Hint: It is not.

**Comment by eeliubin** [comment]
> Wow.
> 
> Do you think it is beneficial to your cause if you describe the problem three times? Hint: It is not.

Sorry Matthias, I was thinking LoukasK might not see it...
Really look forward to you help.
Thanks!

**Comment by eeliubin** [comment]
> Wow.
> 
> Do you think it is beneficial to your cause if you describe the problem three times? Hint: It is not.

By the way, is it possible to use the latest SCIP and SCIP-SDP via Matlab, and not through OPTI Toolbox?

**Comment by mattmilten** [comment]
Please open a new issue and explain carefully and detailed what you did, what didn't work and what error messages you got. And please read the install instructions carefully and follow them precisely.

**Comment by eeliubin** [comment]
> Please open a new issue and explain carefully and detailed what you did, what didn't work and what error messages you got. And please read the install instructions carefully and follow them precisely.

Hi Matthias, I just posted a new issue
https://github.com/SCIP-Interfaces/PySCIPOpt/issues/249
Look forward to your help!
Thanks!

**Comment by BigFishDreamWater** [comment]
first  install SCIP SUITE from website
then add path/bin  to the environment variables
then  CMD  and    set SCIPOPTDIR=C:\Program Files\SCIPOptSuite 7.0.2  （make sure your SCIP install this path or your path）
then   pip uninstall  pyscipopt 
then   pip install  pyscipopt 
yeah ,just restart notebook,and it's worked fine.
tips：uninstall last pyscipopt and restart notebook.

**Comment by ashishpatel26** [comment]
> 

This solution is working for me. Thanks 👍👍👍

**Comment by ashishpatel26** [comment]
> I just tried on a fresh Anaconda environment:
> 
> ```
> (C:\Users\m2\Anaconda3) C:\Users\m2>activate scip
> 
> (scip) C:\Users\m2>which python
> 'which' is not recognized as an internal or external command,
> operable program or batch file.
> 
> (scip) C:\Users\m2>SCIPOPTDIR="C:\Program Files\SCIPOptSuite 4.0.1" pip install pyscipopt
> 'SCIPOPTDIR' is not recognized as an internal or external command,
> operable program or batch file.
> 
> (scip) C:\Users\m2>set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 4.0.1"
> 
> (scip) C:\Users\m2>pip install pyscipopt
> Collecting pyscipopt
>   Downloading PySCIPOpt-1.2.0-cp36-cp36m-win_amd64.whl (348kB)
>     100% |████████████████████████████████| 358kB 3.3MB/s
> Installing collected packages: pyscipopt
> Successfully installed pyscipopt-1.2.0
> 
> (scip) C:\Users\m2>python
> Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyscipopt
> >>> m = pyscipopt.Model()
> >>> m.optimize()
> feasible solution found by trivial heuristic after 0.0 seconds, objective value 0.000000e+00
> presolving:
> presolving (1 rounds: 1 fast, 0 medium, 0 exhaustive):
>  0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
>  0 implications, 0 cliques
> transformed 1/1 original solutions to the transformed problem space
> Presolving Time: 0.00
> 
> SCIP Status        : problem is solved [optimal solution found]
> Solving Time (sec) : 0.00
> Solving Nodes      : 0
> Primal Bound       : +0.00000000000000e+00 (1 solutions)
> Dual Bound         : +0.00000000000000e+00
> Gap                : 0.00 %
> ```

> 

This solution is working for me. Thanks 👍👍👍
