### ISSUE TITLE
optimal solution is zero for the easiest problems like puzzle.py and flp.py

### ISSUE THREAD

**Issue by Rotaka92** [SCIP-Interfaces/PySCIPOpt#113]
Hey,
looked through all of your codes now to see what i've done wrong with my model-code for the puzzle.py and especially for the flp.py.
When i run them without any changes, i always get an optimal solution of 0.0. In the flp, none of the edges is bigger than the EPS.

What is the problem here? Has anyone the same issue? I've done no changes to the code at all, just download and run it.

Thanks for your help!

**Comment by mattmilten** [comment]
Weird. I just experienced the same behavior. This must have something to do with the latest SCIP 5.0 release, because my previous version worked just fine.

I will look into that.

**Comment by mattmilten** [comment]
OK, I guess I solved it - at least on my machine it worked. This is what you need to do: Remove all previous installed versions of PySCIPOpt and reinstall again. It might also be enough to run `pip install pyscipopt --upgrade`.

Could you please make sure that you are using the correct SCIP version as well (`model.printVersion()`)? Should be 5.0.0 for PySCIPOpt 1.3. And please check whether the installed pyscipopt is actually the one you would like to use:

```
import pyscipopt
print(pyscipopt.__path__)
```

**Comment by Rotaka92** [comment]
Hey mattmilten,
that advice worked fine for me, got a nice optimal solution =) 
thanks!

**Comment by mattmilten** [comment]
Good to hear! Happy SCIPing, then!
