### ISSUE TITLE
SCIP output not captured in Jupyter notebook

### ISSUE THREAD

**Issue by adbuerger** [SCIP-Interfaces/PySCIPOpt#116]
I noticed that the output of the SCIP solver is not captured when using PySCIPOpt from within a Jupyter notebook, but is still written to the terminal where the Jupyter process is run (tested on Ubuntu 16.04 with Python 2.7 and Jupyter 4.3.0), probably this is related to https://stackoverflow.com/a/46144594 ? It would be a useful feature I think if the output was displayed directly in Jupyter.

**Comment by mattmilten** [comment]
You are right, this can be annoying. I will try to find an easy way to switch the output stream so as it shows up in the notebook.

**Comment by mo271** [comment]
Perhaps this is also useful:
https://groups.google.com/forum/#!topic/jupyter/wK2pGbnKMS8
https://stackoverflow.com/questions/508165

**Comment by stan227** [comment]
The method `model.redirectOutput()` can now be called to fix this problem.
