### ISSUE TITLE
ReOptimization

### ISSUE THREAD

**Issue by isidian** [SCIP-Interfaces/PySCIPOpt#123]
It would be nice to be able to use the re-optimization features of SCIP in the API.  I attempted this myself, and it was a simple enough matter to do
scip.setBoolParam("reoptimization/enable",True)
and also fairly straightforward to modify the .pyx and .pxd files to import SCIPfreeReoptSolve()

But when I tried to implement SCIPchgReoptObjective() it was not going well.  There is a difference in how it is called versus the current implementation of Model.SetObjective().  SCIPchgReoptObjective asks for all variables and coefficients all at once, but the current implementation of Model.SetObjective goes through each variable one at a time, so I cannot simply modify the existing code.

**Comment by isidian** [comment]
Here's a quick hack that I'm using right now.  It borrows heavily from Model.setObjective().

I say it's a quick hack because it doesn't include any kind of error checking, which would be important if this were pushed into the repo version.

```
def chgReoptObjective(self, coeffs, sense = 'minimize'):
        """Establish the objective function as a linear expression.

        :param coeffs: the coefficients
        :param sense: the objective sense (Default value = 'minimize')

        """

        cdef SCIP_OBJSENSE objsense

        if sense == "minimize":
            objsense = SCIP_OBJSENSE_MINIMIZE
        elif sense == "maximize":
            objsense = SCIP_OBJSENSE_MAXIMIZE
        else:
            raise Warning("unrecognized optimization sense: %s" % sense)
        
        assert isinstance(coeffs, Expr)

        if coeffs.degree() > 1:
            raise ValueError("Nonlinear objective functions are not supported!")
        if coeffs[CONST] != 0.0:
            raise ValueError("Constant offsets in objective are not supported!")

        cdef SCIP_VAR** _vars
        cdef int _nvars
        _vars = SCIPgetOrigVars(self._scip)
        _nvars = SCIPgetNOrigVars(self._scip)
        _coeffs = <SCIP_Real*> malloc(_nvars * sizeof(SCIP_Real))
        
        for i in range(_nvars):
            _coeffs[i] = 0.0
        
        for term, coef in coeffs.terms.items():
            # avoid CONST term of Expr
            if term != CONST:
                assert len(term) == 1
                var = <Variable>term[0]
                for i in range(_nvars):
                    if _vars[i] == var.var:
                        _coeffs[i] = coef

        PY_SCIP_CALL(SCIPchgReoptObjective(self._scip, objsense, _vars, &_coeffs[0], _nvars))

        free(_coeffs)
```

**Comment by mattmilten** [comment]
The code looks good to me. You should open a pull request to get the code tested and reviewed.
Please excuse my late reaction to this issue.

**Comment by isidian** [comment]
I've initiated the pull request after adding the changes to a fork created from the most recent master.

**Comment by mattmilten** [comment]
#132

**Comment by fserra** [comment]
we should probably add a test for this

**Comment by mattmilten** [comment]
I did't see your comment @fserra. Sorry!

**Comment by isidian** [comment]
I've been using this fix for a while now to do some re-optimization work, but there is one bug in it that I've found.  If the LP is infeasible, then the program will crash as soon as Model.__del__ is called (automatically or otherwise).  I haven't been able to figure out which part of the destructor method is causing the crash.

Here's an easy way to reproduce the problem:
`
from pyscipopt import Model

model = Model()
model.setBoolParam("reoptimization/enable",True)

x = model.addVar('x')
model.addCons(x == 1)
model.addCons(x == 2)

model.optimize()

print('Optimization done')
del model                          #CRASH
print('Destructor done')    #never gets here
`

Any ideas?

**Comment by mattmilten** [comment]
I ran your example in debug mode and apparently there is a assert failiing in the reoptimization part of SCIP:

```
>> python reoptbug.py
presolving:
presolving (1 rounds: 1 fast, 0 medium, 0 exhaustive):
 1 deleted vars, 1 deleted constraints, 0 added constraints, 2 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolving detected infeasibility
Presolving Time: 0.00

SCIP Status        : problem is solved [infeasible]
Solving Time (sec) : 0.00 (over 0 runs: 0.00)
Solving Nodes      : 0 (0 reactivated)
Primal Bound       : +1.00000000000000e+20 (0 solutions)
Dual Bound         : -1.00000000000000e+20
Gap                : infinite
Optimization done
python: /home/optimi/bzfmilte/opti/code/scipoptsuite/scip/src/scip/reopt.c:1346: cleanActiveConss: Assertion `reopt->activeconss != NULL' failed.
Aborted
```

**Comment by mattmilten** [comment]
This is indeed a bug in SCIP itself. You would need to wait for the next bugfix release :cry:
