### ISSUE TITLE
setup travis

### ISSUE THREAD

**Issue by xmunoz** [SCIP-Interfaces/PySCIPOpt#13]
There are tests! We should run them. I personally like travis-ci.

**Comment by leethargo** [comment]
I'd welcome this, but I'm not sure whether

1. Travis only allows open-source projects.
2. The binary depedencies are easily setup for CI.

**Comment by leethargo** [comment]
If we manage to get 2. working, that would be great and also very interesting for [SCIP.jl](https://github.com/leethargo/SCIP.jl).

**Comment by mueldgog** [comment]
We provide the VS compiled SCIP and JNI libraries since creating those for Windows is a mess with our current Makefiles. For Linux everything works fine, so I don't really see a reason to provide the `libscipopt.so`.

**Comment by leethargo** [comment]
I see.
