### ISSUE TITLE
Unexpected behavior of "check" flag in addCons

### ISSUE THREAD

**Issue by g-munoz** [SCIP-Interfaces/PySCIPOpt#130]
Dear PySCIPOpt Team,

I have been running some experiments where I need to modify the "check" flag, and I have been observing some strange behavior. I am attaching a Python script that evidences this.

In this example, I create a minimization problem whose optimal value is -17. If I add some redundant non-linear constraints with "check=True" then the value stays at -17 as expected. However, if I set "check=False" in one of these redundant constraints, the value jumps to 0, which shouldn't happen, as SCIP should be checking for fewer constraints for feasibility.

I hope you can help me with this, and I apologize if the issue is something simple I'm not seeing.

Best,
Gonzalo.

[checkIssue.zip](https://github.com/SCIP-Interfaces/PySCIPOpt/files/1720996/checkIssue.zip)

**Comment by fserra** [comment]
So I can't reproduce this; can you try the latest SCIP version and if it fails again, can you write here what you used to install SCIP and the interface

**Comment by g-munoz** [comment]
Updating to SCIP 5.0.1 fixed the issue. I hadn't noticed there was a newly released version. Thank you for your help!
