### ISSUE TITLE
setting `lb` to `None` fails

### ISSUE THREAD

**Issue by mo271** [SCIP-Interfaces/PySCIPOpt#145]
In the`addVar` method, in the description we can read:
`:param lb: lower bound of the variable, use None for -infinity (Default value = 0.0)`

I tried setting `lb` to `None`, but it fails:
```
In [9]: M = Model()

In [10]: M.addVar(ub=None)
Out[10]: x1

In [11]: M.addVar(lb=-M.infinity())
Out[11]: x2

In [12]: M.addVar(lb=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-eeff3f28bbf0> in <module>()
----> 1 M.addVar(lb=None)

src/pyscipopt/scip.pyx in pyscipopt.scip.Model.addVar()

TypeError: a float is required
```
One can get it to work with `-M.infinity()`, but just setting `None` would be nicer, especially since it is mentioned in the doc and already works for `ub`.

**Comment by fserra** [comment]
Oh yes. We actually have this in the latest master but not in the pip
package, if I remember correctly.

Did you use pip install or are you compiling the interface?

**Comment by mo271** [comment]
Yes, this was version 1.4.0 from pypi. It works indeed with the current master branch!

I am looking forward to a fresh pip version...

Thank you for the quick reply.

**Comment by mattmilten** [comment]
Release 1.4.1 is on its way!

**Comment by mo271** [comment]
cool!
