### ISSUE TITLE
Model.writeProblem() causes TypeError (version 1.4.3 with Python 3)

### ISSUE THREAD

**Issue by chofchof** [SCIP-Interfaces/PySCIPOpt#154]
# What is problem?

From the version 1.4.3, `Model.writeProblem()` (in `scip.pyx`) causes `TypeError` with Python 3.

The reason is as follows:

1. For Python 3, `str_conversion` is defined as (line 31)
>    str_conversion = lambda x:bytes(x,'utf-8')

2. In the definition of `writeProblem()` the first three lines are (line 741-743)
>    fn = str_conversion(filename)
>    fname, fext = splitext(fn)
>    ext = str_conversion(fext)

3. The default value of `filename='origprob.cip'`. After running the first and the second line we may have `fname=b'origprob'` and `fext=b'.cip'`.

4. How about the third line? It is `str_conversion(fext)`, that is, `bytes(b'.cip','utf-8')` which generates the following error, because an extra encoding `utf-8` was given for the binary array.
> TypeError: encoding without a string argument

# How to solve?

It's simple. Just replace `ext = str_conversion(fext)` (line 743) with `ext = fext`.

**Comment by mattmilten** [comment]
Thank you for the detailed report and the suggested fix!

**Comment by chofchof** [comment]
You're welcome. I appreciate this project.
