### ISSUE TITLE
Log function

### ISSUE THREAD

**Issue by martinerr** [SCIP-Interfaces/PySCIPOpt#167]
Is there a way to use a log function on decision variables? I've found this old issue, where I see it wasn't implemented yet in 2016. Is there any update now? See: https://github.com/SCIP-Interfaces/PySCIPOpt/issues/41 

Thank you!

**Comment by fserra** [comment]
Hi, yes you can. In `test_expr.py` we build logarithmic expressions... a bit artificial though.

**Comment by martinerr** [comment]
Oh great! Thank you for your very quick reply. Is there anything else I should do besides import the log or exp? Because I get an AssertionError.

I imported the expressions like this:
from pyscipopt import Model, quicksum, multidict, log, exp

And I wrote the objective function like this:
model.setObjective(quicksum((exp(z[i,p])) for i in C for p in P), "maximize")

Thanks!

**Comment by fserra** [comment]
oh, sorry  
you can't have nonlinear objectives. You have to linearize it, using the so-called epigraphical representation (or something like that). That is:

1. add a new variable, `objvar = model.addVar(name="objvar", type= "C", lb=None, ub=None)`
1. use that constraint as the objective `model.setObjective(objvar, "maximize")`
1. and then add a constraint `model.addCons(objvar <= quicksum((exp(z[i,p])) for i in C for p in P))`

**Comment by jj314** [comment]
@fserra Does it make a difference with respect to performance whether the auxiliary constraint is a <= vs ==?

**Comment by fserra** [comment]
In principle, it could. So if your objective is concave and you add objvar <= obj, then this is a convex constraint, while objvar == obj is non-convex. Now, of course SCIP could detect this, but I am not sure right now if it is going to do that, so I would use <= as a rule of thumb.
