### ISSUE TITLE
Can't create ranged rows with obvious syntax "lhs <= expr <= rhs"

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/PySCIPOpt#17]
As stated in the [corresponding test](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/tests/test_linexpr.py#L193), for Python syntax reasons, we would need some parenthesis to express ranged constraints (with both lhs and rhs).

This is already broken in the examples, as discovered in a [SCIP issue](https://git.zib.de/integer/scip/issues/1023).

Also, this fact should at least be highlighted in the documentation.

Maybe, we can also catch the exception that is thrown and work around the issue with some Python magic?

**Comment by leethargo** [comment]
Relevant [PEP](https://www.python.org/dev/peps/pep-0335/) that was rejected.

**Comment by leethargo** [comment]
[Discussion on StackOverflow](http://stackoverflow.com/questions/17666876/chaining-comparisons-overloading-the-not-overloadable-and-operator) with somebody having the same problem. We don't want to quote the expressions, so we should instead keep using the parenthesis :disappointed:

**Comment by fserra** [comment]
is it possible to catch and then create two constraints?

**Comment by fserra** [comment]
do you know if you can write ranged constraints in gurobi.py??

**Comment by leethargo** [comment]
In Gurobi, there's a special method [addRange](https://www.gurobi.com/documentation/6.5/refman/py_model_addrange.html) that you'd have to use:
```
# 1 <= x + y <= 2
model.addRange(x + y, 1.0, 2.0, "range0")
```

**Comment by leethargo** [comment]
We should really improve the error message in the `TypeError` that we throw in `ExprCons.__nonzero__(self)`

**Comment by leethargo** [comment]
There was a suggestion to use keyword arguments for adding ranged constraints, because the current syntax (`lhs <= (expr <= rhs)`) is really confusing.

I agree that the syntax is ugly, but I would like to have only way of setting the type of constraint. Adding optional keyword arguments `lhs` and `rhs` to `Model.addCons` would lead to ambiguous code like `m.addCons(x + y <= 3, rhs=2)`.

@mattmilten: Should we then follow Gurobi and allow only one-sided inequalities and equations for `addCons` but use a separate method for ranged constraints (linear and nonlinear)?

**Comment by mattmilten** [comment]
Hmm, I'm not sure which solution is nicer or more straightforward. I prefer the current set using only one method.
