### ISSUE TITLE
Missing Contributing guidelines

### ISSUE THREAD

**Issue by ramabile** [SCIP-Interfaces/PySCIPOpt#170]
Dear SCIP workers,
Among the several pro's to write down a CONTRIBUTING/CONTRIBUTING.md file, it can improve the awareness of contributors.  
For instance, I overlooked there is a continuous integration and the pull requests must comply with python3.

**Comment by mattmilten** [comment]
You are absolutely right! This is lacking and we will add a CONTRIBUTING shortly.
