### ISSUE TITLE
MinIISC / how do I check for model errors?

### ISSUE THREAD

**Issue by ziv121** [SCIP-Interfaces/PySCIPOpt#172]
say I entered two constraints(among others) that contrast each other.
I would expect some kinda a model error/exception, but it just gives me partial results instead.
I do not expect the model to deal with it, I just want a way to track it down somehow - in sense of awareness that I entered bad conditions.
how can it be done? 
thank you

**Comment by mattmilten** [comment]
Maybe I don't understand your question correctly. It's not possible to check feasibility of the model during creation - this would be way to expensive.

What do you mean by "partial results"? Shouldn't the model become infeasible when you add conflicting constraints?

Maybe you could share a minimal example to demonstrate the issue?

**Comment by ziv121** [comment]
thank you for the fast reply.

I'm not sure I can provide a minimal result as I'd have to synthesize it from 0..
in general, I'm just confused with how the model handled my contrast conditions.

my solution is in a form of binary matrix.
I have a condition which says that for each row, sum(row)<=1. 
now, because this is a maximization problem I usually have 1s in almost every row(99.9%) except for some exceptions(legitimate ones)

now, I have manually added 2 conditions - in a specific row, I demand two cells to have value of 1.
obviously, that should cause a logic failure and the problem cannot be solved.

now, instead of getting no results at all or some exception - I do not get notified but only get partial results - means maybe 30% of the rows have 1s. my guess is it started filling the matrix until it to to the row where the contradict conditions are, and simply stopped.

now my question is, how do I get notified when that kinda stuff happened? I don't wanna count on the user to supply validate conditions, I wanna make sure myself.

thank you very much, again.

**Comment by ramabile** [comment]
For completeness, this works:
```
from pyscipopt import Model

m = Model()

### "None" means -infinity as lb
x = m.addVar("x","I", None) #relative integer variable
n = m.addVar("n","I", None) #relative integer variable
s = m.addVar("s","B")

m.addCons(x==-101)  #negative integer

m.addCons(s == x-2*n)
m.setObjective(s)
m.optimize()

assert m.getStatus() == "optimal"
for v in m.getVars(): print("%s %d" % (v,m.getVal(v)))

print("%d%%2 == %d?" % (m.getVal(x), m.getVal(s)))
print(m.getVal(s) == m.getVal(x)%2)
assert m.getVal(s) == m.getVal(x)%2
```

**Comment by mattmilten** [comment]
There is an application in SCIP, called MinIISC, that can tell you why a model is infeasible: http://scip.zib.de/doc/applications/MinIISC/

This cannot be called from PySCIPOpt, though, instead you could write out the model and put it into the compiled C application.

**Comment by ramabile** [comment]
MinIISC is extremely interesting, thanks for the tip!
What do you mean with "cannot be called from PySCIPOpt"? Is it just a matter of missing implementation or is there any design choice it breaks so PySCIPOpt trying to implement MinIISC?

**Comment by mattmilten** [comment]
MinIISC is an application within SCIP, i.e., it is not contained in the SCIP library and cannot be called via the API. Only a binary is created when compiling the code. IMO this deserves to be a proper feature integrated into SCIP and I'll try to persuade someone to move the code there :-)

**Comment by fserra** [comment]
i am just going to close this as nothing will happen in the future that i can see
