### ISSUE TITLE
Error message with resolves

### ISSUE THREAD

**Issue by loehndorf** [SCIP-Interfaces/PySCIPOpt#175]
Thanks for making this very nice Python interface for SCIP!

I ran into a problem when reoptimizing. I took the example from the readme, but I am interested in changing problem data and then resolving. I run:
```model = Model("Example")
x = model.addVar("x")
y = model.addVar("y", vtype="INTEGER")
obj = model.setObjective(x + y)
ctr = model.addCons(2*x - y*y >= 1)
model.optimize()
model.freeReoptSolve()
obj = model.setObjective(x + y)
```
The error message:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-11-e014e8325907> in <module>()
      6 model.optimize()
      7 model.freeReoptSolve()
----> 8 obj = model.setObjective(x + y)
      9 model.optimize()

src/pyscipopt/scip.pyx in pyscipopt.scip.Model.setObjective()

src/pyscipopt/scip.pyx in pyscipopt.scip.PY_SCIP_CALL()

Exception: SCIP: error in input data!
```
What am I doing wrong here? Error in input data seems absurd, as I use the same objective as before.

**Comment by loehndorf** [comment]
The same happens when I change the RHS of a constraint (this time without calling freeReoptSolve)

```
model = Model("Example")
x = model.addVar("x")
y = model.addVar("y", vtype="INTEGER")
obj = model.setObjective(x + y)
ctr = model.addCons(2*x - y*y >= 1)
model.optimize()
model.chgRhs(ctr, 2.0)
```
The error message:
```
--------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
src/pyscipopt/scip.pyx in pyscipopt.scip.PY_SCIP_CALL()

Exception: SCIP: method cannot be called at this time in solution process!
Exception ignored in: 'pyscipopt.scip.Model.__dealloc__'
Traceback (most recent call last):
  File "src/pyscipopt/scip.pyx", line 206, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: method cannot be called at this time in solution process!
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-e80bedbd7879> in <module>()
      5 ctr = model.addCons(2*x - y*y >= 1)
      6 model.optimize()
----> 7 model.chgRhs(ctr, 2.0)

src/pyscipopt/scip.pyx in pyscipopt.scip.Model.chgRhs()

src/pyscipopt/scip.pyx in pyscipopt.scip.PY_SCIP_CALL()

Exception: SCIP: error in input data!
```

**Comment by fserra** [comment]
Hi. The problem is that SCIP has stages and you can only do certain things in certain stages. For instance, you can change the model while you are creating it, but not when you are solving it.

You have to call `model.freeTransform()`

**Comment by yghbpr** [comment]
Hi. Although I have used "model.freeTransform()" before changing my model, I have the same problem.
Actually, for several times it works correctly but after a while it seems that lack of memory makes it unable to deallocate some variables. I have pasted my errors here. Is there anyone to help me?

[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:128] ERROR: Insufficient memory for reallocation of 900784 bytes.
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:128] ERROR: No memory in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:900] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:1430] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:1588] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\cons.c:6754] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\prob.c:1323] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\prob.c:576] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:452] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:2440] ERROR: Error <-1> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:2660] ERROR: Error <-1> in function call
Traceback (most recent call last):
  File "C:/Users/asus/PycharmProjects/MAsterModelSCIP/toTest.py", line 1442, in <module>
    main1(models,ListOfSFCs[q],sfcNodeReq[q],q)
  File "C:/Users/asus/PycharmProjects/MAsterModelSCIP/toTest.py", line 1266, in main1
    models[q][mdlcntr].optimize()
  File "src\pyscipopt\scip.pyx", line 2083, in pyscipopt.scip.Model.optimize
  File "src\pyscipopt\scip.pyx", line 193, in pyscipopt.scip.PY_SCIP_CALL
MemoryError: SCIP: insufficient memory error!
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:3413] ERROR: invalid SCIP stage <2>
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_prob.c:763] ERROR: Error <-8> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_general.c:381] ERROR: Error <-8> in function call
Traceback (most recent call last):
  File "src\pyscipopt\scip.pyx", line 207, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: method cannot be called at this time in solution process!
Exception Exception: Exception('SCIP: method cannot be called at this time in solution process!',) in 'pyscipopt.scip.Model.__dealloc__' ignored
WARNING: Transformed variable <t_B_Nprim_R_I_T[3,0,1,4]> not released when freeing SCIP. Consider releasing variable first.
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\var.c:6966] ERROR: cannot change the bounds of a fixed variable
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\var.c:6943] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\var.c:8948] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\prob.c:624] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:2130] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_solve.c:3408] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_prob.c:763] ERROR: Error <-9> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.0\scip\src\scip\scip_general.c:381] ERROR: Error <-9> in function call
Traceback (most recent call last):
  File "src\pyscipopt\scip.pyx", line 210, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: error in input data!
Exception Exception: Exception('SCIP: error in input data!',) in 'pyscipopt.scip.Model.__dealloc__' ignored

**Comment by fserra** [comment]
Can you please update to the latest version of scip and pyscipopt. If it still happens, can you please paste your code or build a smaller code that generates the error and paste it. How big is your model?
