### ISSUE TITLE
AssertionError messages

### ISSUE THREAD

**Issue by ramabile** [SCIP-Interfaces/PySCIPOpt#178]
Dear SCIP workers,
with the goal of a self-explaining interface, when an assertion error is raised it would be very helpful to get a meaningful assertion error. Not everyone goes through the code with a breezy attitude. :)

I am working to give an appropriate message to the ones I find and understand. I would like to keep this issue open to clarify some nasty `assert` statements.

I start with `scip.pyx` which I am more confident with. I list the assertions in increasing order of personal _understanding_:
- `assert op2idx[valuenode[0]] == SCIP_EXPR_CONST` in `_addGenNonlinearCons`;
- `assert len(node[1]) == 1` in `_addGenNonlinearCons`;
- `assert varpos == nvars` in `_addGenNonlinearCons`;
- `assert len(term) == 1` in `setObjective` and `chgReoptObjective`;
- `assert len(v) == 2, 'term: %s' % v` in `_addQuadCons`; (not that clear)
- `assert cons.isQuadratic()` in `getTermsQuadratic`. (yes, it's clear... which assertionError message?)

Out of curiosity: in `addConsIndicator` there are the following:
```
if cons.expr.degree() > 1:
    raise ValueError("expected linear inequality, expression has degree %d" % cons.expr.degree())

assert cons.expr.degree() <= 1
```
Is that intended? Is the check so detrimental that, in case of optimization (_e.g._ `-O` flag) the check should be included? Or is that just an involuntary redundancy?

**Comment by ramabile** [comment]
Closed by https://github.com/SCIP-Interfaces/PySCIPOpt/commit/453482a1752d87fe4b21276eb2ab3ef388526a5b

**Comment by mattmilten** [comment]
Cool, thanks!
