### ISSUE TITLE
Update interface for SCIP 6.0.0

### ISSUE THREAD

**Issue by mattmilten** [SCIP-Interfaces/PySCIPOpt#179]
There are a bunch of failing tests with the current release candidate. See branch [sm/build-with-scip6.0](https://github.com/SCIP-Interfaces/PySCIPOpt/tree/sm/build-with-scip6.0)

**Comment by mattmilten** [comment]
@fserra @stephenjmaher

**Comment by mattmilten** [comment]
Yes, please. There was some confusion with all those branches and I'm afraid there might have been some duplicate work. Sorry about that.

**Comment by stephenjmaher** [comment]
No problem. I created the `pre6.0` branch to contain all of the work for the release. I will delete `pre6.0` now.

**Comment by stephenjmaher** [comment]
I don't know how to understand the errors in the CI tests. Could either of you tell me what the issue is with `SCIP_BENDERS`?

**Comment by mattmilten** [comment]
I simply didn't bother to setup appveyor (the Windows builds) for SCIP 6.0. So we're trying the test the 6.0 PySCIPOpt with 5.0.1 SCIP and this cannot work. I claim, that it's safe to ignore as long as the travis builds are working fine. We will properly test the Windows version as soon as the SCIP 6.0 package is released.
