### ISSUE TITLE
Integer vtypes and close-to-integer float values 

### ISSUE THREAD

**Issue by ramabile** [SCIP-Interfaces/PySCIPOpt#185]
Dear SCIP workers,
I kindly appeal to your own experience.

I frequently use binary/integer variables. When I return their values for an optimal solution, it could occasionally happen I get floats very close to the unity. I can fix the problem rounding the value when needed. Still, I wonder where the problem could raise.
96 binary variables and 286 original constraints of the type: `quicksum(vars) == N` or `quicksum(vars) >= 1` or `quicksum(vars) <= N - 1`. 2 variables has value `0.9999999999999998` and two has value `2.220446049250313e-16`. I am aware in this case the values are actually integers up to the double precision unit roundoff.
I ask if it is an expected behaviour of SCIP/PySCIPOpt or it is just my loose implementation. Is there any caveat I am missing here?

Thanks!

**Comment by fserra** [comment]
This is expected behavior. SCIP checks with tolerances, even the integrality constraints so one should expect to see such numbers from time to time.

**Comment by ramabile** [comment]
Ok so for consistency I will not change PySCIPOpt to return an integer if vtype is binary/integer.
(just as idea: this design principle could be written in the `CONTRIBUTING.rst` so that expected behaviours of SCIP and PySCIPOpt do not differ)
