### ISSUE TITLE
PySCIPOpt MIP Model outputs an LP file that cannot be solved by SCIP

### ISSUE THREAD

**Issue by wesleycmtsang** [SCIP-Interfaces/PySCIPOpt#188]
Hi Developers,

So I've recently built an MIP model with PySCIPOpt. SCIP_TestUseCase1.py calls SCIP_Blending_Model.py's blending_model function with some given parameters to find an optimal solution to the constructed problem.

[SCIP_test1.zip](https://github.com/SCIP-Interfaces/PySCIPOpt/files/2143765/SCIP_test1.zip)

The model does give an optimal solution when the SCIP_TestUseCase1.py is run. (It is not the optimal solution though. I will submit a separate issue with regards to that.)

However, when I write the problem to an LP (SCIP_test1.lp) file and feed that directly into SCIP, it says the model is infeasible or unbounded.

One thing to note is that the objective function is a quicksum function. (Check out Lines 168-170 of SCIP_Blending_Model.py), thus I needed to create a single variable (objvar) to hold the objective function.

Thank you! Keep up the great work!

Regards,
Wesley

**Comment by mattmilten** [comment]
The last constraint seems to be nonlinear:

```
blending_model.addCons(objvar <= quicksum((sum(dailyUsedTonnages.values())*percentRecoveries[curr]*(100.0-moistures[curr])*(stockpile1Prices[curr] - opexPT - shippingCost) + (sumPremiums[curr]-sumPenalties[curr])*percentRecoveries[curr]*(100.0-moistures[curr]))/10000.0 for curr in range(1,numPlantProducts+1)))
```

This results in a somewhat broken `.mps` or `.lp` file that cannot be read correctly. If you SCIP's own `.cip` format, SCIP can solve the file exactly the same way as PySCIPOpt.
