### ISSUE TITLE
How to limit the runtime?

### ISSUE THREAD

**Issue by LingxiaoShawn** [SCIP-Interfaces/PySCIPOpt#197]
I have a problem that's extremely nonlinear and seems that the optimization progress won't stop, so I wander is there anyway to set the time limitation for the solver?

**Comment by fserra** [comment]
Sure, just use `scip.setRealParam('limits/time', 100)` where `scip` is a `Model()`. You can, of course, change the 100 for whatever number you want. Good luck

**Comment by LingxiaoShawn** [comment]
Thank you!

**Comment by LidiiaS** [comment]
@LingxiaoShawn  Hello,

 Thank you very much for your advice. I was looking for time limitation solution in pyscipopt as well. 

When I write "Model().setRealParam('limits/time', 100)" after importing Model from pyscipopt and before defining the model, etc – it does nothing (the code is running longer that 100 seconds), but it does not produce any error. Am  I doing something wrong? Please, help. 

Thanks! 

Best,
Lidiia

**Comment by LidiiaS** [comment]
Hello @fserra,
I've also found this on stackoverflow: 

m = pyscipopt.Model()
m.setParam('limits/time', 600)

But this returns error "name 'pyscipopt' is not defined"..   I see some similarities between your solution and this one but should it be setParam or setRealParam, or there is no difference? 

Here is the beginning of my code (just in case):

from pyscipopt import Model, quicksum, multidict, SCIP_PARAMSETTING
import pdb
from random import random
from random import randint 
import random
import time, sys
from time import perf_counter

mm = pyscipopt.Model()
mm.setParam('limits/time', 60)


 #create non-linear problem

def nonlinear(K, I, J, demand, alpha, Lambda, IQ, Inv, c, cQ, w, P, PQ, S, SQ, 
        mu, muQ, z, sigma, L, beta):
  
    
    model = Model("Nonlinear")
    X, XQ, Z, ZQ, U, Y, SS, new, xi, IPT1, IPT2, ro, roQ, f, Aux1, Aux2, binary1, binary2, STFfromFC, IPT1FC, IPTMFC, STFfromstore, ITP1store, ITPMstore = {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}

    for i in range (1, I+1):
        for j in range (1, J+1):

**Comment by LidiiaS** [comment]
@mattmilten Hello, 

I am sorry to disturb you, I've seen your answer to a similar question. 

Could you please help with setting a time limit in pyscipopt?  The following does not work:

m = pyscipopt.Model()
m.setParam('limits/time', 600). 

:(

Thank you very much in advance!

Kind regards,
Lidiia
