### ISSUE TITLE
Min of variables in PySCIPOpt

### ISSUE THREAD

**Issue by yghbpr** [SCIP-Interfaces/PySCIPOpt#198]
I have a "min" function in one of the constraints of my model. It should calculate the minimum of a parameter and a decision variable, which is not possible in the version that I' m using. Would you please help me how to handle it? Is there any newer version which can manage the problem?

**Comment by fserra** [comment]
Hi

you can always write min(a,b) as (a + b)/2 - abs(a -b)/2 and the absolute value is supported in PySCIPOpt.

Can you write exactly how your constraint looks like? Maybe there is a way of removing the min

**Comment by ramabile** [comment]
Following @fserra, you need an auxiliary variable `c` which represents the minimum between the variable `a` and `b` in your model `m`:
```m.addCons(c == ((a+b)/2 - abs(a-b)/2)```
Same holds for the maximum, changing the sign before `abs`:
```m.addCons(c == ((a+b)/2 + abs(a-b)/2)```

I could consider to implement `min` and `max` this way if they are native SCIP features too. Is that OK for the maintainers?

**Comment by mattmilten** [comment]
I like the idea of having dedicated binary operators for `min` and `max`. This might be helpful to write accessible/readable code.

**Comment by fserra** [comment]
mmm if we were to do this, then we would have to preprocess this min function. In many cases, you can probably just remove it, but SCIP will not do it and that would be very bad. So, unless SCIP implements the min operator, I wouldn't add it at the pyscipopt level

**Comment by ramabile** [comment]
@fserra is a legit point. Still, I would find beneficial to add min/max constraints as basic examples for newcomers.
Full disclosure: I overlooked PySCIPOpt supports absolute value!

**Comment by mattmilten** [comment]
We really need a proper documentation that lists stuff like this (#190 )

**Comment by ryanjoneil** [comment]
> @fserra is a legit point. Still, I would find beneficial to add min/max constraints as basic examples for newcomers. Full disclosure: I overlooked PySCIPOpt supports absolute value!

Same - I found out through this issue. Is there somewhere else to look?
