### ISSUE TITLE
clean up examples

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/PySCIPOpt#2]
Which of the examples actually work with PySCIPOpt? Should they be turned into automated tests?
Delete all the other files.

**Comment by fserra** [comment]
Yeah, why do we have/need the gurobi examples??

**Comment by mattmilten** [comment]
I removed the gurobi examples and moved the remaining to directory `unfinished`.

I still need to clean up this directory. We should keep some of the examples. They are mostly about modeling and wouldn't work well as tests.

**Comment by mattmilten** [comment]
Working examples are now in the `finished` subdirectory.

**Comment by mattmilten** [comment]
Whall we close this issue? Or do we need to imporve the examples further (documentation, etc.)?

**Comment by leethargo** [comment]
I'm fine with closing. Or we remove the `unfinished` dir.
