### ISSUE TITLE
I have a problem of installation

### ISSUE THREAD

**Issue by jazminyolotzin** [SCIP-Interfaces/PySCIPOpt#200]
hello, I have already install scip in my computer, I installed it used cmake, I CAN'T RUN PySCIPOpt, is a direct problem of the script setup.py , it doesn't pass some parameters to the Cś compiler,I don't know wich is the problem

**Comment by mattmilten** [comment]
Please share the commands you executed as well as the corresponding output, so we can understand what went wrong.

**Comment by mattmilten** [comment]
I am closing this, because discussion continues in #201
