### ISSUE TITLE
RE TO SCIP-INTERFACE 

### ISSUE THREAD

**Issue by jazminyolotzin** [SCIP-Interfaces/PySCIPOpt#201]
I have installed the SCIP library using cmake and I can executed using simply "scip" from terminal, as far I understand the library is installed and has the proper  enviroment variables set. 
When I run 
`pip install pyscipopt` 
a large list of errors appear , I have trace back the error to this: 
`src/pyscipopt/scip.c:2327:70: error: unknown type name ‘SCIP_BENDERSENFOTYPE’; did you mean ‘SCIP_LINEARCONSTYPE’?
     static CYTHON_INLINE PyObject* __Pyx_PyInt_From_SCIP_BENDERSENFOTYPE(SCIP_BENDERSENFOTYPE value);`

My belived is that some parameter is not properly set on the python script setup.py.  I have tried to installed on a different maching using pip and the sorce code,  and came up with the same result for any of the installations.

**Comment by fserra** [comment]
Hi

you do not have to create a new issue every time you reply, you can reply in the issues' thread.
You have to set the environment variable yourself, it is not set automatically.
Also, are you sure you are pointing/installed scip version 6 ?

**Comment by jazminyolotzin** [comment]
You were right, I was trying to installed using the 5 version instead of 6. My apologies for your time spent.
have a good day!!!
