### ISSUE TITLE
API to submit the whole problem currently in memory, intead of saving to file?

### ISSUE THREAD

**Issue by fvcaputo** [SCIP-Interfaces/PySCIPOpt#205]
I'm sorry if this is already explained somewhere in the documentation, I have looked for it and also read the source code but couldn't find the answer.

I know `Model` has a method `readProblem` which can read the problem described in a file. I'm wondering if there is a similar API that allows me to just pass the problem if I have it in memory?

My use case is that I have the whole problem as a string variable. What I can do is save this whole variable in a file and have SCIP read it to solve it. Is there any API that allows me to cut the middle man and just pass this variable to the solver?

Thank you.

**Comment by fserra** [comment]
I don't think this is possible

**Comment by fvcaputo** [comment]
@fserra Ah I see. I thought maybe the way the solver reads the file might have something to do with it (probably optimized in some ways), but was wondering about it anyways. Thanks.

**Comment by fserra** [comment]
SCIP doesn't have such a function in its API, as far as I know, probably because nobody has needed such a function so far.
