### ISSUE TITLE
Creating multiple child nodes in Branchrule

### ISSUE THREAD

**Issue by gokhanceyhan** [SCIP-Interfaces/PySCIPOpt#225]
Hi,
I am trying to implement my own branching rule to solve an MILP problem.

As far as I understand, I can create multiple child nodes by using model.createChild() inside the branchexeclp() function by inheriting Branchrule class. However, I need to give a node selection priority and an estimate for the objective value of the best feasible solution contained in the subtree after applying the branching to the createChild() method. C API documentation tells that one might use the methods SCIPcalcNodeselPriority() and the method SCIPcalcChildEstimate() to obtain those values. However, Python API for those function are not available, is it?

My question is whether there is any plan to create Python APIs for those functions in the near future? Or, how can i add the corresponding wrapper functions myself?

 I would appreciate your help.

Thanks and regards,

Gokhan

**Comment by mattmilten** [comment]
Hey Gokhan,

thank you for this nicely written question/request/issue.
I started writing about how you would need to add these two methods but quickly stopped and just did it myself :-)

Please check out and test the new methods in #226

**Comment by gokhanceyhan** [comment]
Thank you Matthias. I appreciate your very quick response and getting the job done. Should I clone the repository to have these features? Or, can I expect a release in the near future?

**Comment by mattmilten** [comment]
We just pushed the new version 2.1.0 to PyPI, including the additions.

**Comment by gokhanceyhan** [comment]
Great, thanks a lot.
