### ISSUE TITLE
Solving fixed MILP and getting the optimal dual values

### ISSUE THREAD

**Issue by gokhanceyhan** [SCIP-Interfaces/PySCIPOpt#228]
Hi,

I need to get the optimal value of a dual variable corresponding to a linear constraint in my MILP problem. To do that, I apply the following steps:

1) Solve MILP
2) Apply freeTransform()
3) Fix the integer variables to their optimal values
4) Change the types of those integer variables to continuous
5) Turnoff presolve and heuristics, disable propagation
6) Solve LP
7) Use getDualsolLinear() function to get the dual values

The situation is that, sometimes I am able to get the dual values correctly, but sometimes they appear as minus infinity (-1e+99). I suspect that the problem occurs when the solver hits the time limit while solving MILP. What could be the problem here? And, is there a shortcut to solve fixed MILPs like in CPLEX or Gurobi?

Thanks and regards,

Gokhan

**Comment by gokhanceyhan** [comment]
**I share below the method where I want to solve the fixed MILP problem:**    
```
    def solve_fixed_model(self):
        # get the values of the block bid variables
        bbid_id_2_val = {
            bid_id: self.model.getVal(bbidvar) for bid_id, bbidvar in self.bid_id_2_bbidvar.items()}
        self.fixed = self.model
        self.fixed.freeTransform()
        # convert the problem into fixed MILP
        for bid_id, var in self.bid_id_2_bbidvar.items():
            value = bbid_id_2_val[bid_id]
            if abs(value - 0.0) <= self.fixed.getParam('numerics/feastol'):
                self.fixed.chgVarUb(var, 0.0)
            else:
                self.fixed.chgVarLb(var, 1.0)
            self.fixed.chgVarType(var, 'C')
        self.fixed.setPresolve(scip.SCIP_PARAMSETTING.OFF)
        self.fixed.setHeuristics(scip.SCIP_PARAMSETTING.OFF)
        self.fixed.disablePropagation()
        self.fixed.optimize()
```

**Then, I query the dual values as follows in the following method:**
```
    def _get_best_solution(self):
        model = self.master_problem.fixed
        # fill dam solution object
        dam_soln = ds.DamSolution()
        dam_soln.total_surplus = model.getObjVal()
        for bid_id, var in model.data.bid_id_2_bbidvar.items():
            value = model.getVal(var)
            if abs(value - 0.0) <= model.getParam('numerics/feastol'):
                dam_soln.rejected_block_bids.append(bid_id)
            else:
                dam_soln.accepted_block_bids.append(bid_id)
        market_clearing_prices = []
        for con in self.master_problem.period_2_balance_con.values():
            mcp = model.getDualsolLinear(con)
            market_clearing_prices.append(mcp)
        dam_soln.market_clearing_prices = market_clearing_prices
        return dam_soln
```

Thanks for your time.

**Comment by mattmilten** [comment]
Haha, "`fill dam(n) solution object`"...

Seriously, I guess I have an idea what is going wrong: You don't optimize again and since the dual values are taken directly from the LP solver, it has no chance of filling those values. That's why you end up with weird numbers. As I said above, dual values are a bit tricky in SCIP since it is not a MIP solver at heart.

**Comment by gokhanceyhan** [comment]
:) Nice catch,

But at the end of ```solve_fixed_model```, I solve an LP model. Why do I need to optimize again?

**Comment by mattmilten** [comment]
`1e+99` is `SCIP_INVALID`. This value will be returned as dual value only when you query the dual multiplier of a nonlinear constraint. Are you sure that there are no nonlinear constraints in your model and that there is no warning printed by PySCIPOpt? Usually, we check whether a constraint is linear before passing the dual solution.

Do you maybe have a minimal working example - including the data?

**Comment by fserra** [comment]
close due to inactivity
