### ISSUE TITLE
How to use Scip Parallel solve using Pyscipopt Model

### ISSUE THREAD

**Issue by LordSycho** [SCIP-Interfaces/PySCIPOpt#229]
So, I have a CMIP that i am trying to solve using Pyscipopt( + I have installed SCIP Opt suite version 6). And as it is taking long and only using one core. I wanted to know is there a way that i can use Multiple cores using pyscipopt. As of now when i run it eats up 16gb ram but uses only one core. 

I tried to search for it and came to an understanding that it needs to be enabled while compiling the make file using TPI=tny and then a concurrent solve can be started by using the concurrentopt command instead of the optimize command in the SCIP shell

but when i try to replace optimize i get this error : 
AttributeError: 'pyscipopt.scip.Model' object has no attribute 'concurrentopt'

If it is possible please help me here. Or provide me some clarity over this. (Gurobi and IBM Cplex have these parallel mode functionality.)

**Comment by LordSycho** [comment]
Hi,
Thanks for the above changes it makes pyscipopt try to run solveConcurrent but it at the end fails stating: 
"SCIP was compiled without task processing interface. Parallel solve not possible"

I am using windows installer any idea how to enable parallel solve on windows. 

As windows installer while installing doesn't provide any options at the time of installing to enable parallel mode.

**Comment by mattmilten** [comment]
Interesting, we'll see what we can do about this and try to include the parallel mode in the Windows installer.

**Comment by LordSycho** [comment]
Hi @mattmilten I am trying to optimize a MICP problem using scip. I observed 
1 . That scip 6 takes too long like more then an hour and still couldnt reach to optimal solution where 
     scip 5 was able to come with an optimal sol in 250 secs. 
2.  Scip 6 has some issues while installing on ubuntu with TPI=tny it raises issues with pthread. where 5 
     just gets installed with out any prob. 
3.  The issue that i am concerned about as of now : as i have started using scip 5: their is some problem 
     with DLL when running with pyscipopt.  I added the path and all but its not working. Do i need to 
     mention scip version in pyscipopt ?
****Thanks Please look in to 3rd And help asap.****

**Comment by mattmilten** [comment]
Probably you need to clean up your system to avoid that PySCIPOpt links to the wrong SCIP library. I don't even understand whether you're using Windows or Linux right now.

Please understand that we are not some kind of support staff.

**Comment by ravir252** [comment]
It had tried with fresh ubuntu 16.04 but it is not working

**Comment by mattmilten** [comment]
Please follow the instructions **precisely**.

**Comment by tiantanshu** [comment]
> Hey. I guess one just needs to extend the interface to support concurrentopt
> 
> here is a diff
> 
> ```diff
> diff --git a/src/pyscipopt/scip.pxd b/src/pyscipopt/scip.pxd
> index 95dc673..4d88f27 100755
> --- a/src/pyscipopt/scip.pxd
> +++ b/src/pyscipopt/scip.pxd
> @@ -551,6 +551,7 @@ cdef extern from "scip/scip.h":
>      SCIP_RETCODE SCIPsolve(SCIP* scip)
>      SCIP_RETCODE SCIPfreeTransform(SCIP* scip)
>      SCIP_RETCODE SCIPpresolve(SCIP* scip)
> +    SCIP_RETCODE SCIPsolveConcurrent(SCIP* scip)
>  
>      # Node Methods
>      SCIP_NODE* SCIPgetCurrentNode(SCIP* scip)
> diff --git a/src/pyscipopt/scip.pyx b/src/pyscipopt/scip.pyx
> index cb7d25b..3086876 100755
> --- a/src/pyscipopt/scip.pyx
> +++ b/src/pyscipopt/scip.pyx
> @@ -2309,6 +2309,12 @@ cdef class Model:
>          PY_SCIP_CALL(SCIPsolve(self._scip))
>          self._bestSol = Solution.create(SCIPgetBestSol(self._scip))
>  
> +    def solveConcurrent(self):
> +        """Transforms, presolves, and solves problem using additional solvers which emphasize on
> +           finding solutions."""
> +        PY_SCIP_CALL(SCIPsolveConcurrent(self._scip))
> +        self._bestSol = Solution.create(SCIPgetBestSol(self._scip))
> +
>      def presolve(self):
>          """Presolve the problem."""
>          PY_SCIP_CALL(SCIPpresolve(self._scip))
> ```

Thanks for your code, but I don't work it on Centos7. I follow your step that change the scip.pxd file and the scip.pyx file. Then I run `python setup.py install` to setup pyscipopt module. When I run `model.solveConcurrent()` the system raise error which is 

> AttributeError: type object 'pyscipopt.scip.Model' has no attribute 'solveConcurrent'

BTW, I have installed SCIP with using `make TPI=tny`

**Comment by fserra** [comment]
it seems that the python setup.py install didn't go through or maybe you have more than one pyscipopt installed and your python is using a different one??
