### ISSUE TITLE
Dual variables not accessible

### ISSUE THREAD

**Issue by joaopedroso** [SCIP-Interfaces/PySCIPOpt#23]
The dual solution does not seem to be accessible; e.g., for a constraint c[i]
    model.getDualsolLinear(c[i]) 
seems to always return 0.

**Comment by mattmilten** [comment]
This method only returns the dual solution if the solved problem is a pure LP and presolving was disabled. This is required because the dual information is coming only from the LP solver so we need to be sure that the internal LP is identical to the SCIP problem.

**Comment by joaopedroso** [comment]
The problem subsists even with presolving disabled; e.g, in the model attached.
[lo_wines_scip.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/374041/lo_wines_scip.txt)

**Comment by mattmilten** [comment]
This is fixed in 9c0a775. The original constraints were not transformed and SCIP only accepts transformed constraints here.

**Comment by joaopedroso** [comment]
Some problems seem to be standing; running the attached model segfaults...

[tmp.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/376404/tmp.txt)

**Comment by Viech** [comment]
I'm also having issues with LP duals even with presolve disabled. Some constraints yield the correct duals, other constraints _in the same problem and during the same optimization pass_ throw `no dual solution available for constraint` warnings. Setting the affected dual values to `0.0` is not correct; some of the affected constraints are supposed to have non-zero duals.

Unfortunately my example where some duals of tight constraints are returned while some are not is too involved for a bug report. However, here is an example with a single constraint where retrieving its dual fails even though the constraint is tight (and its dual value should be `1.0`):

```
import pyscipopt
m = pyscipopt.Model()
x = m.addVar("x")
c = m.addCons(x >= 1)
m.setObjective(x, "minimize")
m.setPresolve(pyscipopt.scip.PY_SCIP_PARAMSETTING.OFF)
m.optimize()
m.getDualsolLinear(c)
```
Output:
```
Traceback (most recent call last):
  File "src/pyscipopt/scip.pyx", line 1276, in pyscipopt.scip.Model.getDualsolLinear
  File "src/pyscipopt/scip.pyx", line 1228, in pyscipopt.scip.Model.getTransformedCons
  File "src/pyscipopt/scip.pyx", line 283, in pyscipopt.scip.Constraint.create
Warning: cannot create Constraint with SCIP_CONS* == NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyscipopt/scip.pyx", line 1292, in pyscipopt.scip.Model.getDualsolLinear
Warning: no dual solution available for constraint c1
```
