### ISSUE TITLE
SCIP 6.0.1 build error

### ISSUE THREAD

**Issue by roessig** [SCIP-Interfaces/PySCIPOpt#232]
I just tried to build PySCIPopt for the new SCIP 6.0.1 release. Unfortunately, the following error occurs, maybe you know how to fix it:

In file included from /home/ansgar/meg/Vorlesungen/thesis/verify/PySCIPOpt/include/scip/scip.h:35,
                 from src/pyscipopt/scip.c:610:
/home/ansgar/meg/Vorlesungen/thesis/verify/PySCIPOpt/include/scip/def.h:43:10: fatal error: scip/config.h: No such file or directory
 #include "scip/config.h"

**Comment by mattmilten** [comment]
How did you install SCIP? The config header should be either contained in the pre-built package or be generated automatically.

**Comment by roessig** [comment]
[ansgar@localhost opt]$ cmake .. -DLPS=cpx -DCPLEX_DIR=/home/ansgar/Programs/cplex/cplex
-- Build shared libraries: ON
-- Build type: Release
-- Found CPLEX: /home/ansgar/Programs/cplex/cplex/include/ilcplex  
-- Found BLISS: /usr/include  
-- Could NOT find ZIMPL (missing: ZIMPL_DIR)
-- Could NOT find IPOPT (missing: IPOPT_LIBRARIES) (Required is at least version "3.12.0")
-- Looking for FE_DOWNWARD
-- Looking for FE_DOWNWARD - found
-- Could NOT find CRITERION (missing: CRITERION_LIBRARY CRITERION_INCLUDE_DIR) 
-- Could NOT find CRITERION (missing: CRITERION_LIBRARY CRITERION_INCLUDE_DIR) 
-- The following OPTIONAL packages have been found:

 * ZLIB
 * Readline
 * GMP
 * BLISS

-- The following REQUIRED packages have been found:

 * CPLEX
 * SCIP

-- The following OPTIONAL packages have not been found:

 * ZIMPL
 * IPOPT (required version >= 3.12.0)
 * Criterion

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ansgar/Programs/scipoptsuite-6.0.1/scip/opt
[ansgar@localhost opt]$ make -j2


This is what I ran. make finished succesfully stating
] Linking CXX executable ../bin/scip
[100%] Linking CXX shared library ../lib/libscip.so
[100%] Built target scip
[100%] Built target libscip

**Comment by mattmilten** [comment]
OK, looks good so far. What do you mean by "softlinks to lib and include"? You can just set the environment variable `SCIPOPTDIR` when compiling PySCIPOpt to point to your installation. In any case, you need to install SCIP before linking to it. The new `config.h` depends on your configuration and is not located in the `src` directory, but the build directory. It will be copied to the `include` directory during the installation of SCIP, though.

**Comment by mattmilten** [comment]
To install to a custom directory:

```
cmake .. -DCMAKE_INSTALL_PREFIX=<your/custom/path>
make install
```

**Comment by roessig** [comment]
Great thanks, it works with make install. I never used install for SCIP 6.0.0 
Though, I tried to do
` SCIPOPTDIR=<path/to/scip_install_dir> `
and also
`export SCIPOPTDIR=<path/to/scip_install_dir> `
but in these cases I got 
```
src/pyscipopt/scip.c:589:10: fatal error: scip/scip.h: No such file or directory
 #include "scip/scip.h"
```
It works though, when I create the links for lib and include manually using ln -s

**Comment by mattmilten** [comment]
Strange, on Linux this usually works fine:

```
SCIPOPTDIR=<...> python setup.py install
```

Maybe, it's because you already have the lib and include links in the PySCIPOpt directory?

**Comment by mattmilten** [comment]
Strange, on Linux this usually works fine:
```
SCIPOPTDIR=<...> python setup.py install
```
Maybe, it's because you already have the lib and include links in the PySCIPOpt directory?
