### ISSUE TITLE
Example of how to use GCG from PySCIPOpt

### ISSUE THREAD

**Issue by boiro9** [SCIP-Interfaces/PySCIPOpt#235]
I want to solve a decomposable ILP problem using directly the branch and price framework of the solver GCG, without defining by myself plugins related to the algorithm (pricing or branchinh rules).  I would like to know if it is possible to do this within the PySCIPOpt interface, and what are the way to define the structure information of the problem. I have not found any example in the tests folder related to this.

Many thanks in advance!

**Comment by mattmilten** [comment]
Hmm, I suppose this could be realized by linking to the `libgcg` instead of the `libscip`. Have never tried that, though. You could just rename the lib accordingly and check whether you can call some gcg specific functions - or if it works at all...
