### ISSUE TITLE
pyscipopt: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by m-seydali** [SCIP-Interfaces/PySCIPOpt#236]
Hi,
I have already installed pyscipopt. However after running my code, I see the following error:
"ImportError: DLL load failed: The specified module could not be found."
What could be the reason?

**Comment by mattmilten** [comment]
Did you add `SCIPOPTDIR\bin` to your `PATH` as specified in [INSTALL.rst](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.rst)?

This is necessary for Windows to find the SCIP dll.

**Comment by m-seydali** [comment]
Hi,
I reinstalled the package again. This time I added "SCIPOPTDIR\bin" to my path. It worked.

Thank you very much.

Best Regards,
Mohammad
