### ISSUE TITLE
Problems on benders decomposition plugin

### ISSUE THREAD

**Issue by annkiki** [SCIP-Interfaces/PySCIPOpt#237]
Hello everybody, recently I am implementing a problem with both benders decomposition and column generation. To write in SCIP format, I implement the benders class and pricer class respectively, hoping to solve the problem using column generation first then call benders decomposition on several subproblems. However, when running prob.optimize(), I observe "pricerinit"->"benderssolvesub"->"bendersgetvar" were invoked sequentially. But no column generation was performed until the program ended. I suppose this is due to no variable mapping is found between master problem and subproblems (as master problem's variables are added during solving). My **questions** follows:

-  Is there a way to perform the two things at the same time? I try to adjust the pricer's priority but failed.

-  When I tested the bendersgetvar, I found the mappedvar I provided (using a dict from master problems variable to subproblem variables) failed with the following problem:

```
AttributeError: "'pyscipopt.scip.Variable' object has no attribute 'var'" in 'pyscipopt.scip.PyBendersGetvar' ignored
```
I guess maybe the interface function got something wrong? 

Hope somebody can help me with the following doubts, thanks in advance!

P.S. I implement the SCIPactivateBenders and SCIPaddBendersSubproble to make SCIP aware the subproblems.

**Comment by stephenjmaher** [comment]
It is great to see that you are using the Benders' decomposition framework. Unfortunately, using column generation with the Benders' decomposition framework has not been really tested. So we really need to think about what is happening on the SCIP side as well as with then Python interface.

It is difficult to know what is happening here without an example. Are you able to share some code to help us understand the issue?

**Comment by annkiki** [comment]
Ok, so I make a simplified code for my problem, after implementing the following SCIP interface python wrapper (add them to scip.pyx, in scipyadds.pyx) you can run to see what's going on for problem 2. For problem 1, just go to line25 in simpleExample.py to capitalize 2 c (i.e. 'c_%d' --> 'C_%d' ). So no variable in MP matches SP.
Thanks for your attention.
[pyscipopt_probs.tar.gz](https://github.com/SCIP-Interfaces/PySCIPOpt/files/2817692/pyscipopt_probs.tar.gz)

**Comment by annkiki** [comment]
@stephenjmaher Hi, Stephen. Any progress so far? Thank you! ;)

**Comment by stephenjmaher** [comment]
The first issue is not an issue at all. It appears that your print statements are being called in the order that they are supposed to.

The second issue is related to a limitation of the getVar function. The full functionality is not currently available. I have created a branch to work on this issue, which is [benders-plugin-bug](https://github.com/SCIP-Interfaces/PySCIPOpt/tree/benders-plugin-bug).

The issue that I have at the moment is passing the `mappedvar` back to SCIP in `PyBendersGetvar`. I don't know how to convert the python `Variable` object to `SCIP_VAR*` @mattmilten @fserra do either of you have an idea how to do this?

I also updated the example: [simpleExample.tar.gz](https://github.com/SCIP-Interfaces/PySCIPOpt/files/2828596/simpleExample.tar.gz). Previously, it was using Probing mode, but this would require the subproblem SCIP to be in the SOLVING stage. So I changed this to directly solving the SCIP instance and then freeing the transform of the problem.

**Comment by stephenjmaher** [comment]
I have made some changes to the Benders' decomposition plugin. These changes are on the [benders-plugin-bug](https://github.com/SCIP-Interfaces/PySCIPOpt/tree/benders-plugin-bug) branch. This should be merged into the master soon.

One thing that came up is that the parameter `benders/MPBenders/updateauxvarbound` needs to be set to `False`. This is a bug in SCIP, which will be fixed at the next release.

Some changes were made to the example. These are given in 
[simpleExample.tar.gz](https://github.com/SCIP-Interfaces/PySCIPOpt/files/2850912/simpleExample.tar.gz)
