### ISSUE TITLE
`SCIP_CALL` decorator

### ISSUE THREAD

**Issue by mattmilten** [SCIP-Interfaces/PySCIPOpt#24]
The `scipErrorHandler` decorator destroys our docstrings.

There are two ways around this:

1. using `functools.wraps` to preserve the docstring
2. use `PY_SCIP_CALL` explicitly instead of the decorator.

What do you think, @leethargo @fserra @xmunoz?

**Comment by fserra** [comment]
I've always been a big fan of PY_SCIP_CALL.

**Comment by leethargo** [comment]
I prefer the explicit call to `PY_SCIP_CALL`. First, the decorator solution is not as flexible (in some methods, more than one SCIP C-function is called). Furthermore, it's weird to look at the code of `Model.create` and wonder why there is a `return` statement.

**Comment by mattmilten** [comment]
Good! I'm going to update the code accordingly.
