### ISSUE TITLE
violation: right hand side is violated by 1e+20

### ISSUE THREAD

**Issue by hossiiii** [SCIP-Interfaces/PySCIPOpt#242]
Hi,

I am in trouble because unexpected values ​​are present

```
SCIP Status        : problem is solved [unbounded]
Solving Time (sec) : 0.00
Solving Nodes      : 1
Primal Bound       : +1.00000000000000e+20 (5 solutions)
Dual Bound         : +1.00000000000000e+20
Gap                : 0.00 %
  [nonlinear] <c1>: (<objvar> + (power((<x(1)> + (<x(2)> * 0.0819672) + (<x(3)>
* 0.0657895) + (<x(4)> * 0.10989) + (<x(5)> * 0.0657895) + (<x(6)> * 0.0657895))
, -1) * (<x(1)> + (<x(2)> * 12.2) + (<x(3)> * 15.2) + (<x(4)> * 9.1) + (<x(5)> *
 15.2) + (<x(6)> * 15.2)) * (-1))) <= 0;
violation: right hand side is violated by 1e+20
best solution is not feasible in original problem
Optimal value: 1e+20
```

The code is as follows

``` python
from pyscipopt import Model, quicksum, multidict

def mkp(I,J,v,b):

    model = Model("mkp")

    x = {}
    for j in J:
        x[j] = model.addVar(vtype="B", name="x(%s)"%j)
    
    objvar = model.addVar(name="objvar", vtype= "C", lb=None, ub=None)
    
    model.addCons(objvar <= 1/quicksum(1/b[j]*x[j] for j in J) * quicksum(b[j]*x[j] for j in J))

    model.setObjective(objvar, "maximize")
    model.data = x

    return model

def example():
    J,v = multidict({1:0.78239, 2:0.12470, 3:0.003737, 4:0.072672, 5:0.026466, 6:-0.009972})
    I,b = multidict({1:1, 2:12.2, 3:15.2, 4:9.1, 5:15.2, 6:15.2})
    return I,J,v,b

I,J,v,b = example()
model = mkp(I,J,v,b)
x = model.data
model.optimize()

print("Optimal value:", model.getObjVal())

EPS = 1.e-6

for i in x:
    v = x[i]
    if model.getVal(v) > EPS:
        print(v.name, "=", model.getVal(v))
```

How can I get the correct value?
~~I am sorry that the display of github is difficult to see due to inexperience.~~
Thanks and regards,

**Comment by mattmilten** [comment]
I formatted your code correctly. You need to use triple backticks to mark code blocks ("´´´"). I can reproduce the issue and will look into it.

**Comment by hossiiii** [comment]
Thank you very much for everything

**Comment by mattmilten** [comment]
We found the issue with your model: Since you are dividing by the sum of some binary variables, this denominator may become 0 (if all binaries are 0) and hence the constraint is undefined. An easy fix to get rid of this forbidden solution is to add the following constraint:

``` python
model.addCons(quicksum(x[j] for j in J) >= 1)
```

By the way, it seems that you are mixing up your `J` and `I` indices when constructing the model: You loop over `J` but access `b[I]`.

**Comment by mattmilten** [comment]
Another work around would be to add a small constant to the denominator to prevent it to become 0.

**Comment by hossiiii** [comment]
Thank you very much for analyzing the cause. It was very helpful. I tried moving it, I was surprised by the speed of the operation of "PySCIPOpt". It is a really wonderful module. Thank you very much in the future.
