### ISSUE TITLE
deepcopy Model object

### ISSUE THREAD

**Issue by Nobody12** [SCIP-Interfaces/PySCIPOpt#244]
Hi,

is there a way to deepcopy a Model object, e.g. to implement a primal heuristic based on a subMIP.

Best regards & thanks,
Markus

**Comment by mattmilten** [comment]
We need to add the copy functionality to construct a new Model instance that contains a copy of the original SCIP instance.

**Comment by mattmilten** [comment]
#246

**Comment by mattmilten** [comment]
Did you try the new code, @Nobody12?

**Comment by Nobody12** [comment]
I tried out the new code and it works as expected. 
Thanks a lot for the fast response and the adjustments!
