### ISSUE TITLE
Variable can not be evaluated

### ISSUE THREAD

**Issue by hossiiii** [SCIP-Interfaces/PySCIPOpt#247]
Thank you for helping

I am sorry for the rudimentary question

Can I evaluate variables before performing optimization?

I would like to do this kind of processing.

```
def add_num(arg):
	if(arg < 1):
		y = arg + 1
	return y

model.addCons(objvar <= add_num(quicksum(v[j]*x[j] for j in J)))

```

The full text of the code

```
from pyscipopt import Model, quicksum, multidict

def add_num(arg):
	if(arg < 1):
		y = arg + 1
	return y

def mkp(I,J,v,b):

	model = Model("mkp")
	model.hideOutput()

	# Create Variables
	x = {}
	for j in J:
		x[j] = model.addVar(vtype="B", name="x(%s)"%j)
	
	objvar = model.addVar(name="objvar", vtype= "C", lb=None, ub=None)
	
	# Create constraints
	model.addCons(objvar <= add_num(quicksum(v[j]*x[j] for j in J)))
	model.addCons(5 <= 1/quicksum(1/b[i]*x[i] for i in I))
	model.addCons(quicksum(x[j] for j in J) >= 1)
	# Objective
	model.setObjective(objvar, "maximize")
	model.data = x

	return model

def example():
	J,v = multidict({1:0.68669,2:0.9842,3:0.77353,4:0.55047,5:0.32054,6:0.39316})
	I,b = multidict({1:10.6,2:6.4,3:12.1,4:22.2,5:16.2,6:14.4})
	return I,J,v,b

I,J,v,b = example()
model = mkp(I,J,v,b)
x = model.data
model.optimize()

print("Optimal value:", model.getObjVal())

EPS = 1.e-6

for i in x:
	v = x[i]
	if model.getVal(v) > EPS:
		print(v.name, "=", model.getVal(v))
```

If it is an out of place question please delete it.

**Comment by mattmilten** [comment]
Maybe I don't understand the question not correctly. To me it does not make any sense to check variables before optimization because they are **variables**, i.e. they can take any value in their domain.

**Comment by hossiiii** [comment]
Thank you for your early response.

Because the variable, arg, is recognized as a character string in "add_num", conditional branching using the "if statement" was not possible.

-------------------------------------------------------------------------------------
Hope
arg = 0.xxxxx
In fact
arg = "v[1]*x[1]  + v[2]*x[2]  + v[3]*x[3]  + v[4]*x[4]  + v[5]*x[5]  + v[6]*x[6] "
-------------------------------------------------------------------------------------

I would like to make a conditional branch of an "if statement" with the value after assigning a numeric value to arg. Can I handle such a condition?

**Comment by mattmilten** [comment]
I think you are talking about indicator constraints:

https://github.com/SCIP-Interfaces/PySCIPOpt/blob/35775087653e6a920cb21683b7e2922141e8fb01/src/pyscipopt/scip.pyx#L1875

https://scip.zib.de/doc-6.0.1/html/group__CONSHDLRS.php#ga52f6038d998403a3f5f5ba3c154f0dfc

**Comment by hossiiii** [comment]
Thank you for telling me where to reference.
I saw the reference destination.
I'm sorry but I couldn't understand.
As a confirmation just to be sure, is it impossible to make a conditional branch of an "if statement" with the value after assigning a numeric value to arg?

**Comment by fserra** [comment]
Have a look at Chapter 9 of https://docs.mosek.com/MOSEKModelingCookbook-letter.pdf
In particular Section 9.1.3
