### ISSUE TITLE
Install python interface to SCIP on 64-bit Windows 10 with Python 3.7

### ISSUE THREAD

**Issue by eeliubin** [SCIP-Interfaces/PySCIPOpt#249]
Hi, I was trying to install PySCIPopt on 64-bit Windows 10 and Python 3.7 following the steps. However, there's an error making me unable to call SCIP. 
The downloaded pyscipopt  is stored at `D:\Python3plus\PySCIPOpt`

1. Download the latest SCIP Suite and install in in `D:\Scipopt`
2. Open CMD and run `set SCIPOPTDIR="D:\Scipopt"`
3. Run `set PATH=%PATH%;%SCIPOPTDIR%\bin`
4. Run `pip install pyscipopt` and the result is
```
Requirement already satisfied: pyscipopt in d:\python3plus\lib\site-packages (2.1.2)
```
5. Install `Cython`
6. Run `d:` and `cd D:\Python3plus\PySCIPOpt`
7. Run `python setup.py install`

All the installation process seems good. However, after installing `pytest`, I run `pytest`, errors occur as follows:

```
### ================================================= test session starts =================================================
platform win32 -- Python 3.7.2, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: D:\Python3plus\PySCIPOpt, inifile: setup.cfg
collected 0 items / 22 errors / 1 skipped

======================================================= ERRORS ========================================================
_______________________________________ ERROR collecting tests/test_benders.py ________________________________________
ImportError while importing test module 'D:\Python3plus\PySCIPOpt\tests\test_benders.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_benders.py:9: in <module>
    from pyscipopt import Model, quicksum, multidict, SCIP_PARAMSETTING
..\lib\site-packages\pyscipopt\__init__.py:5: in <module>
    from pyscipopt.scip      import Model
E   ImportError: DLL load failed: 找不到指定的模块。

...

____________________________________ ERROR collecting tests/test_variablebounds.py ____________________________________
ImportError while importing test module 'D:\Python3plus\PySCIPOpt\tests\test_variablebounds.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_variablebounds.py:1: in <module>
    from pyscipopt import Model
..\lib\site-packages\pyscipopt\__init__.py:5: in <module>
    from pyscipopt.scip      import Model
E   ImportError: DLL load failed: 找不到指定的模块。
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 22 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 1 skipped, 22 error in 0.33 seconds =========================================_


Hope some helps and Thanks!

**Comment by mattmilten** [comment]
You should set up a new, clean virtual environment, preferably with [Anaconda](https://www.anaconda.com/distribution/). As you can see, there is already a previously installed but broken PySCIPOpt found in your system.

For now, you also don't need to run the entire test suite - it's enough to test for `python -c import pyscipopt`

**Comment by eeliubin** [comment]
> You should set up a new, clean virtual environment, preferably with [Anaconda](https://www.anaconda.com/distribution/). As you can see, there is already a previously installed but broken PySCIPOpt found in your system. Try to locate and delete every trace of this installation. It should be in some `python\lib\site-packages` directory.
> 
> For now, you also don't need to run the entire test suite - it's enough to test for `python -c import pyscipopt`

Thanks Matthias, by the way is it possible to

**Comment by eeliubin** [comment]
> You should set up a new, clean virtual environment, preferably with [Anaconda](https://www.anaconda.com/distribution/). As you can see, there is already a previously installed but broken PySCIPOpt found in your system. Try to locate and delete every trace of this installation. It should be in some `python\lib\site-packages` directory.
> 
> For now, you also don't need to run the entire test suite - it's enough to test for `python -c import pyscipopt`

Thanks Matthias, I finally got it work in Anaconda3.

Another questions is do you have any API manual for using SCIP in Python?

Thanks!

**Comment by mattmilten** [comment]
Good! Thanks for the feedback.

**Comment by eeliubin** [comment]
> Good! Thanks for the feedback. We are currently working on providing an online documentation. For now you will have to use `help()` in Python or use tab/auto-completion in IPython etc.

Hi Matthias, got another question, hope you can provide some suggestions.
https://github.com/SCIP-Interfaces/PySCIPOpt/issues/251
Thanks!
