### ISSUE TITLE
Using SCIP-SDP viar CBF-format

### ISSUE THREAD

**Issue by eeliubin** [SCIP-Interfaces/PySCIPOpt#252]
Hi All,
I was trying to using CBF-format to call the scipsdp-3.1.1, however, resulting error indicating that only VER 1 is supported currently. Moreover, it also showed that 

`ERROR: SDPs in primal form currently not supported, please use PSDCON`

Dose this mean I cannot formulate the constraint X>=0 in an efficient way, but have to build the constraint with more complicated PSDCON?

By the way, can I build the model more efficiently with SDPA format?

Thanks!

**Comment by mattmilten** [comment]
SCIP-SDP is not available in PySCIPOpt. Please refer to the SCIP mailing list or the projects webpage http://www.opt.tu-darmstadt.de/scipsdp/
