### ISSUE TITLE
Install PySCIPOpt on 64-bit Windows 10 with Python 3.7/Python 3.5

### ISSUE THREAD

**Issue by zy09838** [SCIP-Interfaces/PySCIPOpt#272]
Hi there, 

I was trying to install PySCIPopt on 64-bit Windows 10 and Python 3.7/Python 3.5 following the steps in https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.md. While there is still a error when I call/import PySCIPOpt. 

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyscipopt
  File "C:\Python\lib\site-packages\pyscipopt\__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model
ImportError: DLL load failed: The specified module could not be found.
```

Though my error is very similar to the issue #249 #110, I can't solve my problem through solutions mentioned.

Specifically, I have a trial with Python 3.5 first and I met this error, I thought it may be caused by my Python version or previously uncleared files, thus I installed a new Python (Python 3.7) and reinstall everything following instruction, I met exactly same error again. Additionally I have tried both SCIPOptSuite 5.0.1 & SCIPOptSuite 6.0.1, I have already set environment variable as C:\Program Files\SCIPOptSuite 5.0.1\bin (for 5.0.1) or C:\Program Files\SCIPOptSuite 6.0.1\bin (for 6.0.1), it still doesn't work. 

Could you help me there?

Thanks in advance.

**Comment by mattmilten** [comment]
Make sure that you only have one installation of the SCIPOptSuite - the latest - in your path. Otherwise you might end up linking to the wrong one. Did you set `SCIPOPTDIR` before installing PySCIPOpt? Please write down the exact commands you used.

**Comment by zy09838** [comment]
After I did a Window system update and restart my laptop again, it then start to work. I think maybe system haven't updated Path (though I restarted my laptop after adding SCIPOPTDIR's path, it is pretty strange). But anyway it is working right now, thanks a lot! Please close this issue.
