### ISSUE TITLE
ScipOpt 6.0.1 Build no config.h generated

### ISSUE THREAD

**Issue by nfunwigabga** [SCIP-Interfaces/PySCIPOpt#274]
I tried to install PySCIPOpt and get an error that 
`fatal error: scip/config.h: No such file or directory`. 

```
OS: Centos 7
```

I built SCIP Suite using `make` as follows:
`make GMP=false ZIMPL=false INSTALLDIR="/usr/local"`

Then I exported the path:
`export SCIPOPTDIR=/usr/local`

Everything seems to work, and I can actually launch SCIP via `scip`. But when I try to `pip install pyscipopt`, I get the error that the `config.h` header file is missing (and it sure is missing from the includes directory). I may be wrong but I thought the file is supposed to be generated by the build process. Am I doing something wrong?

**Comment by mattmilten** [comment]
You are using the "old" Makefile system to build SCIP. Unfortunately, this is not compatible with PySCIPOpt. Please use the CMake installation/build procedure as explained here: https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.md#requirements

**Comment by nfunwigabga** [comment]
O i see... i missed that little detail. Thanks very much.

**Comment by purin0604** [comment]
Should I install the entire SCIP Optimization Suite or can I only install scip in the scipoptsuit using cmake to be compatible with PySCIPOpt?
I keep having trouble with installing the entire suite, so I am wondering if installing only scip using Cmake is enough to use Python interface.
Thank you

**Comment by mattmilten** [comment]
This issue has been closed. Please open a new one for a new question.
On topic: You need a fully working SCIP installation, not all parts of the SCIPOptSuite are required. You should definitely first try using the prebuilt installers instead of building SCIP yourself.
