### ISSUE TITLE
node 

### ISSUE THREAD

**Issue by arccos0** [SCIP-Interfaces/PySCIPOpt#279]

**Comment by arccos0** [comment]
Hi all,

    Is there any way for me to get node information during the solver searching the optimal solution? I want to plot a graph where the x-axis is the time step and the y-axis is the best found solution at a particular time point. 

thank you

Xiangyi

**Comment by mattmilten** [comment]
For this you might want to use the Eventhdlr plugin to collect the data whenever a certain event is triggered, e.g. a new solution is found. Look here for an example implementation: https://github.com/mattmilten/TreeD

**Comment by arccos0** [comment]
> For this you might want to use the Eventhdlr plugin to collect the data whenever a certain event is triggered, e.g. a new solution is found. Look here for an example implementation: https://github.com/mattmilten/TreeD

Hey! Thanks a lot. What you have suggested really works. :)
