### ISSUE TITLE
Cannot fix binary variable upper bound to zero when using model.addVar

### ISSUE THREAD

**Issue by ChiamYu** [SCIP-Interfaces/PySCIPOpt#287]
Hi! Thank for your writing this super useful package. I am trying to fix the upper bound of several binary variables to zero when creating a new variable, but the model still return the upper bound as 1. Is that a property of binary variable to ignore ub as argument? 

I am using PySCIPOpt==2.1.5 with python 2.7 and SCIP version 6.0.1.
```
# This UB is still 1, when the variable type is Binary
temp_var = self.model.addVar(
    name='myvar',
    vtype='B',
    lb=0,
    ub=0)
# LP file:  0 <= myvar <= 1


# The UB becomes 0 when I switch the variable type to Integer
temp_var = self.model.addVar(
    name='myvar',
    vtype='I',
    lb=0,
    ub=0)
# LP file:  0 <= myvar <= 0
```
Thanks!

**Comment by ChiamYu** [comment]
I just read the implementation https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/src/pyscipopt/scip.pyx#L1092 

Is it possible to assert that upper bound of binary variable cannot be larger than 1, instead of  fixing it to 1, because the argument `ub` is still accepted by the method?

**Comment by ramabile** [comment]
If the variable type is binary then any lower and upper bound will be override and forced by PySCIPOpt to 0 and 1, respectively. This is unexpected behaviour for me as user.

**Comment by mattmilten** [comment]
You are right, this is quite unexpected - especially since there is no warning message.

Based on a quick look into the relevant SCIP code, I did not see a reason for not allowing creation of fixed binary variables. I am going to check this.

**Comment by mattmilten** [comment]
Also, thank you @ChiamYu for your kind words!

**Comment by ChiamYu** [comment]
Thank you for fixing this @mattmilten !
