### ISSUE TITLE
setup.sh should work when libscipopt and scip includes are installed in a standard location

### ISSUE THREAD

**Issue by mkoeppe** [SCIP-Interfaces/PySCIPOpt#29]
I would suggest the following.
1) As seems to be standard with Cython extensions, users are expected to simply set CPPFLAGS and LDFLAGS so that the compiler will find headers ands the library.
2) Offer the SCIPOPTDIR variables as a convenience (which if provided would set include_dirs and library_dirs), but don't require it.
3) Don't require symlinks.

(On a related note, SCIP's "make install" forgets to install several header files. https://trac.sagemath.org/ticket/21094 has patches for that and other things.)

**Comment by mattmilten** [comment]
We were inspired by the way the JuliaOpt developers find/set these paths:
https://github.com/JuliaOpt/Gurobi.jl#installation

I also don't see why setting the two vars `CPPFLAGS` and `LDFLAGS` should be easier or more straight forward?

What's so bad about symlinks? I guess you would prefer to refer to the actual lib and header directly, right? This could be an alternative but then the user would need to set these paths whenever the interface needs to be recompiled - symlinks simply store this information for later use.

And yes, SCIP's `make install` is not working very well. We will most likely revamp the entire build system in the near future.

**Comment by leethargo** [comment]
"Standard locations" could also be searched in `setup.py` and the symlinks created then (if they don't exist yet).

**Comment by mkoeppe** [comment]
By the way, in case you are interested in testing PySCIPOpt with an installed version of SCIP (in a standard tree): SageMath version 7.4.beta0 has recently merged my package for SCIPOptSuite. You can get it from https://github.com/sagemath/sage/tree/develop -- after installation, "sage -i scipoptsuite" will install the package (need to manually put the scipoptsuite tarball into the upstream/ directory first).

**Comment by mkoeppe** [comment]
I just took another look at the current PySCIPOpt. The issue with `setup.py` persists -- it is not possible to install this package via `pip` (for example, directly from the git repository using `pip install git+https://github.com/SCIP-Interfaces/PySCIPOpt.git`) because there is no way to set symlinks between downloading and installation.

**Comment by mattmilten** [comment]
We're working on it. The following will improve with the next SCIP release:

- library archives that also contain the headers
- setup.py that works on pre-installed SCIP (either by pointing it to a custom path or by using the global one)

I'm not sure yet whether we should provide the `scip.c` which is compiled by Cython. The Cython docs recommend to provide this but I'm not sure where to put it, since it should not be part of the git repo.

**Comment by mkoeppe** [comment]
OK, looking forward to the new version.

Regarding the generated `scip.c`, if you want to include it (which I agree is useful), you would include it in the distribution built by `setup.py sdist` (and certainly not in the git repo).

**Comment by mattmilten** [comment]
OK, after playing around with the different options I found out different solutions:

- bdist_wheel: this would be my preferred solution but is not supported on Linux (I will try to publish it for Windows adn OSX as wheels)
- sdist: requires the user the build the interface, so he/she needs to have `libscipopt.so` and the headers available
- bdist_egg: should work on all platforms and only requires the `libscipopt.so` but it doesn't work with `pip`

Could you give me some insight on how to proceed best?

**Comment by mattmilten** [comment]
Oh and by the way, all these solutions of course don't require any symlinks or any preconfigurations. The `libscipopt.so` needs to be either installed in a usual path or its path needs to be added to `$LD_LIBRARY_PATH`.

**Comment by mkoeppe** [comment]
Every package needs to have a working "sdist". In particular this is what we need for Sage.

Binary distributions (bdist_*) are optional, and I have never used nor created one, so I can't give you advice on this.

**Comment by mattmilten** [comment]
The package is now uploaded to PyPI, both as sdist and as wheels for Windows.

Furthermore, setup.py will look for standard paths as well and is not forcing to create symlinks.

**Comment by mkoeppe** [comment]
scipoptsuite 4.0.0 shared library install is still broken on Mac OS X (see my message to the SCIP mailing list). Consequently pysciptopt is broken too.
