### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by fschloesser** [SCIP-Interfaces/PySCIPOpt#290]
The links in the documentation provided by the search field in the upper right are broken. They lead to `<a_page>.php.html`, whereas they should only lead to `<a_page>.php`.
However within the doc it seems to be working fine.

**Comment by mattmilten** [comment]
Furthermore, many classes, including `Model`, are not documented anymore. I suspect this is due to #321

**Comment by fserra** [comment]
@fschloesser is this still valid? I could navigate the documentation without a problem. The problem of Matthias I can see

**Comment by fserra** [comment]
So I have no idea why some classes are not appearing. The class Event and column appear as children of scip. But there are many more that don't appear Row, Model, etc. 

What I did find out is that only the first three classes listed in `scip.pxd` appear in the documentation. I didn't find any 3 in docs/doxy so I have no idea where this limit comes from.

Any ideas anybody?

**Comment by fschloesser** [comment]
From `docs/doxy` 
```
FILE_PATTERNS          = *.pyx *.pxd *.pxi *.py *.md
```
The fact that some classes (for example the Models) are defined both in `scip.pyx` and `scip.pxd` seem to make the documentation overwrite previous definitions instead of extending them. 
If you delete the *.pxd in the line 
```
FILE_PATTERNS          = *.pyx *.pxi *.py *.md
```
The models will appear in the documentation. Although I don't know if then you might be missing other things by not doxying the *.pxd files...

**Comment by mattmilten** [comment]
The documentation seems to be completely fine again.
