### ISSUE TITLE
Node selector to pass back the pointer to SCIP_NODE 

### ISSUE THREAD

**Issue by pg2455** [SCIP-Interfaces/PySCIPOpt#291]
Hi,

This might not be a code issue. I am writing an extension for node selector. It looks very similar to `branchrule.pxi`. I am stuck at implementing `PyNodeselSelect` which is responsible for node selection. 

```
cdef SCIP_RETCODE PyNodeselSelect (SCIP* scip, SCIP_NODESEL* nodesel, SCIP_NODE** selnode):
  cdef SCIP_NODESELDATA* nodeseldata
  nodeseldata = SCIPnodeselGetData(nodesel)
  PyNodesel = <Nodesel>nodeseldata
  pointer = PyNodesel.nodeselect()
  selnode[0] = pointer # pointer.scip_node doesn't work here
  return SCIP_OKAY
```
This cython function calls the cython class `Nodesel`, which is extended by the a python class to look at the current leaves in the node via `SCIPgetLeaves` API. `SCIPgetLeaves` returns the pointers to the leaf nodes. I am converting these pointers to the `Node` object and then deciding which leaf node should be selected (in PythonNodesel). 
How can I put the pointer of this selected leaf into `selnode[0]`? I am not much familiar with cython, but it might be that it's not logically possible. 
```
   # in "cdef class Model" in "scip.pyx"
    def getLeaves(self):
      cdef SCIP_NODE** leaves
      cdef int nleaves
      PY_SCIP_CALL(SCIPgetLeaves(self._scip, &leaves, &nleaves))
      cdef nodes = []
      for i in range(nleaves):
        nodes.append(Node.create(leaves[i]))
      return nodes
```

```
class PythonLBNodeSel(scip.Nodesel):
    def __init__(self):
        pass

    def nodeinitsol(self):
        print(self.model.getNNodes())

    def nodeselect(self):
        if len(self.model.getLeaves()) > 0:
            selnode = self.model.getLeaves()[0]
            return selnode # WRONG!!!

    def nodecomp(self, node1, node2):
        return 1
```
```
cdef class Nodesel:
  cdef public Model model

  def nodecopy(self):
    pass

  def nodefree(self):
    pass

  def nodeinit(self):
    pass

  def nodeexit(self):
    pass

  def nodeinitsol(self):
    pass

  def nodeexitsol(self):
    pass

  def nodeselect(self):
    # implement
    pass

  def nodecomp(self, node1, node2):
    # implement your own comparator
    return 0
```

**Comment by fserra** [comment]
mmm my guess would be something like this
```
cdef SCIP_RETCODE PyNodeselSelect (SCIP* scip, SCIP_NODESEL* nodesel, SCIP_NODE** selnode):
  cdef SCIP_NODESELDATA* nodeseldata
  nodeseldata = SCIPnodeselGetData(nodesel)
  PyNodesel = <Nodesel>nodeseldata
  result_dict = PyNodesel.nodeselect() # like the dictionaries that are used in the other pxi file
  selected_node = <Node>(result_dict.get("selnode", None)) # "selnode" or whatever the name should be
  selnode[0] = selected_node.scip_node # this should work now
  return SCIP_OKAY
```

let me know how it goes

**Comment by pg2455** [comment]
It worked! For the sake of understanding -  I thought that `Node` class can be called in Cython code using `Node()`. Why is `<Node>` used?

**Comment by fserra** [comment]
Cool.

Mmm I am not sure I understand the `Node()` comment, but the `<Node>` is just to cast the object to type `Node`. This is here https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#checked-type-casts

I guess that python or cython forgets that the returned object was of type Node, and one needs to remind it about that in order to access its internal data. Why this happens, I don't know...
