### ISSUE TITLE
missing method primalSetUpperbound

### ISSUE THREAD

**Issue by networds** [SCIP-Interfaces/PySCIPOpt#293]
I'm using Branch and Price to solve a set cover/set partition-style formulation.
For most instances, I know that there exists an integral optimal solution, but the solver has difficulties finding it.

I would like to inform SCIP that it should, in the branching, either prune nodes with a LB strictly higher than the root LP optimum, or at least to ignore those nodes and continue with the others.

My best guess is that this can be done with `SCIPprimalSetUppberbound`, but it is not implemented in `PySCIPOpt` at the moment.

Can you help out by adding this method to `PySCIPOpt`, or help me find a different way of accomplishing what I try to do?

Many thanks in advance!

**Comment by fserra** [comment]
I guess `setObjlimit` would do what you want, or am I missing something?

**Comment by networds** [comment]
Ah yes thanks :) `setObjlimit` is indeed what I was looking for.
