### ISSUE TITLE
Import error for libscip.so.6.0

### ISSUE THREAD

**Issue by nfunwigabga** [SCIP-Interfaces/PySCIPOpt#295]
I followed the install instructions to build SCIPOptsuite as follows:
```
mkdir build && cd build
cmake3 ..
make READLINE=false
make check
make install INSTALLDIR=/usr/local
```

then I exported the install path as follows:
```
export SCIPOPTDIR=/usr/local
```

then I installed PyScipOpt using `pip install pyscipopt`

I do not get any errors, but when I do `from pyscipopt.scip import Model` I get the error:
```
ImportError: libscip.so.6.0: cannot open shared object file: No such file or directory
```

I can see `libscip.so.6.0` in the `/usr/local/lib` folder and all other folders seem to be ok (bin, include). I can also launch the scip terminal via `scip`. Not sure why the import in my python script is failing.

I am using `CentOS7` with Python 3.6.

**Comment by nfunwigabga** [comment]
OK, i see that I forgot to add `/usr/local` to my PATH, so
```
export PATH=$PATH:/usr/local
```
solved it for me.

**Comment by blim747** [comment]
I got this error today too for 8.0 and this fixed it:
```
ldconfig /opt/pyscipopt/lib
```

Where `ldconfig /opt/pyscipopt` is where I executed the install script https://www.scipopt.org/download.php?fname=SCIPOptSuite-8.0.3-Linux-ubuntu.sh
