### ISSUE TITLE
Issue with variable data when using SCIP debug build

### ISSUE THREAD

**Issue by raviagrwl420** [SCIP-Interfaces/PySCIPOpt#299]
I am working with a very simple script where I read a MIP instance and access its variable data.
```
from pyscipopt import Model

instance = 'mc11.mps'

# initialize the model
model = Model(instance)
model.readProblem(instance)

# get the data
vars = model.getVars()
vtypes = []
vcoeffs = []

for var in vars:
    vtypes.append(var.vtype())
    vcoeffs.append(var.getObj())

print(set(vtypes))
print(set(vcoeffs))

model.optimize()
```
This seems to work fine with a SCIP release build but not with the debug build.
Output (with release build):
```
original problem has 3040 variables (1520 bin, 0 int, 0 impl, 1520 cont) and 1920 constraints
{'CONTINUOUS', 'BINARY'}
{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 197.0, 198.0, 199.0, 200.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0, 219.0, 220.0, 221.0, 222.0, 223.0, 224.0, 225.0, 226.0, 227.0, 228.0, 229.0, 230.0, 231.0, 232.0, 233.0, 234.0, 236.0, 237.0, 238.0, 239.0, 240.0, 241.0, 242.0, 243.0, 244.0, 245.0}
```
Output (with debug build):
```
original problem has 3040 variables (1520 bin, 0 int, 0 impl, 1520 cont) and 1920 constraints
{'CONTINUOUS'}
{4.6453440346783e-310}
```
Note that the output from SCIP when reading the instance is the same in both the cases. Moreover, it solves the instance correctly irrespective of the build used. This should mean that there is some issue with accessing the variable data. I would suspect that this should be an issue with SCIP and not PySCIPOpt but I'm not entirely sure.

Details:
1. SCIP 6.0.1 + SOPLEX 4.0.1
2. PySCIPOpt v2.1.6

**Comment by fserra** [comment]
interesting.

I could reproduce it. Apparently when one uses the debug version one must compile with:
`python setup.py install --debug`

I don't really know why it does not work otherwise. @mattmilten do you know?

**Comment by mattmilten** [comment]
I suppose it's an effect of broken headers: When you use `--debug`, you undefine the `NDEBUG` flag that is used in some headers making it compatible with the debug build library.

**Comment by raviagrwl420** [comment]
@fserra Thanks! That didn't occur to me.
@mattmilten Thanks! Makes sense now.
