### ISSUE TITLE
Cannot fix variables with chgVarLb() / chgVarUb()

### ISSUE THREAD

**Issue by joaopedroso** [SCIP-Interfaces/PySCIPOpt#31]
Fixing variables with model.chgVarLb() / chgVarUb() does not seem to be working.  Using the program attached (and miplib3's instance p0033.mps) leads to the error:

[src/scip/scip.c:19803] ERROR: invalid SCIP stage <10>
[...]
Exception: SCIP: method cannot be called at this time in solution process!

jpp

[mipissue.py.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/394019/mipissue.py.txt)

**Comment by mattmilten** [comment]
You need to call `freeTransform()`. SCIP will always create a transformed problem - even if presolving is disabled like in your example.

**Comment by joaopedroso** [comment]
Thanks.

The timing for calling ``freeTransform()`` seems to be after the first call to ``optimize()`` (it works, though it invalidates further calls to model.getVars()).

The corrected code is::

    from pyscipopt import Model, quicksum, multidict, SCIP_PARAMSETTING
     
    model = Model("test")
    model.readProblem("p0033.mps")
    for var in model.getVars():
        if var.vtype() != "CONTINUOUS":
            model.chgVarType(var, "CONTINUOUS")
     
    model.setPresolve(SCIP_PARAMSETTING.OFF)
    model.optimize()
     
    EPS = 1.e-3
    for var in model.getVars():
        lp = model.getVal(var)  # <<< would not work after calling freeTransform
        if lp > EPS and lp < (1-EPS):
            fix = int(lp +.5)
            model.freeTransform()
            model.chgVarLb(var, fix)
            model.chgVarUb(var, fix)
            print("fixed variable {} to {}".format(var.name, fix))
            break
     
    model.optimize()
    for var in model.getVars():
        print("{} --> {}".format(var.name, model.getVal(var)))

jpp

**Comment by mattmilten** [comment]
Is this fixed now?

**Comment by joaopedroso** [comment]
It is fixed, thanks.
Here is a usage example: a randomized relax-and-fix for MIP instances in mps format.

jpp

[scip_rnd_relax-and-fix.py.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/514478/scip_rnd_relax-and-fix.py.txt)
