### ISSUE TITLE
Latest version of PySCIPOpt goes wrong while v1.4.9 works fine

### ISSUE THREAD

**Issue by brucefeng10** [SCIP-Interfaces/PySCIPOpt#317]
Hi all,
After installing the latest version of PySCIPOpt in Python3.6 on Windows64, I try to call it by `from pyscipopt import Model`, and a common error occurs as follows:
```
from pyscipopt.scip import Model
ImportError: DLL load failed: The specified module could not be found.
```
I have included `C:\Program Files\SCIPOptSuite 5.0.1\bin` to my system path. So I guess this should not be the problem.

Then I removed my PySCIPOpt of the latest version, and installed PySCIPOpt of version v1.4.9. Now everything works fine. 
I don't know if anybody else has encountered this, and what might have caused this?

**Comment by mattmilten** [comment]
PySCIPOpt is not backwards compatible to older versions of the SCIP Optimization Suite. You should always use the latest PySCIPOpt together with the latest SCIP version. You should not just update one part.
