### ISSUE TITLE
m.getStatus() returns "unknow" when gap limit reached

### ISSUE THREAD

**Issue by brucefeng10** [SCIP-Interfaces/PySCIPOpt#325]
Before implementing `m.optimize()`, I set optimization stopping gap by `m.setRealParam('limits/gap', 0.02)`, so the optimization will stop when the gap reaches 0.02. The log shows 
```
SCIP Status        : solving was interrupted [gap limit reached]
```
but `m.getStatus()` returns "unknow" value.  

Note that when I set optimization stopping time by `m.setRealParam('limits/time', 10)`, `m.getStatus()` returns "timelimit" value, that make senes.

**Comment by mueldgog** [comment]
This issue has been fixed already. Please check out the latest version of PySCIPOpt.
