### ISSUE TITLE
The branch candidates change after probings

### ISSUE THREAD

**Issue by Wenbo11** [SCIP-Interfaces/PySCIPOpt#328]
We try to get the gap after branching a node.

The probing code snippet is following:

```
    assert not model.inRepropagation()
    assert not model.inProbing()
    branch_cand1 = model.getLPBranchCands()
    print(f'branch_cand1 is {len(branch_cand1[0])}')
    model.startProbing()
    model.fixVarProbing(branch_cand[0][i], int(np.ceil(branch_cand[1][i])))
    model.constructLP()
    model.solveProbingLP()
    gap = model.getGap()
    model.endProbing()
    branch_cand2 = model.getLPBranchCands()
    print(f'branch_cand2 is {len(branch_cand2[0])}')
```

When we repeated the previous code, we sometimes observed the branch_cand1 and branch_cand2 are different after the model.endProbing(). Could you please explain this phenomenon? Thanks

Best.

**Comment by fserra** [comment]
hi @Wenbo11 

After probing scip sets back the old basis and then resolves the LP again (hopefully instantly). However, if there is degeneracy it can go to a different solution.
Also, if the LP that you solve in probing is, for example, infeasible, then conflict analysis will be run and this can affect the problem after you end probing

**Comment by Wenbo11** [comment]
Thanks for your suggestions!
For the case one you mentioned, being curious, why scip needs to resolves the LP even if it has found an exact solution of the LP?
Further, I turned off the conflict analysis when solving the MIP. Would the second case still happen?

**Comment by fserra** [comment]
The thing is that something might happen during probing. So SCIP would need to resolve anyway if something happened. If nothing happened, it should solve instantly.

**Comment by Wenbo11** [comment]
Thank you so much.
