### ISSUE TITLE
cannot use pyscipopt module in conda environment

### ISSUE THREAD

**Issue by kovacsrekaagnes** [SCIP-Interfaces/PySCIPOpt#332]
I am trying to create a new project in pycharm using Conda and I get the following error**. 
I get the same error** if I write in the terminal: conda install pyscipopt.
If I write pip install pyscipopt in the terminal, I get:
Requirement already satisfied: pyscipopt in /Users/rkovacs/anaconda3/lib/python3.7/site-packages (2.2.3)

I don't really understand what I am doing wrong or if there is a problem using pyscipopt from a Conda environment.

**
Solving environment: ...working... failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://github.com/SCIP-Interfaces/PySCIPOpt.git/noarch/repodata.json>
Elapsed: 00:00.312557

The remote server could not find the noarch directory for the
requested channel with url: https://github.com/SCIP-Interfaces/PySCIPOpt.git

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by mattmilten** [comment]
Hi,
There simply is no conda package of PySCIPOpt. You have to install the one from PyPI using `pip install pyscipopt`.
There is no disadvantage of using pip packages in a conda environment - I do it all the time, because several packages are only available via pip.

Cheers,
Matthias
