### ISSUE TITLE
Branch Ordering

### ISSUE THREAD

**Issue by AtefehRajabalizadeh** [SCIP-Interfaces/PySCIPOpt#341]
Hello, I am using SCIP and I am coding with python 2. I want to fix the variables branch ordering before solving the problem. for example, the problem starts branching ar zero, then one, ...
How should I do that? I know that in CPLEX there is "order.set(BranchOrdering)" but I cannot find anything in SCIP.

**Comment by mattmilten** [comment]
I suppose what you are looking for is this parameter:

```
# child selection rule ('d'own, 'u'p, 'p'seudo costs, 'i'nference, 'l'p value, 'r'oot LP value difference, 'h'ybrid inference/root LP value difference)
# [type: char, advanced: FALSE, range: {dupilrh}, default: h]
nodeselection/childsel = h
```

**Comment by fserra** [comment]
I think Atefeh wants to fix the branching order. I guess setting the branching priority of variable 1 highest then var 2 and so on.

**Comment by AtefehRajabalizadeh** [comment]
> I think Atefeh wants to fix the branching order. I guess setting the branching priority of variable 1 highest then var 2 and so on.

Yes Exactly.

**Comment by mattmilten** [comment]
Alright, then you need to call [SCIPchgVarBranchPriority()](https://scip.zib.de/doc-6.0.2/html/group__PublicVariableMethods.php#ga274db1c9e91d873799f6484e45a8d6bc)... after you have added this to the interface.

**Comment by AtefehRajabalizadeh** [comment]
How should I add it to the interface? I am totally new to SCIP. could you provide one example for that? I could not find any example in Python API

**Comment by fserra** [comment]
in the readme there is a section: Extending the interface

**Comment by fserra** [comment]
Hey @AtefehRajabalizadeh I just extended the interface with a couple of functions

you can see [here](https://github.com/SCIP-Interfaces/PySCIPOpt/pull/344/files)  to see what needs to be done

**Comment by AtefehRajabalizadeh** [comment]
Thank you @fserra. I copied scip.pxd of the pull request section to what I already had in the installation path. Unfortunately, I have not seen any chgVarBranchPriority() yet. But my understanding is that I should add it this function to my scip.pxd file and then call it from python. is that right?

**Comment by fserra** [comment]
yes, you need to add it. I just wanted to show how to add functions. Basically you put in pxd the signature from the SCIP API. Then in pyx you implemented. As you can see, almost always the implementation is straightforward, just a wrapper to call the C function. The documentation of the python function is usually copied from the documentation of the C function.

 You wanna give it a try? You can open a pull request afterward, so then we can tell you if it is ok and we can also merge it.

**Comment by AtefehRajabalizadeh** [comment]
Hello @fserra. I wrote this code in my scip.pyx file:
`    def chgVarBranchPriority(self, Variable var, priority):     
        if priority is None:
            priority = 0
        PY_SCIP_CALL( SCIPchgVarBranchPriority(self._scip, var.scip_var, priority) )`
and also added this code in my scip.pxd:
`SCIP_RETCODE SCIPchgVarBranchPriority(SCIP* scip, SCIP_VAR* var, int branchpriority)`
Unfortunately, I still cannot call chgVarBranchPriority() in my python project. Is there any further steps that I should follow?
I am totally new in c and Scip. I would appreciate it if you could give me more hints.
Regards,

**Comment by fserra** [comment]
you have to recompile the interface after you add those functions.  Look at https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.md#building-everything-from-source

**Comment by AtefehRajabalizadeh** [comment]
I read the link you mentioned. It seems to be so much harder than I expected. Here are the steps I followed:
1) pip installed Cython.
2) downloaded PySCIPOpt package files from Github. replaced scip.pxd and scip.pyx with my edited files which I added some functions the way you mentioned.
3) tried to install the edited package from my local source. however, I got the following errors:
`C:\Users\Atefeh>set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 6.0.2"

C:\Users\Atefeh>set PATH=%PATH%;%SCIPOPTDIR%\bin

C:\Users\Atefeh>pip install c:/users/atefeh/pyscipopt/
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing c:\users\atefeh\pyscipopt
Installing collected packages: PySCIPOpt
    Running setup.py install for PySCIPOpt ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\public\\documents\\wondershare\\creatortemp\\pip-req-build-kzaaqg\\setup.py'"'"'; __file__='"'"'c:\\users\\public\\documents\\wondershare\\creatortemp\\pip-req-build-kzaaqg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\public\documents\wondershare\creatortemp\pip-record-vgwqrp\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python27\64\Include\PySCIPOpt'
         cwd: c:\users\public\documents\wondershare\creatortemp\pip-req-build-kzaaqg\
    Complete output (38 lines):
    Using include path <C:\Program Files\SCIPOptSuite 6.0.2\include>.
    Using SCIP library <scip> at <C:\Program Files\SCIPOptSuite 6.0.2\lib>.
    c:\python27\64\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\__init__.py -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\benders.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\benderscut.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\event.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\nodesel.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\relax.pxi -> build\lib.win-amd64-2.7\pyscipopt
    copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-2.7\pyscipopt
    running build_ext
    building 'pyscipopt.scip' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\src\pyscipopt
    C:\Users\Atefeh\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\SCIPOptSuite 6.0.2\include" -Ic:\python27\64\include -Ic:\python27\64\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-2.7\Release\src\pyscipopt\scip.obj
    scip.c
    C:\Program Files\SCIPOptSuite 6.0.2\include\scip/def.h(33) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\Atefeh\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python27\64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\public\\documents\\wondershare\\creatortemp\\pip-req-build-kzaaqg\\setup.py'"'"'; __file__='"'"'c:\\users\\public\\documents\\wondershare\\creatortemp\\pip-req-build-kzaaqg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\users\public\documents\wondershare\creatortemp\pip-record-vgwqrp\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python27\64\Include\PySCIPOpt' Check the logs for full command output.
`
I do not know what is wrong. I really appreciate your help.

**Comment by fserra** [comment]
@mattmilten is there a simple way of recompiling the interface in windows?

**Comment by AtefehRajabalizadeh** [comment]
Dear @mattmilten ,I really need to work with SCIP and when I found that this function is not in python I tried C and SCIP and it was much more difficult in windows. I really appreciate it if you could provide a procedure of adding a function so I will be able to handle SCIP with python.
Thank you very much in advance.

**Comment by mattmilten** [comment]
Dear @AtefehRajabalizadeh, first you should install Anaconda or miniconda and use an up-to-date python. I'd recommend python-3.7. Then the command above should not fail.

**Comment by AtefehRajabalizadeh** [comment]
Dear @mattmilten and @fserra, Finally I could see my function in the model properties. Thank you so much for that. I have not tested it though. Hopefully, it works perfectly. I really appreciate your time and help.
Best,
Atefeh

**Comment by fserra** [comment]
This is great news! 

It would be nice if you could open a pull request with your extensions to the interface.

**Comment by AtefehRajabalizadeh** [comment]
I will do that for sure if I can make sure it works correctly.
