### ISSUE TITLE
AttributeError: 'pyscipopt.scip.Model' object has no attribute 'getKhalilState

### ISSUE THREAD

**Issue by vincentfortin** [SCIP-Interfaces/PySCIPOpt#345]
I installed PySCIPOpt, both using pip, as well as installing from the source. Imports work correctly.

I am using SCIP version 6.0.1

**Comment by fserra** [comment]
what is a Khalil State?

**Comment by vincentfortin** [comment]
It is an attribute in the following code base.
https://github.com/ds4dm/learn2branch/blob/a00e27c408cd0899b22f8bd5d73a85c82c052b28/utilities.py#L286

I could not find somewhere in the code where they defined this attribute, so I assumed that it was an attribute of the SCIP model.

**Comment by fserra** [comment]
It is not an attribute of the SCIP model.

I guess you should open an issue in the learn2branch repo

**Comment by vincentfortin** [comment]
Thanks, I did so.
