### ISSUE TITLE
Fixed Variables

### ISSUE THREAD

**Issue by AtefehRajabalizadeh** [SCIP-Interfaces/PySCIPOpt#347]
Hello, I have a question, I would appreciate it if you could help me to find its answer. I am trying to get the fixed variables at each node (at each node of the branch and bound tree those with integer value or those with equal lower and upper bound). I found the function getVar() under event class. I also saw these two links, and I could not get it in node information:
[https://github.com/mattmilten/TreeD/blob/master/TreeD.py](url)
[ https://github.com/SCIP-Interfaces/PySCIPOpt/issues/284](url)
The code that I am trying to run is:

```
    class MyEvent(Eventhdlr):

        def __init__(self, var):
            self.var = var

        def eventinit(self):
            calls.append('eventinit')
            self.model.catchVarEvent(self.var, SCIP_EVENTTYPE.VARFIXED, self)

        def eventexit(self):
            calls.append('eventexit')
            self.model.dropVarEvent(self.var, SCIP_EVENTTYPE_VARFIXED, self)

        def eventexec(self, event):
            calls.append('eventexec')
            print('Var: ', event.getVar())

    calls = []        


    model = Model("")
    model.readProblem("3030/NewExample1.lp")
    var=model.getVars()
    eventhdlrVar = MyEvent(var[0])
    model.includeEventhdlr(eventhdlrVar, "TestFixedVar", "python event handler to catch FixedVar")
    model.optimize()
```

I get an error with the code and I do not think even it gives me what I want at each node when we are solving the LP-relaxation.
I can take the fixed variables by checking the lower bound and upper bound but I want to make sure I am taking the fastest procedure.
Thank you in advance,
Atefeh

**Comment by fserra** [comment]
Hi @AtefehRajabalizadeh 
I am not 100% sure what you want. The following code prints the list of fixed variables after each node is solved (meaning: after the node is detected feasible, infeasible or was branched on).
It will work after #353 gets merged.

```python
from pyscipopt import Model, Eventhdlr, quicksum, SCIP_EVENTTYPE
import sys

class FixedVarsAtNode(Eventhdlr):
    """PySCIPOpt Event handler to print fixed vars of each node."""

    def eventexec(self, event):
        # collect fixed vars
        fixedvars = []
        self.transvars = self.model.getVars(transformed = True)
        for var in self.transvars:
            if self.model.isFeasEQ(var.getLbLocal(), var.getUbLocal()):
                fixedvars.append(var.name)

        # print fixed vars
        nodenumber = event.getNode().getNumber()
        print("Vars fixed at node %d are:"%(nodenumber))
        print(fixedvars)

    def eventinit(self):
        self.model.catchEvent(SCIP_EVENTTYPE.NODESOLVED, self)

    def eventexit(self):
        self.model.dropEvent(SCIP_EVENTTYPE.NODESOLVED, self)

if __name__ == "__main__":

    scip = Model()

    # read instance
    if len(sys.argv) <= 1:
        print("Error: specify model.")
        exit(0)

    print("File: " + sys.argv[1])
    scip.readProblem(sys.argv[1])

    # create and add event handler
    eventhdlr = FixedVarsAtNode()
    scip.includeEventhdlr(eventhdlr, "PrintVarsAtNode", "python event handler to print fixed variables after each solved node")

    # solve
    scip.printVersion()
    scip.optimize()
```

**Comment by AtefehRajabalizadeh** [comment]
Thank you so much. I could not find model.isFeaseq though. I implemented like this:
`
class LPstatEventhdlr(Eventhdlr):
     def collectNodeInfo(self, firstlp = True):
        branched=list()
         for i in range (self.n):
            if self.var[i].getLbLocal()==self.var[i].getUbLocal() : 
                branched.append(i)                   

    def eventexec(self, event):
        if event.getType() == SCIP_EVENTTYPE.FIRSTLPSOLVED:
            self.collectNodeInfo(True)
        elif event.getType() == SCIP_EVENTTYPE.LPSOLVED:
            self.collectNodeInfo(False)
        else:
            print("unexpected event:" + str(event))
        return {}

    def eventinit(self):
        self.model.catchEvent(SCIP_EVENTTYPE.LPEVENT, self)

`

**Comment by fserra** [comment]
you should be careful when comparing floats with `==`. If you mostly have binary variables you can check that `ub -lb < 0.5`. Otherwise I would just use the `isFeasEQ` which is in the current master. Also, not every fixed variable is a variable it was branched on.
