### ISSUE TITLE
Infeasible MIP

### ISSUE THREAD

**Issue by dfvial** [SCIP-Interfaces/PySCIPOpt#352]
Hi, I am trying to figure out why SCIP doesnt recognize infeasibility in this MIP,

from pyscipopt import Model, quicksum

MIP = Model("Modelo");

X = MIP.addVar(vtype="BINARY",name= "tiempo en mantenimiento");
Y = MIP.addVar(vtype="BINARY",name= "tiempo en mantenimiento");

MIP.addCons(X+Y<=1,"parte en mante");
MIP.addCons(Y==1,"parte en mante");
MIP.addCons(X==1,"parte en mante");

MIP.setObjective(X+Y);

MIP.optimize();

print(MIP.getVal(X))
print(MIP.getVal(Y))
print (MIP.getVal(X) + MIP.getVal(Y))

Solution: X= 1, Y =1

**Comment by fserra** [comment]
which scip version are you using? (add `MIP.printVersion()` somewhere in your code).
With SCIP 6.0.2 it detects infeasibility just fine.

**Comment by mueldgog** [comment]
You are misusing the API. `getVal()` does not give you the solution value of the best-found solution. You need to check the solution status via `getStatus()` and then access the best solution by `getBestSol`. So the code could look like:

```
if MIP.getStatus() == "optimal":
   sol = MIP.getBestSol()
   print(sol[x])
   print(sol[y])
   print(sol[x] + sol[y])
```
