### ISSUE TITLE
Trouble installing PySCIPOpt on Windows 10

### ISSUE THREAD

**Issue by kasp9201** [SCIP-Interfaces/PySCIPOpt#358]
Dear Github! I am having some trouble installing PySCIPOpt using pip install. When I try I get the following error message:

> Building wheels for collected packages: pyscipopt
  Building wheel for pyscipopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Kasper\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-xv9fls5m\\pyscipopt\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kasper\\AppData\\Local\\Temp\\pip-install-xv9fls5m\\pyscipopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Kasper\AppData\Local\Temp\pip-wheel-cgujggxd'
       cwd: C:\Users\Kasper\AppData\Local\Temp\pip-install-xv9fls5m\pyscipopt\
  Complete output (63 lines):
  Using include path <C:\Program Files\SCIPOptSuite 7.0.0\include>.
  Using SCIP library <scip> at <C:\Program Files\SCIPOptSuite 7.0.0\lib>.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\__init__.py -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\benders.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\benderscut.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\event.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\nodesel.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\relax.pxi -> build\lib.win-amd64-3.7\pyscipopt
  copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-3.7\pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\pyscipopt
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\SCIPOptSuite 7.0.0\include" -IC:\Users\Kasper\anaconda3\include -IC:\Users\Kasper\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-3.7\Release\src\pyscipopt\scip.obj
  scip.c
  src\pyscipopt\scip.c(74021): warning C4047: 'function': 'unsigned int' differs in levels of indirection from 'unsigned int *'
  src\pyscipopt\scip.c(74021): warning C4024: 'SCIPcopyOrig': different types for formal and actual parameter 8
  src\pyscipopt\scip.c(74021): error C2198: 'SCIPcopyOrig': too few arguments for call
  src\pyscipopt\scip.c(74064): warning C4047: 'function': 'unsigned int' differs in levels of indirection from 'unsigned int *'
  src\pyscipopt\scip.c(74064): warning C4024: 'SCIPcopy': different types for formal and actual parameter 9
  src\pyscipopt\scip.c(74064): error C2198: 'SCIPcopy': too few arguments for call
  src\pyscipopt\scip.c(87695): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  src\pyscipopt\scip.c(90853): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  src\pyscipopt\scip.c(93979): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
  src\pyscipopt\scip.c(94559): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
  src\pyscipopt\scip.c(95151): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
  src\pyscipopt\scip.c(100793): warning C4133: 'function': incompatible types - from 'SCIP_VAR *' to 'SCIP_RELAX *'
  src\pyscipopt\scip.c(100793): error C2440: 'function': cannot convert from 'double' to 'SCIP_VAR *'
  src\pyscipopt\scip.c(100793): warning C4024: 'SCIPsetRelaxSolVal': different types for formal and actual parameter 3
  src\pyscipopt\scip.c(100793): error C2198: 'SCIPsetRelaxSolVal': too few arguments for call
  src\pyscipopt\scip.c(103274): error C2198: 'SCIPsetupBendersSubproblem': too few arguments for call
  src\pyscipopt\scip.c(103311): warning C4047: 'function': 'double *' differs in levels of indirection from 'int'
  src\pyscipopt\scip.c(103311): warning C4024: 'SCIPsolveBendersSubproblem': different types for formal and actual parameter 7
  src\pyscipopt\scip.c(103311): warning C4020: 'SCIPsolveBendersSubproblem': too many actual parameters
  src\pyscipopt\scip.c(104390): error C2198: 'SCIPsetupBendersSubproblem': too few arguments for call
  src\pyscipopt\scip.c(104694): warning C4047: 'function': 'double *' differs in levels of indirection from 'unsigned int'
  src\pyscipopt\scip.c(104694): warning C4024: 'SCIPsolveBendersSubproblem': different types for formal and actual parameter 7
  src\pyscipopt\scip.c(104694): warning C4020: 'SCIPsolveBendersSubproblem': too many actual parameters
  src\pyscipopt\scip.c(108733): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
  src\pyscipopt\scip.c(110033): warning C4113: 'SCIP_RETCODE (__cdecl *)(SCIP *,SCIP_BENDERS *)' differs in parameter lists from 'SCIP_RETCODE (__cdecl *)(SCIP *,SCIP_BENDERS *,unsigned int)'
  src\pyscipopt\scip.c(110033): warning C4113: 'SCIP_RETCODE (__cdecl *)(SCIP *,SCIP_BENDERS *,SCIP_SOL *,SCIP_BENDERSENFOTYPE,unsigned int,unsigned int *,SCIP_RESULT *)' differs in parameter lists from 'SCIP_RETCODE (__cdecl *)(SCIP *,SCIP_BENDERS *,SCIP_SOL *,SCIP_BENDERSENFOTYPE,unsigned int,unsigned int *,unsigned int *,unsigned int *,SCIP_RESULT *)'
  src\pyscipopt\scip.c(120675): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
  src\pyscipopt\scip.c(121277): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pyscipopt

I have installed Visual Studio C++ for Python together with the SDK using the Visual Studio installer. Furthermore, I have installed SCIPOptSuite 7.0.0 and added its path to my user variables such that I am able to run SCIP from the command line. My SCIPOpt is installed in "C:\Program Files\SCIPOptSuite 7.0.0" so as instructed by the installation guide I first run `set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 7.0.0"` and then `pip install pyscipopt`. If it's to any help you can see my path user variables below:

> C:\Users\Kasper\anaconda3;C:\Users\Kasper\anaconda3\Library\mingw-w64\bin;C:\Users\Kasper\anaconda3\Library\usr\bin;C:\Users\Kasper\anaconda3\Library\bin;C:\Users\Kasper\anaconda3\Scripts;C:\MinGW\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\cuda\bin;C:\Users\Kasper\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Kasper\AppData\Local\Programs\Python\Python37\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\Kasper\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\Kasper\AppData\Roaming\Python\Python37\Scripts;%PyCharm%;C:\Program Files\SCIPOptSuite 7.0.0\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\Hostx86\x64;

Please let me know if you need any further information. Thanks a bunch! Best regards, Kasper.

**Comment by mueldgog** [comment]
Good to see that you are already using SCIP 7! Anyway, the issue here is that the current master of PySCIPOpt is incompatible with SCIP 7. This will change today after we merged #359. For now, you can just use the `scip-7` branch.

**Comment by kasp9201** [comment]
Thanks a lot for your help, Mueldgog! Have a good day
