### ISSUE TITLE
SCIP v6.0.2 + Python 3.6 works. SCIP 7.0.0 + whatever Python version doesn't

### ISSUE THREAD

**Issue by georgeRIGHT** [SCIP-Interfaces/PySCIPOpt#361]
As I have written in the title, 
a. SCIP v6.0.2 + Python 3.6 works, while 
b. SCIP 7.0.0 + whatever Python version doesn't. 
Since I have already correctly installed a., I am pretty sure I have correctly installed b., too (in different PC, both in Windows, same PATH variables, under ana(conda) environment).
In b. case I cannot even "pip install pyscipopt", while in a. case everything works fine. 
In b. case if I install SCIP 7.0.0 and work in a 3.6 environment, then "pip install pyscipopt" is installed but the .dll error appears (related to the Model to be imported).
Is it a known issue?

**Comment by fserra** [comment]
which dll error? Does SCIP standalone work?

**Comment by georgeRIGHT** [comment]
Thanks for the reply. Yes, SCIP standalone works correctly. The error:

 File "C:/Users/gt/PycharmProjects/testALLb/scipOptTest.py", line 10, in <module>
    from pyscipopt import Model
  File "C:\Users\gt\anaconda3\envs\testALLb\lib\site-packages\pyscipopt\__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model
ImportError: DLL load failed: The specified module could not be found.

**Comment by fserra** [comment]
Can you try again with pyscipopt version 3.0.0 which should be available in pypi shorty

**Comment by georgeRIGHT** [comment]
OK, I will as soon as it becomes available. Thank you.

**Comment by georgeRIGHT** [comment]
Works like a charm now. Thank you!!!
