### ISSUE TITLE
cvxpy Support fro SCIP

### ISSUE THREAD

**Issue by adishavit** [SCIP-Interfaces/PySCIPOpt#366]
Is there any chance we'll see SCIP integration into cvxpy?
See related issue [here](https://github.com/cvxgrp/cvxpy/issues/797).

**Comment by fserra** [comment]
Hi @adishavit 
I sadly don't have the time to integrate SCIP into cvxpy in the near future. But I am very happy to help with any issues.

**Comment by fserra** [comment]
So apparently https://github.com/cvxgrp/cvxpy/pull/1035 integrates scip to cvxpy via pyscipopt

**Comment by adishavit** [comment]
I saw. Awesome!

**Comment by fserra** [comment]
yes, thanks to @rimaddo
