### ISSUE TITLE
Branching on a linear form of variables

### ISSUE THREAD

**Issue by purin0604** [SCIP-Interfaces/PySCIPOpt#368]
Hi,
I am trying to implement a branching rule that considers a sum of variables as well as single variables. 
For example, if LP solutions are  x1=1 and x2= 0.2, I want to include external branching candidates as a sum of these two variables x1+x2=1.2  and let this candidate has a branching priority over single variables (x2) if it has fractional value.

From the SCIP documentation, I found Ryan/Foster branching rule from the binpacking example can be a useful reference to implement my branching rule. 

If it is relevant indeed, do you have the binpacking example in PySCIPOpt or similar branching rule example written in Python? 
If not, I am going to refer the example written in C and code in Python. In this case, I was wondering if all the functions used to implement Ryan/Foster branching rule are also applicable in PySCIPOpt. 

Thank you!

**Comment by fserra** [comment]
sorry for the late reply. we do not have Ryan Foster here, as far as I know, but (as you already found) we have a coloring example in some branch with a similar branching rule

So I am not sure how to achieve what you want.
I think you should write your own branching rule and there you can branch on the linear constraint x1 + x2. You can have a look at branch_multaggr.c in SCIP's source

**Comment by purin0604** [comment]
Thank you for the answer.
