### ISSUE TITLE
how to set the feasibility tolerance ,Primal Bound or infinity value

### ISSUE THREAD

**Issue by xqlaxlq** [SCIP-Interfaces/PySCIPOpt#369]
hi,
is there some way to self define the feasibility tolerance ,Primal Bound or infinity value, i have tried to modified it in "def.h" from SCIP and reinstall the " pyscipopt", it didn,t work.

**Comment by fserra** [comment]
you can set these parameters with
```
m = Model()
m.setParam("numerics/infinity", yournewinfinity)
m.setParam("numerics/feastol", yournewfeastol)
```
What do you mean by primal bound? if you want to only accept solution with better value than some number `N`, you can call `m.setObjlimit(N)`

**Comment by xqlaxlq** [comment]
thx for the quick reply，
some of my constraints have huge coefficient in denominator and very tiny coefficient in numerator , i am not sure, if it is the problem，that i got "presolving detected infeasibility" all the time.

by some other models, i can only get a infeasible solution, because of the violation of constraints.

**Comment by xqlaxlq** [comment]
> 
> 
> you can set these parameters with
> 
> ```
> m = Model()
> m.setParam("numerics/infinity", yournewinfinity)
> m.setParam("numerics/feastol", yournewfeastol)
> ```
> 
> What do you mean by primal bound? if you want to only accept solution with better value than some number `N`, you can call `m.setObjlimit(N)`

thx for the quick reply，
some of my constraints have huge coefficient in denominator and very tiny coefficient in numerator , i am not sure, if it is the problem，that i got "presolving detected infeasibility" all the time.

by some other models, i can only get a infeasible solution, because of the violation of constraints.
