### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hmwesigwa** [SCIP-Interfaces/PySCIPOpt#37]
I have followed the instructions of PySCIPOpt and SCIP. However, when I run
import pysciopt

I get the following error
'''
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyscipopt/__init__.py", line 3, in <module>
    from pyscipopt.scip      import Model
ImportError: /home/hayato/PySCIPOpt/lib/libscipopt.so: undefined symbol: rl_library_version'''

Has anyone come across this problem before?

**Comment by fserra** [comment]
can you compile SCIP with READLINE=false and try again?

**Comment by fserra** [comment]
I mean `make SHARED=true READLINE=false scipoptlib` in the scip opt suite directory

**Comment by hmwesigwa** [comment]
Thanks for the quick response. After making the change you suggested, I got the following error
'ImportError: /home/hayato/PySCIPOpt/lib/libscipopt.so: undefined symbol: __gmp_version'
I then run 'make SHARED=true READLINE=false GMP=false scipoptlib' and it is working. However, one of the tests is not working. Should all the test instances be working?
For test_alldiff.py I get
'''Traceback (most recent call last):
  File "test_alldiff.py", line 9, in <module>
    pytest.skip()
  File "/home/hayato/.local/lib/python2.7/site-packages/_pytest/runner.py", line 527, in skip
    raise Skipped(msg=msg)
builtins.Skipped: <Skipped instance>
'''

**Comment by fserra** [comment]
there seems to be a problem with skipping the test?? but anyway, that is not a problem of the interface, so don't worry.
Thanks!

**Comment by hmwesigwa** [comment]
Thanks!
