### ISSUE TITLE
Cannot import pyscipopt into python ( MacOS Catalina)

### ISSUE THREAD

**Issue by anqi9** [SCIP-Interfaces/PySCIPOpt#372]
I am trying to use pyscipopt on a Mac. I downloaded the SCIP Optimization Suite in my application folder and installed it by instruction. And I installed pyscipopt by typing: pip3 install pyscipopt in the terminal.
When I tried to import pyscipopt in Python, following messages came up:

from pyscipopt import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Library not loaded: libscip.7.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Reason: unsafe use of relative rpath libscip.7.0.dylib in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so with restricted binary

I have no idea how to fix this problem. Could you pls give me a little help

**Comment by mattmilten** [comment]
Did you specify the environment variable `SCIPOPTDIR` to point to the SCIP installation directory?

**Comment by anqi9** [comment]
yes, I tried export SCIPOPTDIR=/usr/local, where has a subdirectory lib and a subdirectory include. It didn't work. 
And I tried export SCIPOPTDIR=/Applications/scipoptsuite-7.0.0, where contains the source codes of SCIP Optimizer. The same problem occurred.

**Comment by AntoinePrv** [comment]
@anqi9 Not sure this is directly related but I'm also investigating installation of SCIP in MacOS. Could you give us the ouptut of the following commands:
```
otool -L /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
```
```
otool -l /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so | grep LC_RPATH -A2
```
```
otool -D /usr/local/lib/libscip.dylib
```

**Comment by anqi9** [comment]
The followings are the outputs:

Leung@LeungdeMBP ~ % **otool -L /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so**:
	libscip.7.0.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

Leung@LeungdeMBP ~ % **otool -l /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so | grep LC_RPATH -A2**
          cmd LC_RPATH
      cmdsize 104
         path /private/var/folders/2x/zklnbj6n7ss0ff0x6xqm3qlr0000gn/T/pip-install-9ysn85qh/pyscipopt/lib (offset 12)

**Leung@LeungdeMBP ~ % otool -D /usr/local/lib/libscip.dylib
/usr/local/lib/libscip.dylib:**
libscip.7.0.dylib



> @anqi9 Not sure this is directly related but I'm also investigating installation of SCIP in MacOS. Could you give us the ouptut of the following commands:
> 
> ```
> otool -L /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
> ```
> 
> ```
> otool -l /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so | grep LC_RPATH -A2
> ```
> 
> ```
> otool -D /usr/local/lib/libscip.dylib
> ```

**Comment by mattmilten** [comment]
Can you try specifying the environment variable `DYLD_LIBRARY_PATH` to point to the SCIP bin directory which contains `libscip.7.0.dylib`.
The error here seems to be that this library cannot be found because it is not in any of the default search locations.

**Comment by anqi9** [comment]
> Can you try specifying the environment variable `DYLD_LIBRARY_PATH` to point to the SCIP bin directory which contains `libscip.7.0.dylib`.
> The error here seems to be that this library cannot be found because it is not in any of the default search locations.

I have tried to set the environment variable as `export DYLD_LIBRARY_PATH=\usr\local\lib`, which contains `libscip.7.0.dylib` or `export DYLD_LIBRARY_PATH=/Applications/scipoptsuite-7.0.0/build/lib` which contains `libscip.7.0.dylib` as well. Neither of them works. 

I have checked on the internet, from one the pages said:" The behaviour of dylib may be controlled by environment variables, however If System Integrity Protection is enabled, environment variables are ignored when executing binaries protected by System Integrity Protection". I'm not so sure whether this issue is related to the relative path.

**Comment by Ethan-W** [comment]
I have encountered with this problem too. Methods to modify `DYLD_LIBRARY_PATH` are generally invalid due to Integrity Protection. I fixed this problem by changing the path` libscip.7.0.dylib ` in `../pyscipopt/scip.cpython-37m-darwin.so` to a more specific ` /Users/apple/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib`, which is the actual path of my dynamic library for scip. Then, all goes right.

first, this is error message:
```
ImportError: dlopen(/Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not loaded: libscip.7.0.dylib
  Referenced from: /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so
  Reason: image not found
```
you need use `otool -L /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so` to get a lock on our trouble:
`libscip.7.0.dylib (compatibility version 7.0.0, current version 7.0.0)`
ahh, a haunting ghost without specific path.

Then, use `sudo install_name_tool -change libscip.7.0.dylib /Users/apple/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so
 ` to fix it.

**Comment by anqi9** [comment]
> I have encountered with this problem too. Methods to modify `DYLD_LIBRARY_PATH` are generally invalid due to Integrity Protection. I fixed this problem by changing the path`libscip.7.0.dylib` in `../pyscipopt/scip.cpython-37m-darwin.so` to a more specific ` /Users/apple/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib`, which is the actual path of my dynamic library for scip. Then, all goes right.
> 
> first, this is error message:
> 
> ```
> ImportError: dlopen(/Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not loaded: libscip.7.0.dylib
>   Referenced from: /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so
>   Reason: image not found
> ```
> 
> you need use `otool -L /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so` to get a lock on our trouble:
> `libscip.7.0.dylib (compatibility version 7.0.0, current version 7.0.0)`
> ahh, a haunting ghost without specific path.
> 
> Then, use `sudo install_name_tool -change libscip.7.0.dylib /Users/apple/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib /Users/apple/anaconda3/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so ` to fix it.

Thank you for the solution, it finally works.
