### ISSUE TITLE
Is SCIP unable to read lp/mps files created by gurobi?

### ISSUE THREAD

**Issue by brucefeng10** [SCIP-Interfaces/PySCIPOpt#373]
I found that SCIP(using PySCIPOpt) is unable to read lp/mps files created by gurobi, while gurobi can read and optimize lp/mps model files created by SCIP.

**Comment by fserra** [comment]
how did you created the file with gurobi? and can you provide a (small) lp/mps model created by gurobi that SCIP can't read please

**Comment by mattmilten** [comment]
This could be an issue with special features not specified in the original LP format description. You should always use MPS format to properly store instances. These are usually better (machine-) readable and have higher numeric precision.

**Comment by brucefeng10** [comment]
> how did you created the file with gurobi? and can you provide a (small) lp/mps model created by gurobi that SCIP can't read please

I create lp format model in gurobipy with `mod.write('lpmodel.lp')`，the created "lpmodel.lp" file is as follows:

\ Model LP_test
\ LP format - for model browsing. Use MPS format to capture full model detail.
Maximize
  3 x[0] + 5 x[1]
Subject To
 R0: x[0] <= 4
 R1: x[0] + 2 x[1] <= 12
 R2: 3 x[0] + 2 x[1] <= 18
Bounds
End

And using the following code in pyscipopt to load the model, and an error occurs:
```
m=Model('xx')
m.readProblem('lpmodel.lp')
m.optimize()
```
it seems that SCIP can only recognize `x_0`, while Gurobi recognizes both `x_0` and `x[0]`

**Comment by fserra** [comment]
I am guessing that you are calling your variables `x[0]`, `x[1]` since Gurobi  https://www.gurobi.com/documentation/9.0/refman/lp_format.html recommends not to use `[ ]` in variable names. 
Well, in any case, it seems that the `[ ]` are used to denote the quadratic part of a function and that is the error I get with SCIP:
```
 ERROR: Syntax error in line 4 (']'): expected value or first quadratic variable. 
  input: 3 x[0] + 5 x[1]
```
Please rename your variables

**Comment by brucefeng10** [comment]
@fserra 
That works. Thank you!

**Comment by qsy-lnas** [comment]
Hi, I meet the same problem and i wonder how you work it out?

**Comment by mattmilten** [comment]
Sadly, MPS is not entirely standardized - most likely, your model is not a straightforward linear model and then there might be incompatibilities in how different solvers encode various MPS extensions.

**Comment by ArnaudDeza** [comment]
I just wanted to point this out for anyone else in the future as it worked for me. 

I was trying to solve a MILP problem using pyscipopt where the MILP problem was first modelled using gurobipy code to then write the problem to a mps file. I kept on running into the same error above "[reader_mps.c:399] ERROR: Syntax error in line 3 [reader_mps.c:3777] ERROR: Error <-2> in function call"

The one thing that fixed it was keeping the objective sense line of the mps file on two separate lines as shown below

i.e this mps file will cause an error in pyscipopt

NAME combinatorial_auction
OBJSENSE MAX
ROWS

i.e this mps file will not cause an error and work fine

NAME combinatorial_auction
OBJSENSE 
 MAX
ROWS
