### ISSUE TITLE
Pyscipopt license query 

### ISSUE THREAD

**Issue by Asimarif11** [SCIP-Interfaces/PySCIPOpt#374]
Hi
I saw on the license file that it falls under MIT and i can use it for commercial purposes but on the scip website it says i can only use it for non-commercial /academic purposes.
Could you kindly help me with my confusion? Because I was planning to use pyscipopt for commercial purposes. 
Regards 
Asim

**Comment by mattmilten** [comment]
Hi Asim,

The PySICPOpt code is free to use as specified in the MIT license. I am afraid it's not very useful if you cannot get a SCIP license, though. We could have opted for using the more restrictive ZIB license also for PySCIPOpt but didn't for multiple reasons.
Depending on your actual application, SCIP licenses are usually quite inexpensive - especially when compared to "proper" commercial codes outside of the academic world.
Please refer to https://scip.zib.de/index.php#license for hot to get a SCIP license.

I hope that helps.

cheers,
Matthias

**Comment by Asimarif11** [comment]
Hi
Thank you so much for your quick reply. Could you elaborate how its not useful without the scip license? I'm very new to programming in general actually so it takes a little while to grasp things. I just need to solve a mixed integer problem i tried to solve it and of course it works great. How would it not be useful if i use it commercially for example. The main question herr is would i be able to use pyscipopt for commercial purpose?
Thank you once again for your time.

**Comment by mattmilten** [comment]
Oh, I am sorry. I guess my wording wasn't really clear.
PySCIPOpt is merely a wrapper around SCIP. It cannot do anything on its own. You always need SCIP to actually transform constraints and variables into a MIP and solve it.
That being said, it's perfectly fine to also use it for commercial applications. SCIP is indeed a quite versatile and powerful solver. There are no restrictions whatsoever concerning the application. You just need to pay for a license if you want to use it for commercial purposes.
