### ISSUE TITLE
Branch and Price implementation with SCIP framework using PySCIPOpt

### ISSUE THREAD

**Issue by purin0604** [SCIP-Interfaces/PySCIPOpt#375]
Hi,
I am moving from CPLEX to SCIP to implement Branch and Price algorithm and have some basic conceptual questions about how to implement B&P with SCIP framework.

I have reviewed Backpacking example written in C and `test_coloring.py`/`test_pricer.py` examples written in Python.

1) Is it enough to add Pricer plugin to the model to solve it with Branch and Price method as in the `test_pricer.py` example? ( I changed the var type from continuous to integer and it seemed working well)    
I just wanted to make sure it is not a example of Price and branch( i.e., add all columns at the root node and solve it with B&B). In the example, it seems like that the pricer adds only one column with the most negative reduced cost at each node, rather than adding all the columns with negative reduced costs at each branched node. Should I manually add all the columns with negative reduced costs by repeating the subproblem iterations within the pricer plugin? or does SCIP framework allow to do it automatically at each node?     
 
2) In the "Backpacking" example, there is a function `addFixedVarsConss()`  to avoid to generate the same columns which are fixed to zero at the node followed by branching on some variables set to be zero.  I am wondering if this function is needed in any Branch and price implementation not to generate the duplicate columns. I think it should be, but I am confused because there is not a similar function in either `test_coloring.py`/`test_pricer.py` examples .     

3) While I tried to run `test_coloring.py`, the following error generated. 
_"ImportError: cannot import name 'Variable' from 'pyscipopt' "_
   It seemed to be resolved by adding a line `from pyscipopt.scip      import Variable`  to the `__init__.py` of the pyscipopt package.  I couldn't run the example anyway because the data info is not given in the code. Can you provide a data file for the example if you have any?

I guess some of my questions are absurd or too fundamental to answer, but it would really helpful for me to grasp a concept of SCIP framework for B&P method. 

Thank you!

**Comment by fserra** [comment]
Hi

1. SCIP should do this automatically. Each call to the pricer adds at most one variable, but the pricer can be called multiple times in a node. You can also add more than one variable (see pricer_binpacking.c on the binpacking example)
Yes it should be enough to add the pricer plugin, just like in the example. However, you might want to implement other callbacks of the pricer: see https://scip.zib.de/doc-7.0.0/html/PRICER.php

2. I am not really an expert on branch and price, I am not 100% sure if such a function is needed in any branch and price implementation, but I think it is a general issue to handle correctly the pricing inside the tree. However, in the coloring example, I think this also happens. It is not as explicit as calling `addFixedVarsConss`, but when the branching occurs, the underlying graph representing the instance is modified and then the pricing problem is build upon the modified graph.
Regarding the test, the master problem there is continuous, so it is just solving an LP with pricing, no branching involved.

3. I think the coloring test reads the files found in `scip/applications/Coloring/data` (this is the C source code of scip). Did you manage to run the coloring test with pyscipopt's master or you are running it on the `use-probdata-to-store-model` branch?


You can read more about SCIP's branch and price in the FAQ (in case you haven't) https://scip.zib.de/doc-7.0.0/html/FAQ.php

**Comment by purin0604** [comment]
I would like to limit the number of newly generated columns at each node (which means I want to have the limit on calling Pricer in a node.) and force to branch and explore the children node once the number of new columns hits some level.  

1) How can I access the number of columns of the parents' node? I want to compare the number of columns between parent's node and the current node and terminate Pricer.
2) It seems like there is a similar function in test_coloring.py in the Pricer  "keep_on_pricing(self)". From the example, does the Pricer stops at the current node after returning False  ?
