### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by soumyamittal** [SCIP-Interfaces/PySCIPOpt#38]
This may be a trivial error but I use conda_setup.py to install scip and I get an ImportError.
`File "pyscipopt/__init__.py", line 3,`
     `from pyscipopt.scip import Model`
`Import Error: No module named scip`

**Comment by mattmilten** [comment]
Was the installation completed successfully or did this error happen during installation? You might try installing with the `setup.py` and your own installation of the SCIP Opt Suite.

**Comment by soumyamittal** [comment]
Same error with setup.py. And yes, I have compiled Opt Suite on my own. There were no  errors then. I had run 'make tests' to verify that.

**Comment by mattmilten** [comment]
So, was the PySCIPOpt installation successful then? If not could you please paste the entire output including the command you used?

If it was successful and you got the error within Python trying to use PySCIPOpt, could you please make sure that you don't run it from within the PySCIPOpt main directory?

**Comment by soumyamittal** [comment]
Yes the PySCIPOpt is successful. 
There are no files created in the `bin/` folder after python installation. Only `Multidict` and `__init__` are present in the `lib/` directory.

**Comment by mattmilten** [comment]
This makes no sense. `lib` is supposed to be a symbolic link to the `lib` directory of the SCIP Opt Suite 3.2.1 and `include` a link to the `scip-3.2.1/src` directory.

There won't be a `bin` directory because there is no executable that gets created. There will be a `build` directory that contains the compiled cython library for PySCIPOpt that is then used from within Python.

**Comment by mattmilten** [comment]
Sooo,... did it work then?

**Comment by soumyamittal** [comment]
No, I am directly using the Opt Suite for now.

**Comment by alakin4** [comment]
For later users with a similar issue, I will state for the record that a system restart (especially on Windows) is necessary. This also worked in this [issue #282 ](https://github.com/SCIP-Interfaces/PySCIPOpt/issues/272).
