### ISSUE TITLE
How to access all the branched vars in the parents node (Node data attribute accessibility)

### ISSUE THREAD

**Issue by purin0604** [SCIP-Interfaces/PySCIPOpt#382]
Hi, 

I would like to change my sub-problem in a Pricer dynamically according to all the branching variables until the node created.
To achieve this, I need to access not only the branching var of the direct parent node, but those of all above nodes. 
How would I relay the branching variable data to all the leaves?   

I tried to store the branching var data into a node data attribute and relay it to its leaves, but it seems like .getCurrentNode() creates a new node instead of accessing existing nodes which contains some information in it's data attribute. (I think this issue was discussed in  #270  )

The following is a part of my code in the branchexeclp function.

```
        down_node, _, up_node = self.model.branchVar(self.var_e[bestcandidate])

        down_node.data = {}
        up_node.data = {}
        curr_node = self.model.getCurrentNode()
        print("curr_node:",curr_node.getNumber(),"down_node:",down_node.getNumber(),"up_node:",up_node.getNumber())
        if curr_node.getNumber() > 1:
            print("curr_node.data",curr_node.data)
        try:
            down_node.data['e_down'] = curr_node.data['e_down'] + [self.var_e[bestcandidate]]
            up_node.data['e_up'] = curr_node.data['e_up'] + [self.var_e[bestcandidate]]
        except:
            down_node.data['e_down'] = [self.var_e[bestcandidate]]
            up_node.data['e_up'] = [self.var_e[bestcandidate]]

        print("# down_node.data", down_node.data)
        print("# up_node.data", up_node.data)
        print("-------------------------------------------------------------------------------------------------------")
```

And the output is as follows. 

```
OUT  branchexeclp
IN  branchexeclp
var_e: e(1,8,67), var_e_val: 0.406076
curr_node: 2 down_node: 4 up_node: 5
curr_node.data None
# down_node.data {'e_down': [e(1,8,67)]}
# up_node.data {'e_up': [e(1,8,67)]}
-------------------------------------------------------------------------------------------------------
OUT  branchexeclp
IN  branchexeclp
var_e: e(1,8,7), var_e_val: 0.389379
curr_node: 5 down_node: 6 up_node: 7
curr_node.data None                   # Expects curr_node.data  {'e_up': [e(1,8,67)]} 
# down_node.data {'e_down': [e(1,8,7)]}
# up_node.data {'e_up': [e(1,8,7)]}
-------------------------------------------------------------------------------------------------------
```

I expected the  curr_node.data = {'e_up': [e(1,8,67)]} in the second interation instead of None. 
Storing all the information in the Model.data attribute would be the only solution for now? 
Would there be more clever way to do what I want? ( Accessing to all branched variables in the ancestors) 

I appreciate all your help :)

**Comment by fserra** [comment]
Yes, you cannot store information in a Node object because every time you ask for a node, a new Node object is created, as explained in  #270 
The same solution should work. Either create a constraint attached to the node or store them in model data.

**Comment by purin0604** [comment]
Thank you for the confirmation. I resolved the problem by storing data in model data.
