### ISSUE TITLE
division in objective: given coefficients are neither Expr or number but ProdExpr

### ISSUE THREAD

**Issue by cnglen** [SCIP-Interfaces/PySCIPOpt#387]
How to add objective which including division expression, such as:

a=model.addVar("a")
b=model.addVar("b")
c=model.addVar("c")

In [354]: model.setObjective((a+b)/c)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-354-e958238996b9> in <module>
----> 1 model.setObjective((a+b)/c)

src/pyscipopt/scip.pyx in pyscipopt.scip.Model.setObjective()

AssertionError: given coefficients are neither Expr or number but ProdExpr

**Comment by fserra** [comment]
sorry, that is a bad error message. PySCIPOpt doesn't allow for nonlinear objectives. So if you want to minimize `(a + b )/c` you should introduce a new variable, `t`, add a constraint `(a + b )/c <=t` and set as objective function just `t`.

**Comment by cnglen** [comment]
Thanks.
