### ISSUE TITLE
Count solutions

### ISSUE THREAD

**Issue by marcovc** [SCIP-Interfaces/PySCIPOpt#390]
I think there might be two issues with this code:

https://github.com/SCIP-Interfaces/PySCIPOpt/blob/f29d2cc0e244065bf6e012b47157e1865651207b/src/pyscipopt/scip.pyx#L4459-L4471 

In the "count()" function, isn't there a "return" missing?

And in the "getNCountedSols" function, shouldn't SCIPgetNCountedSols be wrapped with the PY_SCIP_CALL macro like the others?

Thanks
Marco

**Comment by fserra** [comment]
`SCIPcount` runs SCIP and counts the solutions, that's all it does. Then you can ask for some information to SCIP. It is like `optimize` that just optimizes.

Many of the SCIP functions return a `SCIP_RETCODE`. This is used to signal whether everything is alright or if there is a problem and which. The macro is there to process the `SCIP_RETCODE` (you can see the definition of the `PY_SCIP_CALL` above in the same file.
However, some other functions do not return a `SCIP_RETCODE`, for example, getter functions. This is one of them, that is just getting the number of solutions from where ever it is stored.

Does this answer your question?

**Comment by marcovc** [comment]
Thanks, it does. I was hopping that could be the reason why I getCountedNSols() return 0 right after optimize() returns one solution, but I guess not.

Thank you

**Comment by fserra** [comment]
if you want to get the number of stored solutions found during a call to `optimize` you should get the length of the array returned by `getSols`
