### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by purin0604** [SCIP-Interfaces/PySCIPOpt#392]
Hi,

I have implemented Branch and Price algorithm with own branching rules and it was running well without any errors.

I wanted to add one more branching rule and it needs to add constraints at node locally, so I have created a constraint handler. After including the constraint handler, the code finished abnormally with error msg : "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

I am using SCIPoptsuit 7.0 with cpx solver and pySCIPopt 3.0 on ubuntu  20.04

The following is a part of my codes related to the constraint handler.

```
## main.py
scip = Model("model")
...  ( skip codes for adding variables and constraints of the master problem )

# Store data to the model
scip.data["var"] = var
scip.data["pattern"] = pattern

#Add new branching rule 
newRule= pairBranch(scip, scip.data["var"])
scip.includeBranchrule(newRule, "pair branch", "Branching on pair elements of pattern variables that has fractional LP solution ",  priority=60000, maxdepth=10000, maxbounddist=1)
#Add constraint handler 
conshdlr = pairConshdlr(scip)
scip.data["conshdlr"] = conshdlr
scip.includeConshdlr(conshdlr, "Constraints by pairs", "restrict variable values depending on pair branches", chckpriority=100, propfreq=1)
scip.optimize()
```
```

## branching_rules.py
class pairBranch(Branchrule):
    def __init__(self, model, var):
        self.model = model
        self.var = var
    def branchexeclp(self, allowaddcons):
        (skip codes for selecting pairs to branch on)
       [i1,j1] = pair1
       [i2,j2] = pair2
        same_node = self.model.createChild(0.0, self.model.getLPObjVal())
        diff_node = self.model.createChild(0.0, self.model.getLPObjVal())

        conshdlr = self.model.data["conshdlr"]

        conssame = conshdlr.createCons("pair_same", [i1,j1], [i2,j2], "same",same_node.getNumber())
        self.model.addConsNode(same_node, conssame)

        consdiff = conshdlr.createCons("pair_same", [i1,j1], [i2,j2], "diff", diff_node.getNumber())
        self.model.addConsNode(diff_node, consdiff)

        return {"result": SCIP_RESULT.BRANCHED}

class pairConshdlr(Conshdlr):
    def __init__(self, model): 
        self.model = model

    def createCons(self, name, pair1, pair2, type, curr_node_id):
        cons = self.model.createCons(self, name, stickingatnode=True)
        data = {}
        data["curr_node"] = curr_node_id
        data["pair1"] = pair1
        data["pair2"] = pair2
        data["type"] = type
        data["pettern"] = self.model.data["pattern"]
       # Had to store the constraints data to model.data.
        self.model.data["pairCons"][curr_node_id] = data
        return cons

    def consprop(self, constraints, nusefulconss, nmarkedconss, proptiming):
        consdata = self.model.data["pairCons"][self.model.getCurrentNode().getNumber()]
        pair1 = consdata["pair1"]
        pair2 = consdata["pair2"]
        pattern = consdata["pattern"]

        if consdata["type"] == "diff":
           for var in self.model.data["var"]:
                if pattern[var][pair1] == pattern[var][pair2]
                   self.model.chgVarUb(var, 0.0)

        if consdata["type"] == "same":
           for var in self.model.data["var"]:
                if pattern[var][pair1] != pattern[var][pair2]
                   self.model.chgVarUb(var, 0.0)

        return {"result": SCIP_RESULT.DIDNOTFIND}

    # fundamental callbacks 
    def consenfolp(self, constraints, nusefulconss, solinfeasible):
        return {"result": SCIP_RESULT.FEASIBLE}
    def conscheck(self, constraints, solution, checkintegrality, checklprows, printreason):
        return {"result": SCIP_RESULT.FEASIBLE}
    def conslock(self, constraint, nlockspos, nlocksneg):
        return {"result": SCIP_RESULT.FEASIBLE}

```

**Comment by fserra** [comment]
can you compile to a SCIP in debug mode? There is probably an assert failing before the segmentation fault.

**Comment by purin0604** [comment]
Okay. 
I need to re-install PySCIPOpt it with debug option and maybe also need to build debug library of SCIP. I will update it with the debug results.

By the way, I wonder if I use correct syntax in the code, such as return codes or callback functions in the constraint handler,  add constraints to a node locally in the branching rule.

**Comment by fserra** [comment]
mmm, so from a quick look at the code:

1. `conslock` doesn't need tor return a dictionary. I guess you can just write `pass`. More importantly (and maybe this can cause a segfault(?)), the signature of the function is:
```
def conslock(self, constraint, locktype, nlockspos, nlocksneg):
```
so the `locktype` is missing.

1. Likewise, the signature of `conscheck` is 
```
def conscheck(self, constraints, solution, checkintegrality, checklprows, printreason, completely):
```
so `completely` is missing.

1. Does it make sense to always change the ub of the variables to 0?

what is `pattern` assigned to in consprop?

I don't see anything... let us see what the output while running in debug mode is. Anyway, it is always a good idea to develop in debug mode.

**Comment by purin0604** [comment]
Correction on the first two didn't solve the problem. Sorry, I fixed the typo in the code. `pattern` data is stored in model.data. 

Well, I recomplied SCIP in debug mode & installed pyscipopt with debug option. But there is no additional debug msg, but creates the same type of error "Segmentation fault (core dumped)".

Should I add anything to the code to activate debug msg? Or does it mean I didn't successfully compile it to a debug mode?

**Comment by fserra** [comment]
you can call model.printVersion or something like that. This prints some information about SCIP, in particular, whether it is debug in debug mode. can you paste the output here?

**Comment by purin0604** [comment]
Thank you. Now it runs in debug mode and it found the following assertion error at the root node while adding cuts, where it didn't make errors in the release mode. 

python3: /opt/scipoptsuite-7.0.0/scip/src/scip/cuts.c:3856: cutsSubstituteMIR: Assertion `!SCIPisZero(scip, weights[i])' failed.

**Comment by fserra** [comment]
mmm that is weird. I don't think both error are related.
Can you share your code with me? Otherwise you can try to run with gdb and see if that throws any more info...

**Comment by purin0604** [comment]
I can share the code with you. Which email address do you prefer?

**Comment by fserra** [comment]
my zib address please

**Comment by purin0604** [comment]
I sent an email on Jun 25th to your zib address with subject "Related to PySCIPOpt issue #392 , Code for debugging "  Wanted to ask if you received it well.

**Comment by fserra** [comment]
I have no idea what is going on. A couple of things:
1. You should use `getDualsolLinear` instead of `getDualMultiplier`
2. You have somewhere `scip.setRealParam("numerics/epsilon", integer_tolerance)`. Do you really want to change what SCIP considers to be 0, or you want to set the feasibility tolerance?
To change the feasibility tolerance use `scip.setRealParam("numerics/feastol", integer_tolerance)`.
After changing this, the assert 
```
cuts.c:3856: cutsSubstituteMIR: Assertion `!SCIPisZero(scip, weights[i])' failed.
```
 is gone.

Still the segfault appears. From googling a bit this error seems to be related to some garbage collection stuff. So what I did was to disable garbage collection:
I added `import gc` in BP_main and `gc.disable()` at the beginning of the main function.
Then the assert pops again, but the backtrace seems to be different.

Sadly, I don't really know how to continue debugging, but the output of your debugger seems to be better than gdb, so maybe you can have a look again after disabling garbage collection?

**Comment by purin0604** [comment]
Hi Fssera,
Thank you for the comment. I was working on the different part of the project and recently had time to look into it.

For the `scip.setRealParam("numerics/epsilon", integer_tolerance)` , I meant to use relaxed tolerance for the integer solution such that 0.999 could be considered as integer solution. But it is not really necessary.

I tried many different things but it still raises an segmentation fault error. 
It comes from using 'addConsNode()' in a branchrule module.   
 'addConsNode()' defined as follows in the `scip.pyx` file.
```
    def addConsNode(self, Node node, Constraint cons, Node validnode=None):
        """Add a constraint to the given node

        :param Node node: node to add the constraint to
        :param Constraint cons: constraint to add
        :param Node validnode: more global node where cons is also valid

        """
        if isinstance(validnode, Node):
            PY_SCIP_CALL(SCIPaddConsNode(self._scip, node.scip_node, cons.scip_cons, validnode.scip_node))
        else:
            PY_SCIP_CALL(SCIPaddConsNode(self._scip, node.scip_node, cons.scip_cons, NULL))
```

I wonder if the function missed something like `PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons))` because other functions for adding constraints include it and the binpacking example written in C code  (branch_ryanfoster.c) also have code lines to release constraints. 
I was trying to edit the `scip.pyx` file, but I am having trouble with installing pyscipopt in editable debugging version. 

Could you check if the current `addConsNode()` works well using a very simple example? 
I think this could also answer the issue #395

**Comment by Steve8881** [comment]
Hi purin0604,

I do not think releasing the constraint object helps. Actually, I tried and got `Assertion failed: (cons != NULL), function SCIPconsGetName`.

Have you solved the problem that adding branching constraints to nodes? 

Steve
