### ISSUE TITLE
hash(Constraint) changes

### ISSUE THREAD

**Issue by marcovc** [SCIP-Interfaces/PySCIPOpt#393]
Hi,

It seems the __hash__ of Constraint objects change after solving:

```python3
>>> m = pyscipopt.Model()
>>> x = m.addVar('x','BINARY')
>>> c = m.addCons(x==1)
>>> [hash(c) for c in m.getConss()]
[40393272]
>>> m.optimize()
...
>>> [hash(c) for c in m.getConss()]
[40393608]
```

Is there any way to avoid this? Can the same happen to variables?

Thanks!
Marco

**Comment by fserra** [comment]
SCIP copies the problem before solving, to manipulate without affecting the original formulation.
Thus, at the beginning, the function getConss access the original constraint.
However, after you solve, `getConss` access the so called transformed constraint.
In SCIP there is a function to get the original constraint, but it is not in the interface yet. If you need it you can try to add it (`SCIPgetOrigConss` defined in `scip_prob.h`)

The same will not happen with variables.

**Comment by marcovc** [comment]
Thanks for the explanation! Closing.
