### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/PySCIPOpt#4]
We need a licence for the code and the examples.

[SCIP](http://scip.zib.de/#license) itself uses the [ZIB Academic Licence](http://scip.zib.de/academic.txt), but [GCG](http://www.or.rwth-aachen.de/gcg/#license) (based on SCIP) is released with the LGPL license.

**Comment by leethargo** [comment]
Since the Cython code includes (significant) parts of the SCIP headers, I guess the "copyleft" part of the ZIB academic license applies. I was just rereading it, and the most difficult part seems to be the "tracking of users" in the distribution part.

**Comment by xmunoz** [comment]
Looks like @mattmilten asked this question a while ago on [the mailing list](https://groups.google.com/a/continuum.io/forum/m/#!msg/conda/FvDDzLHvGQ8/gDJF4eu9AQAJ), and got a lukewarm response. I can try to upload [sodapy](https://github.com/xmunoz/sodapy) to conda and see if there are more statistics available to the administrator. Will report back.

**Comment by leethargo** [comment]
The question of distribution (in particular precompiled packages with conda) is still open.
