### ISSUE TITLE
Installation with pip on 64-bit Win10 with Python 2.7  doesn't work

### ISSUE THREAD

**Issue by qyyparadox** [SCIP-Interfaces/PySCIPOpt#404]
> I tried installing pyscipopt and got the following erorr message:

`(base) C:\Users\qyy>set SCIPOPTDIR="C:\Program Files\SCIPOptSuite 7.0.1"`
`(base) C:\Users\qyy>pip install pyscipopt`

`C:\Program Files\SCIPOptSuite 7.0.1\include\scip/def.h(33) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory`

**Comment by mattmilten** [comment]
You are using an outdated Python version. Please upgrade to Python 3 and you should not get this error anymore.

**Comment by qyyparadox** [comment]
yes, I just used Anaconda 3 to pip pyscipopt, and no error any more
