### ISSUE TITLE
Non Linear expressions

### ISSUE THREAD

**Issue by ycouble** [SCIP-Interfaces/PySCIPOpt#41]
Hi,

First of all, thanks for the interface, coming from gurobipy, the transition was seamless.

However, I am looking to use non-linear expression, namely a log in the objective function. Looking inside the code and documentation, I couldn't find the correct way to do it.

Is it implemented yet?

Best,
Yoann

**Comment by fserra** [comment]
Hey Yoann

I am sorry that currently the only nonlinearities that we can handle are
polynomials.

We want to extend it of course, but I think we first have to decide on the
data structure for general expressions.

**Comment by ycouble** [comment]
Ok, thanks for the update.

**Comment by leethargo** [comment]
Besides the internal datastructure, it's also not clear what the usage will look like.
For polynomial expressions, we can use operator overloading on `*` and `+` to hijack the expression parsing in Python. But I wouldn't know how catch a call to `log(x)` where `x` is a `Expr` (there's no `log` function in the global namespace in Python, only `math.log`). I guess we would have to provide functions (and types) that user would need to import, as in
```
from pyscipopt import log
cons = (log(x) == 3)
```

**Comment by ycouble** [comment]
For the objective function, would it be possible to simply pass a user-defined function as argument of the setObjective call ? Something like:

    def eval_f(X):
        return sum(x for x in X)

**Comment by leethargo** [comment]
I don't think we can support general functions. For your example, I could imagine the following:
```
model.setObjective(sum(pyscipopt.log(x) for x in X))
```

**Comment by tarun018** [comment]
Hello !

Is there any update on this ? I need to use a log objective as part of my model.

Thanks.

**Comment by fserra** [comment]
Hi @tarun018 

I am sorry to say that here has been 0 activity in this issue. 
I hope I have some time to start working on this, but not before the next couple of weeks

**Comment by fserra** [comment]
general nonlinear functions are implemented now!
