### ISSUE TITLE
DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by CallendeING** [SCIP-Interfaces/PySCIPOpt#412]
I recently install the pyscipopt library and i can't pass this error "DLL load failed: The specified module could not be found" (does't specify the DLL), I have the "...\bin" PATH and the SCIPOPTDIR variable, I saw all the related issues and i can't solve it. 
Beforehand sorry for my English.

**Comment by mattmilten** [comment]
Hi! Can you give us some more information on the error and what you did to
provoke it? What is your python version? Are you using anaconda?

**Comment by CallendeING** [comment]
I get the error while i import the library as the image shows.
![image](https://user-images.githubusercontent.com/23286646/90667093-53bbce00-e21c-11ea-9ad3-b53dc750fa88.png)
I'm using python 3.7, SCIPOptSuite 6.0.2 and Visual Studio Community 2019 and for the installation I follow the steps in the next order:
- Install SCIP 6.0.2
- Install C++ package for visual studio
- Install Visual Studio Community
- Set enviroment variable
- Install pip
- Install Cython
- Install pyscipopt
- Then I create a proyect in VS and create an enviroment where I use all this libraries

**Comment by CallendeING** [comment]
I just found the error, and it's the compatibility between the versions, previously i was up to date with the versions, but now I need to use an older one.
![image](https://user-images.githubusercontent.com/23286646/90669137-258bbd80-e21f-11ea-8ef5-f5c4bde19d70.png)
I explain it in case someone else has the same problem.
