### ISSUE TITLE
A branch-and-price question

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [SCIP-Interfaces/PySCIPOpt#420]
I am wondering if I could implement a branch-and-price through PySCIPOpt. If so, do you have any suggested model I could possibly study? Also, I just made a simple code for testing my model. But, I cannot see the output as the algorithm proceeds such as Outputflag in Gurobi. If you know how to turn it on, could you please let me know?

**Comment by mattmilten** [comment]
One possible starting point for implementing a pricer is [tests/test_pricer.py](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/tests/test_pricer.py).
Concerning the output issue: make sure to check the terminal for the missing output. I assume that you're using a Jupyter notebook which doesn't show the SCIP output by default. You would need to use `model.redirectOutput()` to see the output in a notebook cell.

**Comment by IngyuLeeGitHub** [comment]
Thank you for your prompt reply!!
