### ISSUE TITLE
Install PySCIPOpt 6.0.2 using pip on Windows 10 64bit with Python 3.6.6

### ISSUE THREAD

**Issue by ScottStetkiewicz** [SCIP-Interfaces/PySCIPOpt#424]
I know this is a common issue, and I've been through #110 , #258 , #249 and #272 all to no avail. Working a project that requires the listed package versions here for compatibility purposes.

Following on from the [instructions](http://scip-interfaces.github.io/PySCIPOpt/docs/html/md_INSTALL.html), I've:

1. Created a new Anaconda environment `conda create -n scip python=3.6.6 pip=19.3.1 `
2. Downloaded PySCIPOpt 6.0.2.exe, extracted and installed to `C:\Program Files\SCIPOptSuite 6.0.2`
3. Added `C:\Program Files\SCIPOptSuite 6.0.2\bin` to my environment variables PATH

Output of `echo %PATH%`:

`C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Users\Scott\AppData\Local\Microsoft\WindowsApps;C:\Users\Scott\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\SCIPOptSuite 6.0.2\bin;`

4. Created a new environment variable `SCIPOPTDIR` set to `C:\Program Files\SCIPOptSuite 6.0.2`
5. Run `CMD` to verify `scip`can be run from the terminal [**output successful**]
6. Within the new conda environment (scip) run `scip` from the conda terminal to verify it can be run here [**output successful**]
7. Within the new conda environment (scip) run `pip install pyscipopt` [**install successful**]

Output of `import pyscipopt` within conda "scip" environment (using python 3.6.6):

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Scott\Anaconda3\envs\scip\lib\site-packages\pyscipopt\__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: DLL load failed: The specified module could not be found.`
 
Attempted fixes:

1. I've gone ahead and tried restarting my computer to see if this fixes things as suggested [here](https://github.com/SCIP-Interfaces/PySCIPOpt/issues/38#issuecomment-498059108), with no luck. 
2. I've cleaned out `C:\Users\Scott\Anaconda3\Lib\site-packages` to make sure there aren't any lingering old files (I've tried installing this several times now, as it's vital to my project), as well as wiping old conda environments from `C:\Users\Scott\Anaconda3\envs`
3. Installing on 3 different computers, with the exact same `ImportError: DLL load failed: The specified module could not be found.` message on each device

I'm at a loss here, but it seems that if this process isn't working on 3 different computers then maybe these steps are somehow incorrect?

**Comment by mattmilten** [comment]
Thank you for the very detailed error report! It seems you did (almost) everything right.
Could you please install the latest version of the SCIP Optimization Suite? pip install is always going to choose the latest available version of PySCIPOpt and that is only compatible with the latest SCIPOpt version. You can find the compatibility table in the [INSTALL.md](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.md).

I hope that fixes the issue.

Cheers,
Matthias

**Comment by ScottStetkiewicz** [comment]
That did the trick! Thanks for the help Matthias
