### ISSUE TITLE
ERROR: cannot add a coefficient to the locked unmodifiable row

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [SCIP-Interfaces/PySCIPOpt#425]
I am making a branch-and-price model. 
In CutPricer, I was trying to add new variables into the constraints and encountered "ERROR: cannot add a coefficient to the locked unmodifiable row".

Could you kindly explain why this happened and how to fix this issue? 

Appreciate your help in advance.

**Comment by fserra** [comment]
This happens because, as the error says, you cannot add a coefficient (a variable) to a constraint that cannot be modified (unmodifiable).

To fix it, you need to tell pyscipopt that the constraint is `modifiable` when you add it.
```
    def addCons(self, cons, name='', initial=True, separate=True,
                enforce=True, check=True, propagate=True, local=False,
                modifiable=False, dynamic=False, removable=False,
                stickingatnode=False):
```
So you do: `model.addCons(bla, bla, bla, modifiable = True)`

**Comment by IngyuLeeGitHub** [comment]
Thank you. Resolved !!
