### ISSUE TITLE
branch-and-price verification

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [SCIP-Interfaces/PySCIPOpt#426]
I am struggling with the verification of my branch-and-price model. 

I want to see a final mathematical formulation after adding all the required columns.  
But, when I used "writeProblem( )", it only gave me the formulation with the initial predefined columns.
**I wonder if there is any way to see the final formulation with added columns and also check their values using "getVal( )"?** 
I would also like to get your advice on the verification of the branch-and-price model if you know other ways. 

**Another question is if there is a way to call columns or variables by name like getConstrByName in Gurobi.**

Lastly, I would like to ask about the general logic in PySCIPOpt. 
**When is the pricer function executed? In other words, when does the algorithm add columns?**

Your supports have helped me out a lot. Appreciate it!!

**Comment by fserra** [comment]
Hi

You can try calling `writeProblem(trans=True)`.
You can get all variables with `getVars` (also with `transformed=True`). Then you should be able to access their values with `getVal()`

Regarding verification, I am not sure. The first things that come to mind are to
1. visualize the solution somehow. This obviously depends on the problem that you are trying to solve.
2. try with small enough problems for which you can model completely (i.e. without the need for pricing in variables). Then solve the complete model and your current model and check whether the sols coincide

In SCIP you can actually find a variable by name with `SCIPfindVar`. However, that function is not interfaced yet. It shouldn't be too hard to extend the interface to include this function. You can have a look here https://github.com/SCIP-Interfaces/PySCIPOpt#extending-the-interface

It basically works by solving the LP and then calling the pricers, solving the LP again and repeat.

As PySCIPOpt is a wrapper for SCIP, all the logic is actually from SCIP. 
You can learn more about SCIP in general from this video https://www.youtube.com/watch?v=Rzk5GfUaLiY&t=1311s
and the other videos in the channel (although, sadly, the video about branch and price is not available)
More information about using SCIP for column generation can be found here:
https://www.scipopt.org/doc/html/FAQ.php#faq_specificquestionsaboutcolumngenerationandbranchandpricewithscip

**Comment by IngyuLeeGitHub** [comment]
Thank you for your kind reply. 
I was able to call the problem formulation and variables with your help. 

I found that some binary variables give the lower and upper bound as 1, e.g.,   1 <= t_v_2 <= 1 and 1 <= v_14 <= 1.
It causes optimal solution discrepancy. I am wondering why this bound issue happens.

Could you also please explain pricedVar in addVar()?

**Comment by fserra** [comment]
I don't understand what the bound issue is.
when `pricedVar` is set to TRUE it informs SCIP that it can price that variable. But I have to say that I am a bit confused here. The equivalent function in SCIP is `SCIPaddPricedVar` however that function allows the user to set a score to the variable. In pyscipopt, we just set the score to 1.0 if `pricedVar` is true.
As far as I understand, SCIP can decide to price variables even if they were not added with `SCIPaddPricedVar`, so it might be that the purpose of `pricedVar` is not really to inform SCIP that it can price but to set the score for the pricing.

Maybe @stephenjmaher can confirm or clarify this better.

**Comment by stephenjmaher** [comment]
When the implementation of `pricedVar` was developed, it was assumed that the score was not regularly used in `SCIPaddPricedVar`. Also, `SCIPaddPricedVar` is always used when adding variables from the pricer. That is the purpose of having the `pricedVar` function.

It could be useful to include the option of adding a score. However, this is not totally necessary and at this stage not a high priority.

**Comment by IngyuLeeGitHub** [comment]
Thank you, guys. Your help has been really useful !!

Regards.

**Comment by pambus** [comment]
> Thank you for your kind reply.
> I was able to call the problem formulation and variables with your help.
> 
> I found that some binary variables give the lower and upper bound as 1, e.g., 1 <= t_v_2 <= 1 and 1 <= v_14 <= 1.
> It causes optimal solution discrepancy. I am wondering why this bound issue happens.
> 
> Could you also please explain pricedVar in addVar()?

Hi @IngyuLeeGitHub . Sorry to bother you, but could you solve the issue with the binary variables? I am having the same problem. Thank you in advance.
