### ISSUE TITLE
Problem with quicksum if the range is a variable

### ISSUE THREAD

**Issue by adhe-k** [SCIP-Interfaces/PySCIPOpt#438]
Hi,

I have this function as part of my constraint :
![image](https://user-images.githubusercontent.com/51048244/94549355-bf04b100-025a-11eb-8f87-9a994bff3f9a.png)
where D(j) is input data and P is a decision variable.

I wrote my constraint as follows :

def consFR(model, q, SS, SOT):
    wSOT = SOT/5
    P = L + wSOT 
    fl_P = int(np.floor(P))

    for t in Ts:
        Dr = quicksum(d for d in demand[t-1:min(t+fl_P-1,T)])
        if (t+fl_P-1)< T : Dr = Dr + (P-fl_P) * demand[t+fl_P-1]

And got an error : 
<ipython-input-13-71dcb4868e1a> in consFR(model, q, SS, SOT)
      2     wSOT = SOT/5
      3     P = L + wSOT
----> 4     fl_P = int(np.floor(P))
      5 
      6     for t in Ts:

TypeError: must be real number, not pyscipopt.scip.Expr

Would you like to help me to solve it?

Best,
Adhe

**Comment by adhe-k** [comment]
Hi again,

I change my code to avoid the floor function, but still have an error in quicksum because the range is a variable.

This is my code :
-------------
def consFR(model, q, SS, SOT):

    for t in Ts:
        Dr = quicksum(d for d in demand[t:min(t+L,T)])
        Dr = Dr + quicksum(d for d in demand_day[min((t+L),T)*5:min((t+L)*5+SOT,T*5)])
-------------

and I got an error : 
-------------
<ipython-input-7-c5212164973d> in consFR(model, q, SS, SOT)
      3     for t in Ts:
      4         Dr = quicksum(d for d in demand[t:min(t+L,T)])
----> 5         Dr = Dr + quicksum(d for d in demand_day[min((t+L),T)*5:min((t+L)*5+SOT,T*5)])
      6 
      7         #if (t+fl_P-1)< T : Dr = Dr + (P-fl_P) * demand[t+fl_P-1]

src\pyscipopt\expr.pxi in pyscipopt.scip.Expr.__richcmp__()

src\pyscipopt\expr.pxi in pyscipopt.scip._expr_richcmp()

NotImplementedError: 
-------------

Same error comes when I change quicksum with np.sum.
I think the problem is in the range which involve a decision variable SOT.

Do you have any suggestion to solve this problem?

Best,
Adhe

**Comment by adhe-k** [comment]
Hi @fserra,

Thank you very much for your answer.
Based on your experience, do you have any suggestion for me to make the constraint formula, which has a variable as the limit for a sum, run well using pyscipopt?
For example with some modifications or using another library?

Best,
Adhe

**Comment by fserra** [comment]
Are you asking me if there is a way of modelling directly just by writing the sum with the variable in the limit?
I don't know about any modelling language that would allow for this, but I am not knowledgable on the capabilities of modelling languages so I might be wrong. Maybe @svigerske can say something more.

**Comment by svigerske** [comment]
I could imagine that modeling languages for constraint programming might allow this, but that isn't really relevant here.
PySCIPOpt is for SCIP, so one might want to keep the capabilities of SCIP in mind. Even though there is a "C" in the name, there is nothing in SCIP these days to represent sums where the limits are variables. I doubt that there is an intention to implement some automated reformulation for this within PySCIPOpt, so it is up to the user to do that manually, that is, use a sum with largest possible limits and ensure that terms are 0 when necessary.

**Comment by adhe-k** [comment]
Thank you very much @fserra and @svigerske for answering my questions.
