### ISSUE TITLE
Problem to release variables for branch-and-price Graph Coloring

### ISSUE THREAD

**Issue by pchervi** [SCIP-Interfaces/PySCIPOpt#439]
Hi,

I have worked on a Python Graph coloring code initially proposed by the SCIP team, eventually getting a working version.
However I couldn’t manage to release variables as no ‘releaseVar()’ instruction exists on Pyscipopt, getting pestered by such warnings:

_WARNING: Transformed variable <t_Initial_Set_1> not released when freeing SCIP.
WARNING: Transformed variable <t_Initial_Set_0> not released when freeing SCIP.
WARNING: Original variable <Initial_Set_38> not released when freeing SCIP.
WARNING: Original variable <Initial_Set_37> not released when freeing SCIP, etc._

What would be the way to release variables in Python, or is there any specific recommendation to avoid such warnings? 

The code is available at https://github.com/pchervi/Graph-Coloring and these warnings can be reproduced with any graph proposed, even a simple 3-wheel graph.

Thank you for your help!

**Comment by fserra** [comment]
should be fixed with the associated PR.

However, then a problem with releasing the constraints appear. I will have a look at that later
