### ISSUE TITLE
variable step

### ISSUE THREAD

**Issue by ChingYoung** [SCIP-Interfaces/PySCIPOpt#444]
Hi everyone,
First of all, thank you very much for helping us with PySCIPOpt.

I want to set the step length of each change of a variable in the solution process.
For example, the variable 0<=a<=10, the step size is 3, the possible values of a are 0, 3, 6, 9, 10.
any way to solve this problem?

Thank you very much.

**Comment by fserra** [comment]
One option is to model that as `a = 3 x1 + 6 x2 + 9 x3 + 10 x4` each of the `x` variables being binary plus `x1 + x2 + x3 + x4 <= 1`

I do not know, however, if that is the best option.

**Comment by ChingYoung** [comment]
> One option is to model that as `a = 3 x1 + 6 x2 + 9 x3 + 10 x4` each of the `x` variables being binary plus `x1 + x2 + x3 + x4 <= 1`
> 
> I do not know, however, if that is the best option.

If the range of variables is large, this method is still very limited. @fserra

**Comment by fserra** [comment]
yes. so if you wouldn't have the 10 at the end you would be able to use `a = 3x` Maybe you can try with an indicator, `y = 1 -> a = 3x` and `z = 1 -> a = 10` and `z + y <= 1` Notice that an indicator constraint only accepts a `<=` constraint, so you probably need
```
y1 -> a <= 3x
y2 -> a >= 3x
z -> a >= 10

z + y1 <= 1
y1 == y2
```

**Comment by ChingYoung** [comment]
> yes. so if you wouldn't have the 10 at the end you would be able to use `a = 3x` Maybe you can try with an indicator, `y = 1 -> a = 3x` and `z = 1 -> a = 10` and `z + y <= 1` Notice that an indicator constraint only accepts a `<=` constraint, so you probably need
> 
> ```
> y1 -> a <= 3x
> y2 -> a >= 3x
> z -> a >= 10
> 
> z + y1 <= 1
> y1 == y2
> ```

Thank you very much for your reply, but this method is not suitable for my needs

**Comment by fserra** [comment]
ok sorry i couldn't help. I am going to close the issue, because anyway it is not related to pyscipopt
