### ISSUE TITLE
Branching rule

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [SCIP-Interfaces/PySCIPOpt#447]
Hi everyone,

I wonder what the default branching rule applied in PySCIPOpt such as depth-first search, best-first search, etc. 
I also want to know if I can change the rule. For instance, if the default option is the depth-first search, I want to try other rules like the best-first search to compare their performances.  

Thank you for your help in advance.

**Comment by mattmilten** [comment]
Please see the SCIP documentation for detailed information about branching rules and how to use them:
 - https://scipopt.org/doc/html/BRANCH.php
 - https://scipopt.org/doc/html/group__BRANCHINGRULES.php

Essentially, you need to specify the priority to activate a certain branching rule:

```
 branching rule       priority maxdepth maxbddist  description
 --------------       -------- -------- ---------  -----------
 relpscost               10000       -1    100.0%  reliability branching on pseudo cost values
 pscost                   2000       -1    100.0%  branching on pseudo cost values
 inference                1000       -1    100.0%  inference history branching
 mostinf                   100       -1    100.0%  most infeasible branching
 leastinf                   50       -1    100.0%  least infeasible branching
 distribution                0       -1    100.0%  branching rule based on variable influence on cumulative normal distribution of row activities
 fullstrong                  0       -1    100.0%  full strong branching
 cloud                       0       -1    100.0%  branching rule that considers several alternative LP optima
 lookahead                   0       -1    100.0%  full strong branching over multiple levels
 multaggr                    0       -1    100.0%  fullstrong branching on fractional and multi-aggregated variables
 allfullstrong           -1000       -1    100.0%  all variables full strong branching
 vanillafullstrong       -2000       -1    100.0%  vanilla full strong branching
 random                -100000       -1    100.0%  random variable branching
 nodereopt            -9000000       -1    100.0%  branching rule for node reoptimization
```

As you can see reliability branching using pseudo cost values is the default method.

**Comment by IngyuLeeGitHub** [comment]
Thank you for your prompt reply. 

I read the references that you provided!
However, it was difficult for me to understand because I am unfamiliar with SCIP.
I wonder if there are any reference PySCIPOpt (python) models that I could take a look into. 

Appreciate your continued assistance!

**Comment by mattmilten** [comment]
No, I don't think there is. You see, PySCIPOpt is little more than a wrapper around SCIP, making it easier to use. You are still using SCIP, just through Python and we actually try to map every SCIP functionality in PySCIPOpt - even the documentations are linked to show that you're mostly just executing a SCIP function when calling a PySCIPOpt method. This is also true for parameters and how the solver works in general.

If you don't want to make yourself a bit familiar with SCIP, you will have a hard time going forward with PySCIPOpt.

**Comment by fserra** [comment]
I had a quick look at the documentation and I didn't find easily a "how to change the default branching rule in SCIP", so maybe we should give a bit more detail.
But yes, as Matthias says, it is the priority of the branching rule which controls who is the default.

Say you want to change the priority of `cloud` branching to make it the default, then you have to do 
`
model.setParam("branching/cloud/priority", 10001)
`

**Comment by IngyuLeeGitHub** [comment]
Thank you all for your help. 

It was really helpful. It seems to work fine!
BTW, does 10001 mean anything in model.setParam("branching/cloud/priority", 10001)?

Thank you.

**Comment by fserra** [comment]
yes, it is the priority that you are setting `cloud` branching to. If you look at the table that Matthias posted you will see that `relpscost` has the largest priority:
```
branching rule       priority maxdepth maxbddist  description
--------------       -------- -------- ---------  -----------
relpscost               10000       -1    100.0%  reliability branching on pseudo cost values
```
since you want to make `cloud` branching the rule with largest priority its priority has to be larger than 10000. `10001` is the first such number.

**Comment by IngyuLeeGitHub** [comment]
That perfectly makes sense. Thank you for the clarification.
