### ISSUE TITLE
cutting planes

### ISSUE THREAD

**Issue by gsagnol** [SCIP-Interfaces/PySCIPOpt#45]
When I have a scip model that I have already solved,
if I add one additional constraint, such as e.g.
`self.scip_model.addCons(expression <= 0)`

(to make a cutting plane), I can't re-solve the problem:
```
/home/optimi/bzfsagno/python/lib/python2.7/site-packages/pyscipopt/scip.so in pyscipopt.scip.PY_SCIP_CALL (pyscipopt/scip.c:20408)()

Exception: SCIP: method cannot be called at this time in solution process!
```

I had a look at the example cutting_stock.py, but it seems that a function `relax()` is missing. 
I'm not 100% sure of what `relax()` must do, but in any case with the approach in this file it is 
**a different copy** of the scip model which is solved at each iteration. Would'nt it be possible to
just *re-solve* the same scip model without the need to create copies of it?

**Comment by fserra** [comment]
Hi Guillaume

This `relax` function doesn't exists in SCIP nor in PySCIPOpt. I think `relax` is gurobi thing.

Anyway, I would say that the proper way of handling this case, is to write a constraint handler which adds the constraints when needed. Maybe the best example we have available is `test_tsp.py` in the `tests` directory.

Would that make sense?

**Comment by gsagnol** [comment]
Thanks Felipe,
I had a look at `tsp.py` and found the solution. The trick was to call `freeTransform()`, which frees all solution process data, and makes it possible to add a cut.

Best !
