### ISSUE TITLE
Installation problems on Ubuntu 16

### ISSUE THREAD

**Issue by bhzunami** [SCIP-Interfaces/PySCIPOpt#48]
Hello

I tried to install the Python Interface but when I want to import a Model I get the following error:
`ImportError: /root/PySCIPOpt/lib/libscipopt.so: undefined symbol: rl_library_version
`

I build the scip installation in a Docker container:

```
# Install all packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential libgmp3-dev zlib1g-dev  libreadline-dev python3 cython3 libncurses5-dev git

# Extract the tgz from the SCIP Page to the folder /root/scipoptsuite-3.2.1
ADD scipoptsuite-3.2.1.tgz /root  

WORKDIR /root/scipoptsuite-3.2.1

# Use INSTALLDIR ../../ to install it in the /usr/local and not in the /root/scipoptsuite-3.2.1/usr/local
RUN make -j6 && make -j6 SHARED=true scipoptlib && make -j6 install INSTALLDIR="../../usr/local"

WORKDIR /root/
RUN git clone https://github.com/SCIP-Interfaces/PySCIPOpt.git

WORKDIR /root/PySCIPOpt
RUN env SCIPOPTDIR=/root/scipoptsuite-3.2.1 python3 setup.py install
```

The `make test` runs through and I can start enter the `scip` to start the interactive shell.

Also in the folder /root/scipoptsuite-3.2.1 there is the lib-folder with the `libscipopt.so` and the src-folder under scip-3.2.1/src/.

What I missed?

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
Cython version 0.23.4

**Comment by mattmilten** [comment]
There is a weird issue with the `readline` library. There seem to be incompatibilities between the Python version and the C version of the library. While the SCIP lib is built with the C version, the PySCIPOpt setup tries to link against the readline lib that comes with Python.

One fix might be to uninstall/remove the Python readline lib. You may be able to find this file by running `ldd scip.so`, where `scip.so` is the Cython generated library for PySCIPOpt.

**Comment by mattmilten** [comment]
Another fix that is a lot easier is to just compile the SCIP Opt Suite with the option "READLINE=false".

**Comment by bhzunami** [comment]
Thanks a lot.
I also had to add `GMP=false READLINE=false` but now it works.
