### ISSUE TITLE
create conda recipes

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/PySCIPOpt#5]
One for `scipopt.so` with headers(?) and one for `PySCIPOpt`.

**Comment by leethargo** [comment]
I created a recipe for `scipoptlib` in the conda branch.

**Comment by leethargo** [comment]
Apparently, `conda` does not mess with `LD_LIBRARY_PATH`: [http://conda.pydata.org/docs/building/shared-libraries.html#shared-libraries-in-linux-and-os-x](conda docs).

**Comment by leethargo** [comment]
I wonder why we link to that many libraries in the `setup.py`:

    libraries=['scipopt', 'readline', 'z', 'gmp', 'ncurses', 'm']

Obviously we need `scipopt` and apparently `m`, and I also see that `z` is useful (it's also included in the conda recipe for `scipoptlib`). However, `readline` and `ncurses` don't make sense to me, because the SCIP shell is not used in the Python wrapper. I'd also remove `gmp`, because I believe it's only needed for Zimpl. So I'd change it to `libraries=['m', 'scipopt', 'z']`

@mattmilten Do you agree?

**Comment by mattmilten** [comment]
ZIMPL is probably not needed - but maybe someone wants to read in  a `zpl` instance, so we should keep it. GMP is also used in SoPlex when doing exact LP solves. `readline` can be removed for sure. There had to be a reason why I added `ncurses` in the first place; I think ZIMPL needs it.

Ideally, the list of necessary libs would be automatically detected.

**Comment by leethargo** [comment]
I believe that `ncurses` is an implicit dependency of `readline` which was needed (at least within `conda`).

> GMP is also used in SoPlex when doing exact LP solves.
But doesn't that require different build flags for SoPlex? I'm not sure how one would activate this now.

> Ideally, the list of necessary libs would be automatically detected.
True, but I have no idea how this could be done, so for the first iteration I'll go for the minimal setup.

**Comment by mattmilten** [comment]
Yes, the minimal setup is a good idea. When users then want to compile using their own `scipoptlib` they might just specify some additional parameter, e.g. `EXTRA_LIBS=gmp`. Just like the `PREFIX` option.

**Comment by leethargo** [comment]
I merged the first set of recipes in #7.

I also built and uploaded the packages, so that I was able to run

    ~/conda/bin/conda create --name t3st --channel leethargo python pyscipopt

and then do

    $ source ~/conda/bin/activate t3st                                         
    discarding /home/bzfschwa/conda/bin from PATH
    prepending /home/bzfschwa/conda/envs/t3st/bin to PATH
    $ python
    Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pyscipopt
    >>> pyscipopt.Model().optimize()
    feasible solution found by trivial heuristic after 0.0 seconds, objective value 0.000000e+00
    presolving:
    presolving (1 rounds: 1 fast, 0 medium, 0 exhaustive):
     0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
     0 implications, 0 cliques
    transformed 1/1 original solutions to the transformed problem space
    Presolving Time: 0.00
    
    SCIP Status        : problem is solved [optimal solution found]
    Solving Time (sec) : 0.00
    Solving Nodes      : 0
    Primal Bound       : +0.00000000000000e+00 (1 solutions)
    Dual Bound         : +0.00000000000000e+00
    Gap                : 0.00 %
    >>>

**Comment by leethargo** [comment]
This should be tested with different Python versions and such.

Also, I'd like to build SCIP with IPOPT, actually.

**Comment by leethargo** [comment]
I've looked into making a `conda` recipe for IPOPT (branch `conda-ipopt`), but this is more involved. I'm guessing that we can use BLAS and Lapack from the `mkl` package, but to get HSL, one needs to register on some homepage :frowning:. I'm not sure what other libraries (such as METIS) are really needed.

Do you have any idea?

**Comment by mattmilten** [comment]
As far as I know, Ipopt can also be compiled without a licensed solver.

**Comment by leethargo** [comment]
I don't think the recipe for ipopt is correct. In `ipopt_addlibs_cpp.txt`, there's `-L/opt/anaconda1anaconda2anaconda3/lib` which seems to be related to [broken conda builds](https://github.com/ContinuumIO/anaconda-issues/issues/137).

**Comment by leethargo** [comment]
One annoying thing about `make scipoptlib`: Now that I manually create the symlink to IPOPT, the other symlinks in `make scip` are no longer created non-interactively and I have to press [Enter].

**Comment by leethargo** [comment]
Now that #8 is merged, I will rebuild the packages and this could be closed.
