### ISSUE TITLE
Handling of constraint releases not uniform across addCons methods

### ISSUE THREAD

**Issue by GregorCH** [SCIP-Interfaces/PySCIPOpt#51]
Not all addCons methods, namely addConsSOS1 and addConsSOS2, release the constraint pointer at the end of the method.

The method `_addLinCons ` does the following:
```
        PY_SCIP_CALL(SCIPaddCons(self._scip, scip_cons))
        PyCons = Constraint.create(scip_cons)
        PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons))

        return PyCons
```

However, I think none of the two approaches is really correct. When the PyCons is created, it has a pointer to the scip_cons internally. Only when this object is freed, a SCIPreleaseCons should be called, in my opinion.

This should currently not matter much, because none of the examples I have looked at so far ever use the returned PyCons object.

**Comment by fserra** [comment]
The discussion about how to correctly free objects is "ongoing" on issue #26

**Comment by GregorCH** [comment]
@fserra , thanks for pointing me there. This issue can hence be closed as a duplicate.
