### ISSUE TITLE
Installation problem using pip

### ISSUE THREAD

**Issue by ppallesen** [SCIP-Interfaces/PySCIPOpt#54]
Hi 
I'm trying to install pyscipopt, but I'm running into some problems. I have installed the SCIP and completed the test succesfully. But when I run pip install pyscipopt I get det following output.
I'm using ubuntu 16 and anaconda. I have added 'export SCIPOPTDIR=~/programs/scipoptsuite-4.0.0' to my .barchrc file. Scipy is updated and python dev installed.
Do you have any ideas what I'm missing?

---------------------------------------------------------------------

Collecting pyscipopt
  Using cached PySCIPOpt-1.0.2.tar.gz
Building wheels for collected packages: pyscipopt
  Running setup.py bdist_wheel for pyscipopt ... error
  Complete output from command /home/peter/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HbQXGx/pyscipopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpr5VaLEpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyscipopt
  copying pyscipopt/__init__.py -> build/lib.linux-x86_64-2.7/pyscipopt
  copying pyscipopt/Multidict.py -> build/lib.linux-x86_64-2.7/pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/pyscipopt
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/peter/programs/scipoptsuite-4.0.0/include -I/home/peter/anaconda2/include/python2.7 -c pyscipopt/scip.c -o build/temp.linux-x86_64-2.7/pyscipopt/scip.o
  pyscipopt/scip.c:306:23: fatal error: scip/scip.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyscipopt
  Running setup.py clean for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
  Running setup.py install for pyscipopt ... error
    Complete output from command /home/peter/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HbQXGx/pyscipopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NDmx1R-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyscipopt
    copying pyscipopt/__init__.py -> build/lib.linux-x86_64-2.7/pyscipopt
    copying pyscipopt/Multidict.py -> build/lib.linux-x86_64-2.7/pyscipopt
    running build_ext
    building 'pyscipopt.scip' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/pyscipopt
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/peter/programs/scipoptsuite-4.0.0/include -I/home/peter/anaconda2/include/python2.7 -c pyscipopt/scip.c -o build/temp.linux-x86_64-2.7/pyscipopt/scip.o
    pyscipopt/scip.c:306:23: fatal error: scip/scip.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/peter/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HbQXGx/pyscipopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NDmx1R-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-HbQXGx/pyscipopt/

**Comment by mattmilten** [comment]
Hi! Could you please check that the directory `/home/peter/programs/scipoptsuite-4.0.0/include` exists and that it contains the SCIP header (scip/scip.h for isntance)? I suppose you did not run `make install` for the SCIPOpt Suite but rather only `make`. Only the `install` will copy the necessary header files to an include directory. Alternatively, you may create a softlink from `scipoptsuite-4.0.0/scip-4.0.0/src` to `scipoptsuite-4.0.0/include` using `ln -s`.

**Comment by ppallesen** [comment]
Thank you very much. You were right. Sorry for forgetting to type make install

**Comment by RicardoGazquez** [comment]
Hi,

Sorry for open a closed issue but I have a similar error than @ppallesen (really, i think that it is the same error). When I have installed SCIP, I have made the make in the install process of scipsuite-7.0.2. I have compiled with the following make:
make ZIMPL=false GMP=false ZLIB=false READLINE=false OPT=dbg

I ran the make test of SCIP an it worked well. After install Scip-7, I have run:
python -m pip install pyscipopt
However, i got the same probem:
ERROR: Command errored out with exit status 1:
   command: /home/ubuntuor/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dfcl73o8
       cwd: /tmp/pip-install-5k_rpxje/pyscipopt/
  Complete output (37 lines):
  Using include path </tmp/pip-install-5k_rpxje/pyscipopt/src>.
  Using SCIP library <scip> at </tmp/pip-install-5k_rpxje/pyscipopt/lib>.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/Multidict.py -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/__init__.py -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/scip.pyx -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/scip.pxd -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/relax.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/expr.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/nodesel.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/pricer.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/sepa.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/event.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/heuristic.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/lp.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/branchrule.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/benders.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/propagator.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/benderscut.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/conshdlr.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  copying src/pyscipopt/presol.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  creating build/temp.linux-x86_64-3.8/src/pyscipopt
  gcc -pthread -B /home/ubuntuor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-install-5k_rpxje/pyscipopt/src -I/home/ubuntuor/anaconda3/include/python3.8 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.8/src/pyscipopt/scip.o
  src/pyscipopt/scip.c:633:10: fatal error: scip/scip.h: No such file or directory
    633 | #include "scip/scip.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyscipopt
  Running setup.py clean for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
    Running setup.py install for pyscipopt ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntuor/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a1dl89d1/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntuor/anaconda3/include/python3.8/pyscipopt
         cwd: /tmp/pip-install-5k_rpxje/pyscipopt/
    Complete output (37 lines):
    Using include path </tmp/pip-install-5k_rpxje/pyscipopt/src>.
    Using SCIP library <scip> at </tmp/pip-install-5k_rpxje/pyscipopt/lib>.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/Multidict.py -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/__init__.py -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/scip.pyx -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/scip.pxd -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/relax.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/expr.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/nodesel.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/pricer.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/sepa.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/event.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/heuristic.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/lp.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/branchrule.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/benders.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/propagator.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/benderscut.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/conshdlr.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    copying src/pyscipopt/presol.pxi -> build/lib.linux-x86_64-3.8/pyscipopt
    running build_ext
    building 'pyscipopt.scip' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/pyscipopt
    gcc -pthread -B /home/ubuntuor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-install-5k_rpxje/pyscipopt/src -I/home/ubuntuor/anaconda3/include/python3.8 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.8/src/pyscipopt/scip.o
    src/pyscipopt/scip.c:633:10: fatal error: scip/scip.h: No such file or directory
      633 | #include "scip/scip.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntuor/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5k_rpxje/pyscipopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a1dl89d1/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntuor/anaconda3/include/python3.8/pyscipopt Check the logs for full command output.

@mattmilten, do you have any idea why cant i install pyscipopt?

Sorry the inconveniences.
Thank you in advance.

Regards,
Ricardo

**Comment by mattmilten** [comment]
Dear Ricardo,

Please follow the installation instructions *precisely* - then would not see these errors. And please format your post for better readability and don't reactivate such an old issue.

Cheers,
Matthias
