### ISSUE TITLE
How to use constraint handlers methods

### ISSUE THREAD

**Issue by bhzunami** [SCIP-Interfaces/PySCIPOpt#58]
How can I get the method _CONSRESPROP_ triggered in a constraint handler for domain propagation?

I have implemented the three methods _conscheck_, _consenfolp_ and _conslock_. I also added the method _consresprop_ but the method never get called.

```
model = Model("Election")
conshdlr = ElectionHdlr(s, row=row, col=col, cons=constituency, logger=logger)
model.includeConshdlr(conshdlr, "election",  "Election", chckpriority=-10000,
                                       needscons=False, propfreq=10)
model.setBoolParam("misc/allowdualreds", False)

# Why is this necessary?
cons1 = model.createCons(conshdlr, "election")
conshdlr.createData(cons1, 10, "cons1_anothername")
model.addPyCons(cons1)
```

I would like to use the domain propagation for setting some constraints during the solve process. Are there any examples?

Thanks

**Comment by fserra** [comment]
Hi @bhzunami  I am sorry I am just seeing this!

The consresprop callback is for resolving conflicts. If you just want to have some propagation you have to implement the consprop callback. For more information look here: http://scip.zib.de/doc/html/CONS.php

What do you mean by "setting some constraints" ? If you want to add a constraint you should rather use the cut callback: conssepalp or conssepasol

In the file `test_alldiff` the constraint handler implements the `consprop` callback.

Hope this helps

**Comment by bhzunami** [comment]
Thanks for your answer. I used the consprop callback for the domain propagation with good results.
