### ISSUE TITLE
removing and adding constraints

### ISSUE THREAD

**Issue by martihj** [SCIP-Interfaces/PySCIPOpt#67]
I want to solve successive optimization problems, by removing and adding a set of constraints. I'm not sure how this may best be achieved. In the C-API there is a method to disable/enable a constraint, would this be the way to go? If it is, would it be possible to extend the python interface to include this functionality?

**Comment by mattmilten** [comment]
Yes, using `SCIPconsActivate/Deactivate()` would probably work for your case. @fserra, do you agree that we should implement this feature?

**Comment by martihj** [comment]
I would also like to update objective coefficients between the iterations. I see that this also is implemented in the C-API but not in the python interface. I'll try to see if I can add this feature myself, but hopefully you agree that these are both useful to be implemented.

**Comment by mattmilten** [comment]
Updating the objective is already supported. Call `setObjective(<new obj>, clear=False)` to keep all other objective coefficients.

**Comment by fserra** [comment]
mmm so it depends on what @martihj actually wants. Note that `SCIPdisableCons` can't be called in the problem stage. Even more, there is an assert that the constraint is not original, so it can only be applied to transformed constraints. 

Take a look at the tsp example (examples/finished/tsp.py). To add a new constraint, we free the transformed problem first. So then, disabling wouldn't work.

I think that the correct way of doing this is with `SCIPdelCons`

But sure, we can support all of them

**Comment by mattmilten** [comment]
I'm going to put in support for SCIPdelCons() and SCIPdelConsLocal().
