### ISSUE TITLE
option to use debug mode in `setup.py`

### ISSUE THREAD

**Issue by mattmilten** [SCIP-Interfaces/PySCIPOpt#69]
as discussed in #68

**Comment by fserra** [comment]
but what about people that install it through a package manager? do you want to distribute  two versions? scip-dbg and scip? or is there an elegant solution to this?

**Comment by mattmilten** [comment]
We don't distribute pre-compiled debug versions. People that want to try the debug code will simply have to get the GitHub version and install it from there.
