### ISSUE TITLE
Problem with importing PySCIPOpt

### ISSUE THREAD

**Issue by solafishes** [SCIP-Interfaces/PySCIPOpt#83]
I am trying to install PySCIPOpt on Ubuntu 16.04. The shared library is at /usr/local/lib and the binary at /usr/local/bin. After building PySCIPOpt from source, I got the following error when trying to import the package from python. I think libscipopt.so is already in position. Your input is much appreciated!!!

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pyscipopt/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pyscipopt/scip.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pyscipopt/scip.py", line 6, in __bootstrap__
ImportError: libscipopt.so: cannot open shared object file: No such file or directory

/usr/local/lib$ ls
libobjscip.so
libscip-4.0.0.linux.x86_64.gnu.opt.a
libscip-4.0.0.linux.x86_64.gnu.opt.so
libscip.a
libscip.linux.x86_64.gnu.opt.a
libscip.linux.x86_64.gnu.opt.so
libscipopt-4.0.0.linux.x86_64.gnu.opt.a
libscipopt-4.0.0.linux.x86_64.gnu.opt.so
libscipopt.a
libscipopt.so
libscip.so
libsoplex-3.0.0.linux.x86_64.gnu.opt.a
libsoplex-3.0.0.linux.x86_64.gnu.opt.so
libsoplex.a

**Comment by mattmilten** [comment]
How did you get the `libscipopt.so`? Did you built the code yourself or are you using the precompiled library? In any case, you also need to have the headers available. 
Did you specify `SCIPOPTDIR` when running `python setup.py install`?
You might also check `echo $LD_LIBRARY_PATH` for `/usr/local/`.

**Comment by mattmilten** [comment]
Also, the binary is not required, only the library and the header files of the SCIP Opt Suite.

**Comment by solafishes** [comment]
@mattmilten I built it myself and yes the headers are there. I did specify SCIPOPTDIR (see below)
siyu@siyu-VirtualBox:~$ echo $SCIPOPTDIR
/usr/local

**Comment by mattmilten** [comment]
How does your PySCIPOpt installation command look like? Could you please paste the command including the entire output?

**Comment by solafishes** [comment]
I guess it has something tudo with the directory I am using. The sudo causes the failure of linking the so. For now I use LD_LIBRARY_PATH and solve the problem.

**Comment by mattmilten** [comment]
Huh, feel free to add another comment when you found a better solution.
