### ISSUE TITLE
Slack variables?

### ISSUE THREAD

**Issue by joaopedroso** [SCIP-Interfaces/PySCIPOpt#84]
Is there a way of accessing slack variables associated to a constraint in PySCIPOpt?

**Comment by mattmilten** [comment]
We could add methods for computing the activity of a constraint and then you could calculate the slack by substracting the lhs or the rhs.

**Comment by joaopedroso** [comment]
Yes, that would be good.  You may also add an attribute "getSlack()" to constraints, equivalent to "c.Slack" attribute of Gurobi/Python.

**Comment by mattmilten** [comment]
Adding a `getSlack()` is not that easy since we don't which side is supposed to be active. You would need to specify whether rhs or lhs is desired.

**Comment by joaopedroso** [comment]
Shouldn't the outcome be the same, whatever side?

**Comment by mattmilten** [comment]
Well, the activity is of course the same but the slack depends on the side.

example:
```
0 <= 2x + y <= 10
activity = 3 (x=1, y=1)
slack_lhs = 3
slack_rhs = 7
```

**Comment by joaopedroso** [comment]
Sorry, I was considering the LHS and RHS of a simple constraint, not one with double bounds.
Indeed, for these constraints computing the difference between the activity and the RHS/LHS is an alternative to having something like getLhsSlack() and getRhsSlack(). Which do you prefer? 

(Gurobi does not seem to have a method for obtaining a constraint's activity.  AMPL has constraint attributes ".body", ".lslack", ".rslack"; and ".slack" is the minimum of lslack and uslack.)
