### ISSUE TITLE
conda recipe Linux 64bits/32bits

### ISSUE THREAD

**Issue by arita37** [SCIP-Interfaces/PySCIPOpt#85]
Hello,

Just wondering if the package is now available in conda, after the recipe was finalized.
On conda, we can only see this one :  

https://anaconda.org/leethargo/pyscipopt/files

Thank you

**Comment by mattmilten** [comment]
No, it's not available in conda. You would need to download the lib and and the headers from https://scip.zib.de and then run `pip install pyscipopt`.

There are some license and download tracking issues so for now we didn't continue working on the conda package.

Is this of great importance for you?

**Comment by arita37** [comment]
Hello,

There are packages and version conflicts with pip (pip can erase files when installing).

Conda make it cleaner and easier to install.

Maybe, if we can summarize the remaining steps for conda package into one page/ one issue: Community (Myself include) can help finalizing.


Thanks vm






On 17 Jul 2017, at 17:48, Matthias Miltenberger <notifications@github.com> wrote:

No, it's not available in conda. You would need to download the lib and and the headers from https://scip.zib.de and then run pip install pyscipopt.

There are some license and download tracking issues so for now we didn't continue working on the conda package.

Is this of great importance for you?

―

**Comment by mattmilten** [comment]
I do see the added benefit of having an easy to use conda package. Unfortunately, I have virtually no experience with ceating conda packages and don't know the common practices.

If you could help us, this would be fantastic!

What are the basic ingredients to create a conda recipe? I am unsure how to package the SCIPOptSuite dependencies (lib and headers).

**Comment by arita37** [comment]
Hello,

Am not an expert, but some ressources here:

https://www.pydanny.com/building-conda-packages-for-multiple-operating-systems.html

http://conda-test.pydata.org/docs/build_tutorials/pkgs.html

It can be built from Pypi package.

They have a git for issues too.
https://github.com/conda/conda-build


Thank you for your very good work on SCIP Optimizer.

Kind regards








Matthias Miltenberger wrote:

**Comment by arita37** [comment]
This recipe template may help :  
https://goo.gl/7hmfNm

**Comment by mattmilten** [comment]
Unfortunately, I don't see the conda package going anywhere soon. Users are supposed to download and install SCIP from http://scip.zib.de and afterwards install PySCIPOpt. We will not be able to package the SCIP Opt sources/libs/headers within the conda package so there is no added benefit over the installation via PyPI, aka `pip install`.
