### ISSUE TITLE
Different solutions by PySCIP and C++ 

### ISSUE THREAD

**Issue by solafishes** [SCIP-Interfaces/PySCIPOpt#88]
I am trying SCIP on a mixed integer programming problem. While the python API gives the correct solution (figure 1), c++ version is not able to (figure 2). I found that both solution processes give exactly the same presolving result, which suggests I made no mistake in creating variables and constraints. Yet, I am not able to tell why this happens...

![python](https://user-images.githubusercontent.com/2771545/29767371-c12f283a-8c14-11e7-88b0-e22229fd580f.png)

![c](https://user-images.githubusercontent.com/2771545/29767379-ca1f172a-8c14-11e7-8761-fdcfd9dc0218.png)

**Comment by mattmilten** [comment]
Interesting! Are you using the same settings and the same LP solver? One of the two solutions is either suboptimal or incorrect. How do you know that the first solution is correct? Could you please share your model formulation (both Python and C++)?

**Comment by fserra** [comment]
You could also take the solution of the C++ model (which seems to have better objective value) and check if it satisfies your Python constraints.

**Comment by mattmilten** [comment]
Is this still relevant, i.e. is it happening also for the new SCIP 4.0.1 release and PySCIPOpt v1.2.0?

**Comment by mattmilten** [comment]
Closed because of inactivity/incompleteness.
