### ISSUE TITLE
Multi threading support is present ?

### ISSUE THREAD

**Issue by bbalegere** [SCIP-Interfaces/PySCIPOpt#93]
Does PySCIPOpt implement multithreading?

Also which solver does it use by default? Is it SoPlex ?

If I have Gurobi installed, can I use that?

**Comment by mattmilten** [comment]
No, PySCIPOpt itself does not implement multi-threading. Parallel processing within SCIP is still experimental (you might want to check out https://ug.zib.de for some massive parallelization using SCIP).

PySCIPOpt is also completely unaware of the used LP solver within SCIP. This solely depends on how you built the SCIP library that PySCIPOpt is linked against. So, yes, it's completely fine to use SCIP/Gurobi with PySCIPOpt. Information on how to build the library with a different LP solver than SoPlex is provided in the SCIP documentation (set the `LPS` parameter to e.g. `grb`).

**Comment by bbalegere** [comment]
How was the library built for the wheel file available at https://pypi.python.org/pypi/PySCIPOpt ?
I am using that and I want to know which solver is being used.
